
(function(){
  'use strict';
  if(window.__ojV35RolePdfBuild) return;
  window.__ojV35RolePdfBuild = true;
  const VERSION = 'OceanJet V35 Role-Controlled Professional PDF Build';
  const ROLE_KEY = 'oj_v35_active_role';
  const $id = id => document.getElementById(id);
  const qsa = sel => Array.from(document.querySelectorAll(sel));
  const app = () => document.querySelector('.app') || document.body;
  const esc = s => String(s==null?'':s).replace(/[&<>"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const now = () => new Date().toLocaleString('en-PH',{hour12:true});
  const toast35 = msg => { try{ if(typeof toast==='function') toast(msg); else console.log(msg); }catch(e){ console.log(msg); } };
  const readLS = (key, fallback) => { try{ const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; }catch(e){ return fallback; } };
  const getDB = () => { try{ return DB || null; }catch(e){ return null; } };
  function ensureView(name){ let v=$id('view-'+name); if(!v){ v=document.createElement('div'); v.id='view-'+name; v.className='view'; app().appendChild(v); } return v; }
  function getRole(){ try{ if(typeof currentRole !== 'undefined'){ if(currentRole === 'supervisor') return 'admin'; if(currentRole === 'cashier') return 'cashier'; } }catch(e){} return sessionStorage.getItem(ROLE_KEY) || 'pax'; }
  function setLegacyRole(role){ try{ currentRole = role === 'admin' ? 'supervisor' : role === 'cashier' ? 'cashier' : null; }catch(e){} }
  function setRole(role, target){
    role = (role === 'admin' || role === 'cashier') ? role : 'pax';
    sessionStorage.setItem(ROLE_KEY, role); setLegacyRole(role);
    const ov=$id('loginOverlay'); if(ov){ ov.classList.remove('v15-admin-login'); ov.style.setProperty('display','none','important'); }
    document.body.classList.add('oj35-ready');
    document.body.classList.toggle('oj35-pax', role==='pax'); document.body.classList.toggle('oj35-cashier', role==='cashier'); document.body.classList.toggle('oj35-admin', role==='admin');
    const badge=$id('roleBadge'); if(badge) badge.textContent = role==='admin' ? '👑 Admin' : role==='cashier' ? '💼 Cashier' : '👤 Passenger';
    try{ window.buildDrawerMenu(); }catch(e){}
    window.showView(target || 'v35-home');
  }
  const PAX = [['v35-home','🏠','Passenger Home'],['calculator','🧮','Baggage Fee'],['fares','💵','Fares'],['schedules','🕐','Schedules'],['damage','📷','Damage Report'],['lostbaggage','🧳','Lost/Damaged Form'],['claimstatus','🔎','Claim Status'],['v35-cashier-login','💼','Cashier Login'],['v35-admin-login','🔐','Admin Login']];
  const CASHIER = [['v35-home','🏠','Cashier Home'],['dashboard','📊','Cashier Dashboard'],['calculator','🧮','Baggage Calc'],['damage','📷','Damage Capture'],['lostbaggage','🧳','Claim Form'],['claimstatus','🔎','Claim Status'],['staffcounter','👥','Staff Counter'],['v32-field','🧾','Field Intake'],['v30-claim','🧳','Claim Studio'],['history','📋','Transactions'],['v35-reports','📄','PDF Center'],['v35-admin-login','🔐','Admin Login']];
  const ADMIN = [['v35-home','🏠','Admin Home'],['dashboard','📊','Dashboard'],['calculator','🧮','Baggage Calc'],['fares','💵','Fares'],['schedules','🕐','Schedules'],['damage','📷','Damage Detector'],['lostbaggage','🧳','Lost/Damaged Form'],['claimstatus','🔎','Claim Status'],['staffcounter','👥','Staff Counter'],['history','📋','History'],['v35-reports','📄','PDF Center'],['exportcenter','📤','Export Center'],['admin','⚙️','Admin Panel'],['sitehealth','🛟','Site Health'],['contentmanager','📝','Content Manager'],['v33-command','🧭','V33 Command'],['v33-staff','🎒','Staff Workbench'],['v33-data','🛡️','Data Guardian'],['v30-os','🚢','Service OS'],['v30-admin','🛠️','V30 Admin'],['v31-ai','🤖','Offline AI'],['v27-guardian','🛡️','Guardian'],['v29-admin','🛠️','V29 Admin']];
  const PAX_ALLOWED = new Set(PAX.map(x=>x[0]).concat(['portal','v33-passenger','v30-care']));
  const CASHIER_ALLOWED = new Set(CASHIER.map(x=>x[0]).concat(PAX.map(x=>x[0])).concat(['portal','v33-passenger','v33-staff','v30-care','v30-sync','exportcenter']));
  const ALWAYS = new Set(['v35-home','v35-cashier-login','v35-admin-login']);
  const ALIAS = {calc:'calculator', quickdesk:'v35-home'};
  function canOpen(name){ const role=getRole(); name=ALIAS[name]||name; if(ALWAYS.has(name)) return true; if(role==='admin') return true; if(role==='cashier') return CASHIER_ALLOWED.has(name); return PAX_ALLOWED.has(name); }
  function navForRole(){ const role=getRole(); return role==='admin' ? ADMIN : role==='cashier' ? CASHIER : PAX; }
  window.buildDrawerMenu = function(){
    const menu=$id('drawerMenu'); if(!menu) return;
    const rows = navForRole().map(i => `<div class="drawer-item" data-view="${i[0]}" onclick="showView('${i[0]}')"><i>${i[1]}</i> ${i[2]}</div>`);
    if(getRole()!=='pax') rows.push(`<div class="drawer-item" data-view="v35-lock" onclick="oj35Logout()"><i>🚪</i> Return to Passenger Mode</div>`);
    menu.innerHTML = rows.join('');
    const dl=document.querySelector('.drawer-logout'); if(dl){ dl.textContent = getRole()==='pax' ? 'Passenger Mode' : '🚪 Return to Passenger'; dl.onclick = window.oj35Logout; }
  };
  function activate(name){ qsa('.view').forEach(v=>v.classList.remove('active')); ensureView(name).classList.add('active'); qsa('#drawerMenu .drawer-item').forEach(el=>el.classList.toggle('active', el.dataset.view===name)); try{ window.scrollTo({top:0,behavior:'smooth'}); }catch(e){ window.scrollTo(0,0); } }
  function chip(text,type){ return `<span class="oj35-chip ${type||''}">${esc(text)}</span>`; }
  function action(ico,title,sub,view,type){ return `<div class="oj35-action ${type||''}" onclick="showView('${view}')"><span class="ico">${ico}</span><b>${esc(title)}</b><small>${esc(sub)}</small></div>`; }
  function actionFn(ico,title,sub,fn,type){ return `<div class="oj35-action ${type||''}" onclick="${fn}"><span class="ico">${ico}</span><b>${esc(title)}</b><small>${esc(sub)}</small></div>`; }
  function collectClaims(){ const keys=['oj_v22_claims','oj_v23_claims','oj_v24_claims','oj_v30_tickets','oj_v30_claims','oj_claims','oceanjet_claims']; let out=[]; keys.forEach(k=>{ const v=readLS(k,[]); if(Array.isArray(v)) out=out.concat(v.map(x=>Object.assign({source:k},x))); }); return out; }
  function collectDamage(){ const a=readLS('oj_damage_master_log_v11',[]); return Array.isArray(a)?a:[]; }
  function kpis(){ const h=(getDB()&&Array.isArray(getDB().history))?getDB().history:[]; const claims=collectClaims(); const damage=collectDamage(); const rev=h.reduce((s,x)=>s+(Number(x.total)||0),0); return `<div class="oj35-grid3"><div class="oj35-kpi"><b>${h.length}</b><span>Transactions</span></div><div class="oj35-kpi"><b>${claims.length}</b><span>Claims</span></div><div class="oj35-kpi"><b>${damage.length}</b><span>Damage Logs</span></div></div><div class="oj35-grid3" style="margin-top:10px"><div class="oj35-kpi"><b>₱${rev.toLocaleString('en-PH')}</b><span>Recorded Revenue</span></div><div class="oj35-kpi"><b>${getRole().toUpperCase()}</b><span>Active Role</span></div><div class="oj35-kpi"><b>PDF</b><span>Exports</span></div></div>`; }
  function renderHome(){
    const role=getRole(), v=ensureView('v35-home');
    if(role==='pax') v.innerHTML = `<div class="card oj35-shell"><div class="oj35-head"><div><h2>👤 Passenger Mode</h2><div class="oj35-sub">No login needed. The site opens as Passenger by default, so passengers only see public tools for fares, schedules, baggage fee checking, reports, and claim status.</div></div>${chip('DEFAULT ACCESS','good')}</div>${kpis()}</div><div class="card"><div class="card-header">Passenger tools only</div><div class="oj35-grid">${action('🧮','Check baggage fee','Official calculator only, clean and simple.','calculator','good')}${action('📷','Report baggage damage','Open detector/evidence workflow.','damage','hot')}${action('🧳','Lost or damaged baggage form','Create a passenger claim record.','lostbaggage','warn')}${action('🔎','Track claim status','Search claim number or last name on this device.','claimstatus','good')}${action('💵','View fares','Passenger fare matrix.','fares','gray')}${action('🕐','View schedules','Route schedule board.','schedules','gray')}</div></div><div class="card"><div class="card-header">Staff login</div><div class="oj35-grid">${action('💼','Cashier Login','For counter staff, receipt handling, and claim processing.','v35-cashier-login','warn')}${action('🔐','Admin Login','For full system control and all reports.','v35-admin-login','hot')}</div><div class="oj35-callout" style="margin-top:10px">Passenger mode hides cashier, staff, admin, backup, and management tools.</div></div>`;
    else if(role==='cashier') v.innerHTML = `<div class="card oj35-shell"><div class="oj35-head"><div><h2>💼 Cashier Workbench</h2><div class="oj35-sub">Cashier sees counter tools only: baggage calculation, receipt work, claim intake, claim processing, transaction history, and PDF reports. Admin-only settings remain hidden.</div></div>${chip('CASHIER ACCESS','warn')}</div>${kpis()}</div><div class="card"><div class="card-header">Cashier workflow</div><div class="oj35-grid">${action('🧮','Baggage Calculator','Compute official baggage fees.','calculator','good')}${action('📄','PDF Receipt / Reports','Export receipts and transaction summaries as PDFs.','v35-reports','warn')}${action('📷','Damage Capture','Capture photos and evidence at counter.','damage','hot')}${action('🧳','Claim Studio','Prepare structured claim packet.','v30-claim','warn')}${action('👥','Staff Counter','Review passenger requests.','staffcounter','gray')}${action('📋','Transactions','Review saved baggage calculations.','history','gray')}</div></div><div class="card"><div class="card-header">Role switch</div><div class="oj35-grid">${action('🔐','Admin Login','Unlock all system tools.','v35-admin-login','hot')}${actionFn('🚪','Return to Passenger Mode','Locks cashier tools and returns the app to public view.','oj35Logout()','gray')}</div></div>`;
    else v.innerHTML = `<div class="card oj35-shell"><div class="oj35-head"><div><h2>👑 Admin Control Center</h2><div class="oj35-sub">Admin has everything: passenger tools, cashier tools, reports, backups, health checks, admin panel, and advanced service modules.</div></div>${chip('FULL ACCESS','hot')}</div>${kpis()}</div><div class="card"><div class="card-header">Admin groups</div><div class="oj35-grid">${action('👤','Passenger Experience','Open public passenger tools.','v33-passenger','good')}${action('💼','Cashier / Staff Tools','Open staff workbench and claim processing.','v33-staff','warn')}${action('📄','Professional PDF Center','Receipts, claims, transactions, and audit reports.','v35-reports','hot')}${action('⚙️','Admin Panel','Routes, pricing, analytics, and settings.','admin','hot')}${action('🛡️','Data Guardian','Storage health and recovery utilities.','v33-data','gray')}${action('🧭','Command Center','Search and launch all modules.','v33-command','gray')}</div></div><div class="card"><div class="card-header">Operational modules</div><div class="oj35-grid">${action('🚢','Service OS','Passenger care and sync tools.','v30-os','good')}${action('🤖','Offline AI','SOP helper and assistant.','v31-ai','gray')}${action('🗺️','Route Intelligence','Live map and pressure board.','v33-map','gray')}${action('🛟','Site Health','Health checks and diagnostics.','sitehealth','warn')}${action('📤','Export Center','Legacy export screen now protected.','exportcenter','warn')}${action('📝','Content Manager','Manage notices/content.','contentmanager','gray')}</div></div>`;
  }
  function renderLogin(which){ const isAdmin = which === 'admin'; const v=ensureView(isAdmin?'v35-admin-login':'v35-cashier-login'); v.innerHTML = `<div class="card oj35-shell oj35-login"><div class="oj35-head"><div><h2>${isAdmin?'🔐 Admin Login':'💼 Cashier Login'}</h2><div class="oj35-sub">${isAdmin?'Unlock full access to all passenger, cashier, reporting, backup, and admin tools.':'Unlock counter-only tools for baggage fee processing, claim intake, receipts, and PDF transaction reports.'}</div></div>${chip(isAdmin?'FULL ACCESS':'COUNTER ACCESS',isAdmin?'hot':'warn')}</div><div class="input-group"><label>Username</label><input id="oj35_${which}_user" autocomplete="username" placeholder="Enter ${isAdmin?'admin':'cashier'} username"></div><div class="input-group"><label>Password</label><input id="oj35_${which}_pass" type="password" autocomplete="current-password" placeholder="Enter password" onkeypress="if(event.key==='Enter')oj35DoLogin('${which}')"></div><button class="primary block" onclick="oj35DoLogin('${which}')">Login as ${isAdmin?'Admin':'Cashier'}</button><button class="accent block" style="margin-top:8px" onclick="oj35Logout()">Continue as Passenger</button><div class="oj35-callout" style="margin-top:12px">${isAdmin?'Admin can see and manage everything.':'Cashier cannot see admin settings, full backups, system configuration, or admin-only dashboards.'}</div></div>`; setTimeout(()=>{ const u=$id(`oj35_${which}_user`); if(u) u.focus(); },60); }
  window.oj35DoLogin = function(which){ const u=($id(`oj35_${which}_user`)?.value||'').trim(), p=($id(`oj35_${which}_pass`)?.value||'').trim(); if(!u || !p) return toast35('Please enter username and password.'); const creds=(getDB()&&getDB().creds)?getDB().creds:{}; const cashier=creds.cashier||{u:'cashier',p:'cashier'}, supervisor=creds.supervisor||{u:'demo',p:'demo'}; const okCashier=which==='cashier' && ((u===cashier.u&&p===cashier.p)||(u==='cashier'&&p==='cashier')); const okAdmin=which==='admin' && ((u===supervisor.u&&p===supervisor.p)||(u==='admin'&&p==='admin')||(u==='demo'&&p==='demo')||(u==='supervisor'&&p==='supervisor')); if(okCashier){ toast35('Cashier tools unlocked.'); setRole('cashier','v35-home'); return; } if(okAdmin){ toast35('Admin tools unlocked.'); setRole('admin','v35-home'); return; } toast35('Invalid login for '+(which==='admin'?'Admin':'Cashier')+'.'); };
  window.oj35Logout = function(){ toast35('Passenger mode active.'); setRole('pax','v35-home'); }; window.logout = window.oj35Logout;
  window.attemptLogin = function(){ const u=($id('loginUser')?.value||'').trim(), p=($id('loginPass')?.value||'').trim(); const creds=(getDB()&&getDB().creds)?getDB().creds:{}; const cashier=creds.cashier||{u:'cashier',p:'cashier'}, supervisor=creds.supervisor||{u:'demo',p:'demo'}; if((u===cashier.u&&p===cashier.p)||(u==='cashier'&&p==='cashier')) return setRole('cashier','v35-home'); if((u===supervisor.u&&p===supervisor.p)||(u==='admin'&&p==='admin')||(u==='demo'&&p==='demo')||(u==='supervisor'&&p==='supervisor')) return setRole('admin','v35-home'); toast35('Invalid username or password.'); };
  function cleanText(s){ return String(s==null?'':s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[₱]/g,'PHP ').replace(/[^\x09\x0A\x0D\x20-\x7E]/g,'?'); }
  function wrapLines(lines, width){ const out=[]; (Array.isArray(lines)?lines:[lines]).forEach(line=>{ line=cleanText(line); if(line===''){out.push(''); return;} let s=line; while(s.length>width){ let cut=s.lastIndexOf(' ', width); if(cut<24) cut=width; out.push(s.slice(0,cut)); s=s.slice(cut).trim(); } out.push(s); }); return out; }
  function pdfEscape(s){ return cleanText(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)'); }
  function makePDF(title, lines, filename){ title=cleanText(title||'OceanJet Report'); const all=wrapLines([title,'Ocean Fast Ferries / OceanJet','Generated: '+now(),'Role: '+getRole().toUpperCase(),''].concat(lines||[]),86); const pages=[]; for(let i=0;i<all.length;i+=42) pages.push(all.slice(i,i+42)); const objs=[null]; objs[1]='<< /Type /Catalog /Pages 2 0 R >>'; objs[2]=''; objs[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'; const kids=[]; pages.forEach((page,idx)=>{ let y=760, stream='BT\n'; page.forEach((line,i)=>{ const size=(idx===0&&i===0)?17:(i<4?10:9); stream += `/F1 ${size} Tf 48 ${y} Td (${pdfEscape(line)}) Tj\n`; y -= (idx===0&&i===0)?22:15; }); stream += 'ET\n'; const len=new TextEncoder().encode(stream).length; const contentId=objs.length; objs.push(`<< /Length ${len} >>\nstream\n${stream}endstream`); const pageId=objs.length; kids.push(pageId+' 0 R'); objs.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`); }); objs[2]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${kids.length} >>`; let pdf='%PDF-1.4\n'; const offsets=[0]; for(let i=1;i<objs.length;i++){ offsets[i]=new TextEncoder().encode(pdf).length; pdf += `${i} 0 obj\n${objs[i]}\nendobj\n`; } const xrefPos=new TextEncoder().encode(pdf).length; pdf += `xref\n0 ${objs.length}\n0000000000 65535 f \n`; for(let i=1;i<objs.length;i++) pdf += String(offsets[i]).padStart(10,'0')+' 00000 n \n'; pdf += `trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF`; const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([pdf],{type:'application/pdf'})); a.download=filename||('oceanjet_report_'+Date.now()+'.pdf'); document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1000); toast35('PDF exported.'); }
  function txLines(){ const h=(getDB()&&Array.isArray(getDB().history))?getDB().history:[]; const rows=['TRANSACTION SUMMARY','Total records: '+h.length,'']; if(!h.length) rows.push('No local transactions recorded yet.'); h.slice(-80).reverse().forEach((x,i)=>rows.push(`${i+1}. ${x.time||''} | ${x.route||''} | ${x.mode||''} | ${x.cls||''} | Pax ${x.pax||''} | ${x.weight||''}kg | PHP ${Number(x.total||0).toFixed(2)}`)); return rows; }
  function claimLines(){ const claims=collectClaims(), damage=collectDamage(); const rows=['CLAIMS AND DAMAGE SUMMARY','Passenger claims: '+claims.length,'Damage evidence logs: '+damage.length,'']; if(!claims.length&&!damage.length) rows.push('No local claims or damage evidence recorded yet.'); claims.slice(0,50).forEach((c,i)=>rows.push(`${i+1}. ${c.claimId||c.id||c.reference||'CLAIM'} | ${c.name||c.lastName||c.passenger||''} | ${c.issue||c.type||c.status||''} | ${c.route||''} | ${c.tag||c.tagNo||''}`)); damage.slice(0,40).forEach((d,i)=>rows.push(`D${i+1}. ${d.id||d.caseId||'DAMAGE'} | ${d.route||''} | ${d.color||''} ${d.size||''} | ${d.damageType||d.damage||d.notes||''}`)); return rows; }
  function systemLines(){ const h=(getDB()&&Array.isArray(getDB().history))?getDB().history:[]; const claims=collectClaims(); const damage=collectDamage(); let keys=[]; try{ for(let i=0;i<localStorage.length;i++) keys.push(localStorage.key(i)); }catch(e){} return ['SYSTEM AUDIT SUMMARY','Build: '+VERSION,'Current role: '+getRole(),'Transactions: '+h.length,'Claims: '+claims.length,'Damage logs: '+damage.length,'Local storage keys: '+keys.length,'','Largest/local keys:',...keys.slice(0,35).map(k=>'- '+k)]; }
  window.oj35ExportReceiptPDF=function(){ const r=$id('receipt'); let text=''; try{ if(typeof lastReceiptText !== 'undefined' && lastReceiptText) text=lastReceiptText; }catch(e){} if(!text&&r) text=r.innerText; if(!text) text='No active receipt yet. Compute baggage first, then export receipt PDF.'; makePDF('OceanJet Official Baggage Receipt',String(text).split(/\n+/),'oceanjet_baggage_receipt.pdf'); };
  window.downloadReceipt=window.oj35ExportReceiptPDF; window.oj35ExportTransactionsPDF=function(){makePDF('OceanJet Transactions PDF Report',txLines(),'oceanjet_transactions_report.pdf');}; window.oj35ExportClaimsPDF=function(){makePDF('OceanJet Claims and Damage PDF Report',claimLines(),'oceanjet_claims_damage_report.pdf');}; window.oj35ExportSystemPDF=function(){makePDF('OceanJet System Audit PDF Report',systemLines(),'oceanjet_system_audit_report.pdf');};
  window.oj35ExportTechnicalJSON=function(){ const data={version:VERSION,exportedAt:new Date().toISOString(),role:getRole(),db:(getDB()||{}),claims:collectClaims(),damage:collectDamage()}; const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); a.download='oceanjet_v35_technical_backup.json'; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1000); toast35('Technical JSON backup exported.'); };
  window.exportDatabase=window.oj35ExportSystemPDF; window.exportV6CSV=window.oj35ExportTransactionsPDF; window.v14ExportTransactions=window.oj35ExportTransactionsPDF; window.v14ExportDamageCSV=window.oj35ExportClaimsPDF; window.v14ExportDamageJSON=window.oj35ExportClaimsPDF; window.v14ExportFullBackup=window.oj35ExportSystemPDF; window.v22ExportClaimsCSV=window.oj35ExportClaimsPDF; window.v23ExportTriageCSV=window.oj35ExportClaimsPDF; window.oj33ExportPack=window.oj35ExportSystemPDF;
  function renderReports(){ const v=ensureView('v35-reports'); v.innerHTML = `<div class="card oj35-shell"><div class="oj35-head"><div><h2>📄 Professional PDF Center</h2><div class="oj35-sub">Receipts and reports now export as clean PDF files. JSON is kept only as a clearly labeled technical backup for recovery.</div></div>${chip('PDF EXPORTS','hot')}</div>${kpis()}</div><div class="card"><div class="card-header">PDF exports</div><div class="oj35-grid">${actionFn('🧾','Receipt PDF','Exports the current baggage receipt as PDF.','oj35ExportReceiptPDF()','good')}${actionFn('📋','Transactions PDF','Cashier daily/shift transaction report.','oj35ExportTransactionsPDF()','warn')}${actionFn('🧳','Claims + Damage PDF','Damage, lost baggage, and evidence summary.','oj35ExportClaimsPDF()','hot')}${actionFn('🛡️','System Audit PDF','Admin audit summary and app health report.','oj35ExportSystemPDF()','gray')}</div></div><div class="card"><div class="card-header">Technical recovery only</div><div class="oj35-callout">Use JSON only for restoring or transferring app data. Normal receipts, cashier summaries, claim reports, and admin reports should be PDF.</div><button class="accent block" style="margin-top:10px" onclick="oj35ExportTechnicalJSON()">Export Technical JSON Backup</button></div><div class="card"><div class="card-header">PDF preview content</div><div class="oj35-pdf-preview">${esc(systemLines().concat(['','---','Receipt button uses latest calculator receipt when available.']).join('\n'))}</div></div>`; }
  function polishExportLabels(){ qsa('button').forEach(b=>{ const t=b.textContent||'', fn=b.getAttribute('onclick')||''; if(/Export|Download|Receipt/i.test(t) && /CSV|JSON|Backup|Snapshot|Receipt|export/i.test(t+fn)){ if(/CSV/i.test(t)) b.textContent=t.replace(/CSV/ig,'PDF'); if(/JSON Backup|Export Backup/i.test(t)) b.textContent=t.replace(/JSON Backup/,'System PDF').replace(/Export Backup/,'System PDF'); if(/Download/i.test(t)&&/Receipt/i.test(t)) b.textContent=t.replace(/Download/,'PDF'); } }); polishRoleVisibility(); }
  function polishRoleVisibility(){ if(getRole()!=='pax') return; qsa('button,.oj35-action,.drawer-item').forEach(el=>{ const fn=el.getAttribute('onclick')||'', txt=el.textContent||''; const protectedTool=/(staffcounter|sitehealth|contentmanager|exportcenter|v33-staff|v33-data|v30-admin|v29-admin|v27-guardian|dashboard|history|admin\b|export|backup)/i.test(fn+' '+txt); const loginTool=/Cashier Login|Admin Login|Passenger Mode/i.test(txt); if(protectedTool && !loginTool){ el.style.display='none'; el.classList.add('oj35-lock'); } }); }
  const renderers={'v35-home':renderHome,'v35-cashier-login':()=>renderLogin('cashier'),'v35-admin-login':()=>renderLogin('admin'),'v35-reports':renderReports};
  const oldShow=window.showView;
  window.showView=function(name){ name=ALIAS[name]||name; if(!canOpen(name)){ if(String(name).includes('admin')){ activate('v35-admin-login'); renderLogin('admin'); toast35('Admin login required.'); return; } if(getRole()==='pax' && /(staff|cashier|export|data|ops)/i.test(String(name))){ activate('v35-cashier-login'); renderLogin('cashier'); toast35('Cashier or Admin login required.'); return; } activate('v35-home'); renderHome(); toast35('This tool is not available for the current role.'); return; } if(renderers[name]){ activate(name); renderers[name](); return; } const r=oldShow?oldShow.apply(this,[name]):undefined; setTimeout(polishExportLabels,80); return r; };
  try{ showView=window.showView; }catch(e){}
  function boot(){ try{ ['v35-home','v35-cashier-login','v35-admin-login','v35-reports'].forEach(ensureView); document.body.classList.add('oj35-ready'); const stored=sessionStorage.getItem(ROLE_KEY)||'pax'; setRole(stored,'v35-home'); const brand=document.querySelector('.brand'); if(brand) brand.textContent='OceanJet Baggage Pro'; const title=document.querySelector('title'); if(title) title.textContent='OceanJet Baggage Pro V42'; setTimeout(polishExportLabels,500); ['v22SubmitClaim','v22LookupClaim'].forEach(fn=>{ if(typeof window[fn]==='function' && !window[fn].__oj35Wrapped){ const oldFn=window[fn]; window[fn]=function(){ const r=oldFn.apply(this,arguments); setTimeout(polishRoleVisibility,80); return r; }; window[fn].__oj35Wrapped=true; } }); console.log(VERSION+' loaded'); }catch(e){ console.error('V35 boot error',e); toast35('V35 recovery: '+e.message); } }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})();
