
(function(){
  if(window.__OJ_V33_VERIFIED_REPAIR__) return; window.__OJ_V33_VERIFIED_REPAIR__ = 'V33_VERIFIED_REPAIR';
  const VERSION = 'V33 Verified Repair Upgrade';
  const VIEWS = ['v31-ai','v32-field','v33-command','v33-passenger','v33-staff','v33-map','v33-data'];
  const ROUTES = ['Cebu → Tagbilaran','Cebu → Ormoc','Cebu → Getafe','Cebu → Surigao','Cebu → Dumaguete','Cebu → Siquijor','Cebu → Maasin','Cebu → Palompon'];
  const $ = id => document.getElementById(id);
  const qsa = s => Array.from(document.querySelectorAll(s));
  const now = () => new Date().toLocaleString('en-PH',{timeZone:'Asia/Manila',hour12:true});
  const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const load = (k,f) => { try { const v = JSON.parse(localStorage.getItem(k) || 'null'); return v ?? f; } catch { return f; } };
  const save = (k,v) => localStorage.setItem(k, JSON.stringify(v));
  function tip(msg){ if(typeof toast === 'function') toast(msg); else console.log(msg); }
  function ensureView(name){ let v = $('view-' + name); if(!v){ v = document.createElement('div'); v.id = 'view-' + name; v.className = 'view'; (document.querySelector('.app') || document.body).appendChild(v); } return v; }
  function activate(name){ qsa('.view').forEach(v => v.classList.remove('active')); ensureView(name).classList.add('active'); qsa('#drawerMenu .drawer-item').forEach(el => el.classList.toggle('active', el.dataset.view === name)); }
  function appKeys(){ return Object.keys(localStorage).filter(k => /^oj_|^off_|^ocean|^v\d|^damage/i.test(k)); }
  function damageCases(){ const keys = ['oj_damage_master_log_v11','off_damage_master_log_v11','oj_damage_cases','oj_v30_tickets']; for(const k of keys){ const v = load(k,null); if(Array.isArray(v) && v.length) return v; } return []; }
  function tickets(){ return load('oj_v30_tickets', load('oj_v33_field_records', [])) || []; }
  function records(){ return load('oj_v33_field_records', []); }
  function storage(){ let bytes = 0; appKeys().forEach(k => bytes += (localStorage.getItem(k) || '').length * 2); return { keys: appKeys().length, mb: +(bytes/1024/1024).toFixed(2), pct: Math.min(100, Math.round((bytes/(4.8*1024*1024))*100)) }; }
  function metrics(){ const d = damageCases(), t = tickets(), r = records(), st = storage(); const open = [...t,...r].filter(x => !/closed|resolved|done/i.test(x.status || '')); const risk = Math.min(99, Math.round(open.length*8 + d.length*2 + st.pct*.35)); return {d,t,r,open,st,risk,ready:Math.max(45,100-risk)}; }
  function chip(text, cls){ return '<span class="oj33-chip '+(cls||'')+'">'+esc(text)+'</span>'; }
  function action(icon,title,desc,fn,type){ return '<div class="oj33-card oj33-action" onclick="'+fn+'"><b>'+icon+' '+esc(title)+'</b><small>'+esc(desc)+'</small>'+(type?chip(type,type==='SAFE'?'good':type==='ADMIN'?'hot':'warn'):'')+'</div>'; }
  function kpis(){ const m=metrics(); return '<div class="oj33-grid"><div class="oj33-card"><b>'+m.ready+'%</b><small>Site readiness</small><div class="oj33-meter"><span style="width:'+m.ready+'%"></span></div></div><div class="oj33-card"><b>'+m.open.length+'</b><small>Open service records</small></div><div class="oj33-card"><b>'+m.d.length+'</b><small>Damage evidence cases</small></div><div class="oj33-card"><b>'+m.st.mb+'MB</b><small>Local storage • '+m.st.keys+' keys</small></div></div>'; }
  function routeLabel(route){ return route || 'Selected route'; }
  function download(txt,type,name){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([txt],{type:type})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),500); }
  function offlineAnswer(q){
    const x = String(q || '').toLowerCase();
    const kb = load('oj_v33_ai_kb',{extra:''});
    if(/baggage fee|compute|calculate|kilo|kg|excess|bagahe|kargada/.test(x)) return 'For official baggage fee computation, please open the Baggage Calc tab. I can guide you, but I will not replace the official calculator.';
    if(/damage|damaged|crack|broken|handle|wheel|claim|stub|guba|nabali/.test(x)) return 'Damage report steps: take claim stub/tag photo, full baggage view, and close-up of damage. Then save the claim number and update status in Staff Workbench.';
    if(/lost|missing|nawala|wala/.test(x)) return 'Lost baggage steps: collect PSN or ticket, last name if available, route, baggage tag, item description, and last seen port. Create a field record and export the handover pack.';
    if(/route|schedule|trip|eta|oras|biyahe|asa|where/.test(x)) return 'Open the Live Map or Schedules tab for route guidance. Main Cebu routes include Tagbilaran, Ormoc, Getafe, Surigao, Dumaguete, Siquijor, Maasin, and Palompon.';
    if(/admin|login|supervisor|password/.test(x)) return 'Normal users do not need login. Admin tools remain protected. Demo admin credentials may be admin/admin, demo/demo, or supervisor/supervisor depending on your build.';
    if(/offline|github|page|upload|deploy|site/.test(x)) return 'For GitHub Pages, upload the files inside the ZIP, not the ZIP itself. The homepage must be named index.html, with manifest.webmanifest, sw.js, and icons folder beside it.';
    if(/hello|hi|help|unsa|ano|what/.test(x)) return 'I can help with routes, schedules, baggage guidance, damage claims, lost baggage, GitHub Pages setup, and staff SOP. Ask in English, Tagalog, or Bisaya keywords.';
    return (kb.extra ? kb.extra + ' ' : '') + 'I am the offline OceanJet assistant. I can answer service, route, claim, baggage, staff, and app setup questions. For official calculations, use the official tabs.';
  }
  function renderAI(){ ensureView('v31-ai').innerHTML = '<div class="card oj33-shell"><div class="oj33-head"><div><h2>🤖 Smart Offline AI Assistant</h2><div class="oj33-sub">Low-end Android friendly. No API key, no server, no model download. Works on GitHub Pages and offline.</div></div>'+chip('OFFLINE AI','good')+'</div></div><div class="card"><div class="card-header">Ask anything about the site or service</div><div id="oj33Chat" class="oj33-chat"></div><div class="grid2" style="margin-top:10px"><input id="oj33Ask" class="oj33-input" placeholder="Ask route, damage, claim, schedule, GitHub..." onkeydown="if(event.key===\'Enter\')oj33AskAI()"><button class="primary block" onclick="oj33AskAI()">Ask</button></div><div class="oj33-grid" style="margin-top:10px">'+action('🧳','Damage help','Ask damage claim steps','oj33QuickAI(\'How to report damaged baggage?\')')+action('🗺️','Route help','Ask route guidance','oj33QuickAI(\'What routes are available?\')')+action('📦','GitHub help','Ask upload steps','oj33QuickAI(\'How to upload to GitHub Pages?\')')+action('🧮','Baggage help','Official calculator reminder','oj33QuickAI(\'Can you compute baggage fee?\')')+'</div></div><div class="card"><div class="card-header">Local AI knowledge note</div><textarea id="oj33KbExtra" class="oj33-textarea" placeholder="Optional extra note for offline assistant">'+esc(load('oj_v33_ai_kb',{extra:''}).extra||'')+'</textarea><button class="accent block" onclick="oj33SaveAIKB()">Save AI Note</button></div>'; seedChat(); }
  function seedChat(){ const box=$('oj33Chat'); if(box && !box.dataset.seeded){ box.dataset.seeded='1'; box.innerHTML='<div class="oj33-msg oj33-bot">Hi. I am the offline assistant. Ask about routes, claims, damage reports, schedules, GitHub Pages, or app troubleshooting.</div>'; } }
  window.oj33AskAI = function(){ const input=$('oj33Ask'); if(!input || !input.value.trim()) return; addMsg(input.value,'user'); const ans=offlineAnswer(input.value); input.value=''; setTimeout(()=>addMsg(ans,'bot'),120); };
  window.oj33QuickAI = function(q){ const input=$('oj33Ask'); if(input) input.value=q; window.oj33AskAI(); };
  window.oj33SaveAIKB = function(){ save('oj_v33_ai_kb',{extra:$('oj33KbExtra').value.trim(),updatedAt:now()}); tip('AI note saved.'); };
  function addMsg(txt,who){ const box=$('oj33Chat'); if(!box) return; const d=document.createElement('div'); d.className='oj33-msg '+(who==='user'?'oj33-user':'oj33-bot'); d.textContent=txt; box.appendChild(d); box.scrollTop=box.scrollHeight; }
  function renderField(){ const list=records(); ensureView('v32-field').innerHTML='<div class="card oj33-shell"><div class="oj33-head"><div><h2>🧾 Field Intelligence Intake</h2><div class="oj33-sub">Fast staff/public intake for damaged baggage, lost baggage, passenger help, feedback, and counter incidents.</div></div>'+chip('FIELD','warn')+'</div>'+kpis()+'</div><div class="card"><div class="card-header">Create field record</div><div class="grid2"><select id="oj33RecType" class="oj33-select"><option>Damage Claim</option><option>Lost Baggage</option><option>Passenger Assistance</option><option>Feedback</option><option>Counter Incident</option></select><select id="oj33RecRoute" class="oj33-select">'+ROUTES.map(r=>'<option>'+r+'</option>').join('')+'</select></div><div class="grid2" style="margin-top:8px"><input id="oj33RecTag" class="oj33-input" placeholder="PSN / tag / ticket"><input id="oj33RecName" class="oj33-input" placeholder="Last name optional"></div><textarea id="oj33RecNotes" class="oj33-textarea" placeholder="Short notes" style="margin-top:8px"></textarea><button class="primary block" onclick="oj33CreateRecord()">Create Field Record</button></div><div class="card"><div class="card-header">Recent field records</div><div id="oj33Records">'+recordRows(list)+'</div><button class="accent block" onclick="oj33ExportRecords()">Export Field CSV</button></div>'; }
  function recordRows(list){ return list.length ? list.slice(0,12).map((r,i)=>'<div class="oj33-row"><div><strong>'+esc(r.id)+'</strong><small>'+esc(r.type)+' • '+esc(r.route)+' • '+esc(r.status)+'</small></div><button class="sm primary" onclick="oj33NextRecord('+i+')">Next</button></div>').join('') : '<p class="muted">No field records yet.</p>'; }
  window.oj33CreateRecord = function(){ const r={id:'OJ-FLD-'+Date.now().toString(36).toUpperCase(),createdAt:now(),type:$('oj33RecType').value,route:$('oj33RecRoute').value,tag:$('oj33RecTag').value.trim(),name:$('oj33RecName').value.trim(),notes:$('oj33RecNotes').value.trim(),status:'Submitted'}; const list=records(); list.unshift(r); save('oj_v33_field_records',list); tip('Field record created: '+r.id); renderField(); };
  window.oj33NextRecord = function(i){ const list=records(); const order=['Submitted','Under Review','Need Evidence','Processing','Closed']; if(!list[i])return; const p=order.indexOf(list[i].status); list[i].status=order[(p+1+order.length)%order.length]; save('oj_v33_field_records',list); renderField(); };
  window.oj33ExportRecords = function(){ const list=records(); const header=['id','createdAt','type','route','tag','name','status','notes']; const csv=[header.join(',')].concat(list.map(r=>header.map(h=>'"'+String(r[h]||'').replace(/"/g,'""')+'"').join(','))).join('\n'); download(csv,'text/csv','oceanjet_v33_field_records.csv'); };
  function renderCommand(){ const m=metrics(); ensureView('v33-command').innerHTML='<div class="card oj33-shell"><div class="oj33-head"><div><h2>🧭 V33 Unified Command Hub</h2><div class="oj33-sub">Verified repair build from the last syntax-clean base. Combines offline AI, field intake, passenger kiosk, staff workbench, live map, and data guardian.</div></div>'+chip('VERIFIED','good')+'</div>'+kpis()+'</div><div class="card"><div class="card-header">Smart action launcher</div><input class="oj33-input" id="oj33Search" placeholder="Search: fare, claim, damage, map, backup, AI..." oninput="oj33SearchActions()"><div id="oj33ActionResults" class="oj33-grid" style="margin-top:10px"></div></div><div class="card"><div class="card-header">Role shortcuts</div><div class="oj33-grid">'+action('👤','Passenger Kiosk','Public self-service tools','showView(\'v33-passenger\')','PUBLIC')+action('🎒','Staff Workbench','Queue and shift tools','showView(\'v33-staff\')','STAFF')+action('🤖','Offline AI','Low-end assistant','showView(\'v31-ai\')','AI')+action('🧾','Field Intake','Create local service records','showView(\'v32-field\')','FIELD')+action('🗺️','Live Map Lens','Route pressure preview','showView(\'v33-map\')','MAP')+action('🛡️','Data Guardian','Backup and health checks','showView(\'v33-data\')','SAFE')+'</div></div><div class="card"><div class="card-header">Command brief</div>'+briefRows(m)+'</div>'; window.oj33SearchActions(); }
  function briefRows(m){ const rows=[['Readiness',m.ready+'%',m.ready<70?'Review storage and queues':'Operational'],['Open records',m.open.length,m.open.length>5?'Assign triage staff':'Normal'],['Damage evidence',m.d.length,m.d.length?'Export damage backup at shift end':'No local evidence yet'],['Storage',m.st.mb+' MB',m.st.pct>70?'Backup and cleanup recommended':'Healthy']]; return rows.map(r=>'<div class="oj33-row"><div><strong>'+esc(r[0])+'</strong><small>'+esc(r[2])+'</small></div>'+chip(r[1],r[0]==='Storage'&&m.st.pct>70?'warn':'')+'</div>').join(''); }
  const searchActions=[['fare','Baggage Calculator','Open official calculator','showView(\'calc\')'],['damage','Damage Detector','Evidence capture and log','showView(\'damage\')'],['claim','Claim Automation','Open claim studio','showView(\'v30-claim\')'],['ai','Offline AI','Ask offline assistant','showView(\'v31-ai\')'],['field','Field Intake','Create service record','showView(\'v32-field\')'],['map','Live Map','Open route pressure view','showView(\'v33-map\')'],['backup','Data Guardian','Export backup','showView(\'v33-data\')'],['admin','Admin','Open protected admin','showView(\'admin\')']];
  window.oj33SearchActions = function(){ const q=($('oj33Search')&&$('oj33Search').value||'').toLowerCase(); const list=searchActions.filter(a=>!q||a.join(' ').toLowerCase().includes(q)).slice(0,8); const box=$('oj33ActionResults'); if(box) box.innerHTML = list.map(a=>action('⚡',a[1],a[2],a[3],a[0].toUpperCase())).join('') || '<p class="muted">No action found.</p>'; };
  function renderPassenger(){ ensureView('v33-passenger').innerHTML='<div class="card oj33-shell"><div class="oj33-head"><div><h2>👤 Passenger Kiosk</h2><div class="oj33-sub">No login. Simple choices for passengers at the port.</div></div>'+chip('PUBLIC','good')+'</div></div><div class="card"><div class="card-header">Choose service</div><div class="oj33-grid">'+action('🧮','Check baggage fee','Use official calculator','showView(\'calc\')')+action('🧳','Report damage','Open damage detector','showView(\'damage\')')+action('🔎','Track claim','Open claim automation','showView(\'v30-claim\')')+action('🤖','Ask AI','Open offline assistant','showView(\'v31-ai\')')+action('🗺️','View routes','Open live map lens','showView(\'v33-map\')')+action('🧾','Create record','Open field intake','showView(\'v32-field\')')+'</div></div><div class="card"><div class="card-header">Passenger guide</div><div class="oj33-row"><div><strong>Damaged baggage</strong><small>Ask staff to capture claim stub, full bag, and close-up damage photo. Keep the claim number.</small></div>'+chip('DAMAGE','hot')+'</div><div class="oj33-row"><div><strong>Lost baggage</strong><small>Prepare PSN/ticket, last name, tag number, route, and item description.</small></div>'+chip('LOST','warn')+'</div></div>'; }
  function renderStaff(){ const list=[...records(),...tickets()].slice(0,10); const rows=list.length?list.map((r,i)=>'<div class="oj33-row"><div><strong>'+esc(r.id||r.claimId||'REC-'+(i+1))+'</strong><small>'+esc(r.type||r.issue||'Service record')+' • '+esc(r.status||'Submitted')+'</small></div>'+chip(priorityText(r),priorityText(r)==='HIGH'?'hot':priorityText(r)==='WATCH'?'warn':'good')+'</div>').join(''):'<p class="muted">No local records yet.</p>'; ensureView('v33-staff').innerHTML='<div class="card oj33-shell"><div class="oj33-head"><div><h2>🎒 Staff Workbench</h2><div class="oj33-sub">Fast triage for baggage staff, cashier, and supervisor review.</div></div>'+chip(list.length+' RECORDS',list.length?'warn':'good')+'</div>'+kpis()+'</div><div class="card"><div class="card-header">Priority queue</div>'+rows+'</div><div class="card"><div class="card-header">Staff actions</div><div class="oj33-grid">'+action('🧳','Damage Capture','Open detector','showView(\'damage\')')+action('🧾','Field Intake','Create service record','showView(\'v32-field\')')+action('🤖','SOP AI Help','Open AI assistant','showView(\'v31-ai\')')+action('📦','Export Pack','Download handover pack','oj33ExportPack()','SAFE')+'</div></div>'; }
  function priorityText(r){ const txt=((r.type||'')+' '+(r.issue||'')+' '+(r.notes||'')).toLowerCase(); if(/critical|lost|wet|broken/.test(txt))return'HIGH'; if(/damage|claim|missing/.test(txt))return'WATCH'; return'OK'; }
  function routeData(){ return ROUTES.slice(0,6).map((n,i)=>({n:n,load:48+((i*17+new Date().getMinutes())%45),eta:25+i*12,risk:(i*13+new Date().getHours()*3)%100})); }
  function renderMap(){ const r=routeData(); ensureView('v33-map').innerHTML='<div class="card oj33-shell"><div class="oj33-head"><div><h2>🗺️ V33 Live Map Intelligence Lens</h2><div class="oj33-sub">Static-site friendly route pressure simulation for GitHub Pages. Gives realistic operations view without GPS feeds.</div></div>'+chip(navigator.onLine?'ONLINE':'OFFLINE',navigator.onLine?'good':'warn')+'</div></div><div class="card"><div class="oj33-map"><div class="oj33-wave"></div><div class="oj33-port" style="left:8%;top:18%">CEBU</div><div class="oj33-port" style="right:8%;top:24%">ORMOC</div><div class="oj33-port" style="right:14%;bottom:20%">TAG</div><div class="oj33-route" style="left:16%;top:32%;width:70%;transform:rotate(8deg)"></div><div class="oj33-route" style="left:20%;top:58%;width:62%;transform:rotate(-15deg)"></div><div class="oj33-ship" style="left:'+(28+(new Date().getSeconds()%35))+'%;top:34%">⛴️</div><div class="oj33-ship" style="left:'+(46+(new Date().getSeconds()%22))+'%;top:62%;animation-delay:1s">🚢</div></div></div><div class="card"><div class="card-header">Route pressure board</div>'+r.map(x=>'<div class="oj33-row"><div><strong>'+esc(x.n)+'</strong><small>ETA '+x.eta+' min • Load '+x.load+'% • Risk '+x.risk+'%</small><div class="oj33-meter"><span style="width:'+x.load+'%"></span></div></div>'+chip(x.risk>68?'High':x.risk>38?'Watch':'Good',x.risk>68?'hot':x.risk>38?'warn':'good')+'</div>').join('')+'</div>'; }
  function renderData(){ const m=metrics(); ensureView('v33-data').innerHTML='<div class="card oj33-shell"><div class="oj33-head"><div><h2>🛡️ V33 Data Guardian</h2><div class="oj33-sub">Health check, storage audit, duplicate signal, and shift handover backup.</div></div>'+chip('LOCAL-FIRST','good')+'</div>'+kpis()+'</div><div class="card"><div class="card-header">Health checks</div><div class="oj33-row"><div><strong>Storage pressure</strong><small>'+m.st.mb+' MB across '+m.st.keys+' app keys</small></div>'+chip(m.st.pct>70?'HIGH':'OK',m.st.pct>70?'warn':'good')+'</div><div class="oj33-row"><div><strong>Duplicate signal</strong><small>'+dupCount()+' possible duplicate claim/tag values</small></div>'+chip(dupCount()?dupCount()+' FOUND':'CLEAR',dupCount()?'warn':'good')+'</div><div class="oj33-row"><div><strong>Recovery</strong><small>Blank-screen guard and self-healing systems remain active.</small></div>'+chip('ACTIVE','good')+'</div></div><div class="card"><div class="card-header">Guardian actions</div><div class="oj33-grid">'+action('📦','Export Snapshot','All important local data','oj33ExportPack()','SAFE')+action('🧹','Compact Logs','Keep latest local audit records','oj33CompactLogs()','SAFE')+action('🔁','Refresh Drawer','Rebuild left navigation','oj33RefreshDrawer()','SAFE')+action('🧪','Run Health Test','Download diagnostics JSON','oj33HealthTest()','SAFE')+'</div></div>'; }
  function dupCount(){ const seen=new Set(); let d=0; [...records(),...tickets(),...damageCases()].forEach(x=>{ const id=x.id||x.claimId||x.tagNo||x.caseId; if(id){ if(seen.has(id))d++; seen.add(id); } }); return d; }
  window.oj33ExportPack = function(){ const pack={version:VERSION,exportedAt:now(),metrics:metrics(),fieldRecords:records(),tickets:tickets(),damage:damageCases(),storageKeys:appKeys(),notes:'V33 verified handover pack.'}; download(JSON.stringify(pack,null,2),'application/json','oceanjet_v33_verified_snapshot.json'); tip('V33 snapshot exported.'); };
  window.oj33CompactLogs = function(){ ['oj_v30_audit','oj_v29_audit','oj_v25_logs','oj_v23_logs'].forEach(k=>{ const v=load(k,null); if(Array.isArray(v)) save(k,v.slice(0,80)); }); tip('Logs compacted.'); };
  window.oj33RefreshDrawer = function(){ if(typeof buildDrawerMenu === 'function') buildDrawerMenu(); patchDrawer(); tip('Navigation refreshed.'); };
  window.oj33HealthTest = function(){ download(JSON.stringify({version:VERSION,at:now(),views:VIEWS.map(v=>({view:v,exists:!!$('view-'+v)})),metrics:metrics(),online:navigator.onLine,userAgent:navigator.userAgent},null,2),'application/json','oceanjet_v33_verified_health_test.json'); };
  const renderers={'v31-ai':renderAI,'v32-field':renderField,'v33-command':renderCommand,'v33-passenger':renderPassenger,'v33-staff':renderStaff,'v33-map':renderMap,'v33-data':renderData};
  function renderLocal(name){ activate(name); (renderers[name] || renderCommand)(); }
  function patchDrawer(){ const menu=$('drawerMenu'); if(!menu) return; const items=[['v33-command','🧭','V33 Command'],['v31-ai','🤖','Offline AI'],['v32-field','🧾','Field Intake'],['v33-passenger','👤','Passenger Kiosk'],['v33-staff','🎒','Staff Workbench'],['v33-map','🗺️','V33 Live Map'],['v33-data','🛡️','Data Guardian']]; items.forEach(item=>{ if(!menu.querySelector('[data-view="'+item[0]+'"]')) menu.insertAdjacentHTML('beforeend','<div class="drawer-item" data-view="'+item[0]+'" onclick="showView(\''+item[0]+'\')"><i>'+item[1]+'</i> '+item[2]+'</div>'); }); }
  function patchNav(){ if(window.__ojV33VerifiedNav) return; window.__ojV33VerifiedNav=true; const oldShow=window.showView; window.showView=function(name){ if(VIEWS.includes(name)){ renderLocal(name); return; } const r=oldShow?oldShow.apply(this,arguments):undefined; setTimeout(()=>{patchDrawer();patchDashboard();},120); return r; }; try{ showView=window.showView; }catch(e){} const oldBuild=window.buildDrawerMenu; window.buildDrawerMenu=function(){ const r=oldBuild?oldBuild.apply(this,arguments):undefined; patchDrawer(); return r; }; try{ buildDrawerMenu=window.buildDrawerMenu; }catch(e){} }
  function patchDashboard(){ const v=$('view-dashboard'); if(!v || $('oj33DashPanel')) return; const m=metrics(); v.insertAdjacentHTML('afterbegin','<div id="oj33DashPanel" class="card oj33-shell"><div class="oj33-head"><div><h2>🧭 V33 Verified Command Ready</h2><div class="oj33-sub">'+m.ready+'% readiness • '+m.open.length+' open records • '+m.d.length+' damage evidence cases</div></div><button class="sm primary" onclick="showView(\'v33-command\')">Open V33</button></div></div>'); }
  function installFab(){ if($('oj33Fab')) return; const b=document.createElement('button'); b.id='oj33Fab'; b.className='oj33-fab'; b.textContent='🧭 V33'; b.onclick=()=>showView('v33-command'); document.body.appendChild(b); }
  function boot(){ try{ VIEWS.forEach(ensureView); patchNav(); if(typeof buildDrawerMenu === 'function') buildDrawerMenu(); patchDrawer(); patchDashboard(); installFab(); console.log(VERSION+' loaded'); } catch(e){ console.error('V33 verified boot error',e); tip('V33 recovery: '+e.message); } }
  if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
})();
