
(function(){
  'use strict';
  const V7_VERSION='v7-innovation-pack-source-based';
  const V7_ROUTES=['cebu_tagbilaran','cebu_maasin','cebu_surigao','cebu_siquijor','cebu_dumaguete','cebu_ormoc','cebu_palompon','cebu_getafe'];
  const V7_CLASS=['TC/OA','BC','SC/PWD (BC)','SC/PWD (TC/OA)','ST','MI'];
  const V7_ALIAS={cebu_tagbilaran:['tagbilaran','tagbi','tagb','bohol'],cebu_maasin:['maasin','massin','southern leyte'],cebu_surigao:['surigao'],cebu_siquijor:['siquijor'],cebu_dumaguete:['dumaguete','duma'],cebu_ormoc:['ormoc'],cebu_palompon:['palompon','kalanggaman'],cebu_getafe:['getafe']};
  const V7_PLAN={
    cebu_tagbilaran:{title:'Cebu to Tagbilaran',type:'Direct',legs:['cebu_tagbilaran'],gate:'A1',travel:'2h',risk:18,eta:'On time'},
    cebu_maasin:{title:'Cebu to Maasin',type:'Direct',legs:['cebu_maasin'],gate:'C1',travel:'3h',risk:24,eta:'On time'},
    cebu_surigao:{title:'Cebu to Surigao',type:'Connect via Maasin',legs:['cebu_maasin','maasin_surigao'],gate:'C2',travel:'5h 30m',risk:42,eta:'Watch transfer'},
    cebu_siquijor:{title:'Cebu to Siquijor',type:'Connect via Tagbilaran',legs:['cebu_tagbilaran','tagbilaran_siquijor'],gate:'A2',travel:'4h 20m',risk:36,eta:'Watch transfer'},
    cebu_dumaguete:{title:'Cebu to Dumaguete',type:'Connect via Tagbilaran',legs:['cebu_tagbilaran','tagbilaran_dumaguete'],gate:'A3',travel:'4h 20m',risk:38,eta:'Watch transfer'},
    cebu_ormoc:{title:'Cebu to Ormoc',type:'Direct',legs:['cebu_ormoc'],gate:'B1',travel:'3h',risk:22,eta:'On time'},
    cebu_palompon:{title:'Cebu to Palompon',type:'Direct',legs:['cebu_palompon'],gate:'B2',travel:'3h',risk:26,eta:'On time'},
    cebu_getafe:{title:'Cebu to Getafe',type:'Direct',legs:['cebu_getafe'],gate:'D1',travel:'1h',risk:14,eta:'Fast lane'}
  };
  const V7_DIRECT={
    cebu_tagbilaran:{'TC/OA':1000,'BC':1560,'SC/PWD (BC)':1274.29,'SC/PWD (TC/OA)':714.29,'ST':800,'MI':500},
    tagbilaran_siquijor:{'TC/OA':1000,'BC':1560,'SC/PWD (BC)':1274.29,'SC/PWD (TC/OA)':714.29,'ST':800,'MI':500},
    tagbilaran_dumaguete:{'TC/OA':1170,'BC':1820,'SC/PWD (BC)':1485.71,'SC/PWD (TC/OA)':835.71,'ST':936,'MI':585},
    cebu_getafe:{'TC/OA':585,'BC':1040,'SC/PWD (BC)':872.86,'SC/PWD (TC/OA)':417.86,'ST':468,'MI':292.50},
    cebu_ormoc:{'TC/OA':1430,'BC':1950,'SC/PWD (BC)':1541.43,'SC/PWD (TC/OA)':1021.43,'ST':1144,'MI':715},
    cebu_palompon:{'TC/OA':1430,'BC':1950,'SC/PWD (BC)':1541.43,'SC/PWD (TC/OA)':1021.43,'ST':1144,'MI':715},
    cebu_maasin:{'TC/OA':1430,'BC':1950,'SC/PWD (BC)':1541.43,'SC/PWD (TC/OA)':1021.43,'ST':1144,'MI':715},
    maasin_surigao:{'TC/OA':1040,'BC':1560,'SC/PWD (BC)':1262.86,'SC/PWD (TC/OA)':742.86,'ST':832,'MI':520}
  };
  const $v=id=>document.getElementById(id);
  const peso=n=>(typeof fmtPHP==='function'?fmtPHP(Number(n)||0):'₱'+(Number(n)||0).toFixed(2));
  const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9.\s]/g,' ').replace(/\s+/g,' ').trim();
  const label=r=>V7_PLAN[r]?.title || (DB?.schedules?.[r]?.title) || String(r).replace(/_/g,' to ').replace(/\b\w/g,m=>m.toUpperCase());
  const optRoutes=sel=>V7_ROUTES.map(r=>`<option value="${r}" ${r===sel?'selected':''}>${label(r)}</option>`).join('');
  const optClass=sel=>V7_CLASS.map(c=>`<option value="${c}" ${c===sel?'selected':''}>${c}</option>`).join('');
  function note(m){ if(typeof toast==='function') toast(m); }
  function audit7(action){try{DB.audit=DB.audit||[];DB.audit.unshift({time:new Date().toLocaleString(),action:'V7 '+action,user:currentRole||'system'});DB.audit=DB.audit.slice(0,300);saveDB();}catch(e){}}
  function findRoute7(text){const q=norm(text);if(q.includes('liloan'))return'liloan';for(const r of V7_ROUTES){if(q.includes(r.replace(/_/g,' '))||q.includes(label(r).toLowerCase()))return r;const dest=r.replace('cebu_','');if(q.includes(dest))return r;for(const a of V7_ALIAS[r]||[])if(q.includes(norm(a)))return r;}return null;}
  function class7(text){const q=norm(text);if(q.includes('business')||/\bbc\b/.test(q))return'BC';if(q.includes('student')||/\bst\b/.test(q))return'ST';if(q.includes('minor')||q.includes('military')||/\bmi\b/.test(q))return'MI';if(q.includes('pwd')||q.includes('senior')||/\bsc\b/.test(q))return(q.includes('business')||/\bbc\b/.test(q))?'SC/PWD (BC)':'SC/PWD (TC/OA)';return'TC/OA';}
  function fare7(route,cls){const plan=V7_PLAN[route];if(!plan)return{total:0,legs:[]};const legs=plan.legs.map(k=>{const fromDB=DB?.paxFares?.[k]?.[cls];const direct=V7_DIRECT[k]?.[cls];const fallback=DB?.paxFares?.[k]?.['TC/OA'] ?? V7_DIRECT[k]?.['TC/OA'] ?? 0;return{key:k,label:label(k),fare:Number(fromDB??direct??fallback??0)};});return{total:Number(legs.reduce((a,b)=>a+b.fare,0).toFixed(2)),legs};}
  function baggage7(route,mode,cls,pax,weight,rounding){const free=mode==='normal'?(DB.freeAllowance[cls]||0):0;const freeTotal=free*pax;const excess=Math.max(0,weight-freeTotal);let E=mode==='normal'?excess/pax:weight;if(rounding==='ceil')E=Math.ceil(E);if(rounding==='floor')E=Math.floor(E);const slab=slabCost(E,DB.slabs[route][mode]);const total=mode==='normal'?slab.total*pax:slab.total;return{free,freeTotal,excess,E,slab,total};}
  function loadScore(route){const base=(DB.schedules?.[route]?.trips?.length||1)*18+(DB.stats?.routeCounts?.[route]||0)*12+(V7_PLAN[route].legs.length>1?16:0);const wk=[0,6].includes(new Date().getDay())?18:0;return Math.min(99,Math.round(base+wk+V7_PLAN[route].risk/3));}
  function riskColor(score){return score>70?'var(--bad)':score>45?'var(--warn)':'var(--ok)';}
  function syncV7(){try{DB.routeInnovation=DB.routeInnovation||{};DB.v7Version=V7_VERSION;delete DB.slabs.cebu_liloan;delete DB.paxFares.cebu_liloan;delete DB.schedules.cebu_liloan;V7_ROUTES.forEach(r=>{if(!DB.paxFares[r]){const o={};V7_CLASS.forEach(c=>o[c]=fare7(r,c).total);DB.paxFares[r]=o;}});saveDB();}catch(e){console.warn('V7 sync skipped',e);}}

  function ensureInnovationView(){
    if(!$v('view-innovation')){const section=document.createElement('div');section.id='view-innovation';section.className='view';const anchor=$v('view-map')||document.querySelector('.view:last-of-type');if(anchor&&anchor.parentNode)anchor.parentNode.insertBefore(section,anchor.nextSibling);else document.querySelector('.app')?.appendChild(section);}
  }
  function patchMenus(){
    if(typeof buildDrawerMenu==='function'&&!window.__v7DrawerPatched){const old=buildDrawerMenu;window.buildDrawerMenu=buildDrawerMenu=function(){old();const menu=$v('drawerMenu');if(menu&&!menu.querySelector('[data-view="innovation"]'))menu.insertAdjacentHTML('beforeend',`<div class="drawer-item" data-view="innovation" onclick="navigate('innovation')"><i>🚀</i> Innovation Packs</div>`);};window.__v7DrawerPatched=true;}
    if(typeof showView==='function'&&!window.__v7ShowPatched){const oldShow=showView;window.showView=showView=function(name){ensureInnovationView();if(name==='innovation'){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$v('view-innovation').classList.add('active');document.querySelectorAll('.drawer-item').forEach(el=>el.classList.toggle('active',el.dataset.view==='innovation'));renderInnovation();return;}return oldShow(name);};window.__v7ShowPatched=true;}
  }

  window.renderInnovation=function(){
    const best=V7_ROUTES.map(r=>({r,s:loadScore(r)})).sort((a,b)=>b.s-a)[0];
    $v('view-innovation').innerHTML=`
      <div class="card v7-card"><div class="card-header"><span>🚀 Innovation Packs V7</span><span class="v7-badge"><span class="v7-pulse-dot"></span> Source-based</span></div>
        <div class="v7-grid3">
          <div class="v7-tile"><b>Calculator Core</b><small>Preserved, not rewritten</small></div>
          <div class="v7-tile"><b>${best?label(best.r).split(' to ')[1]:'--'}</b><small>Predicted busiest route</small></div>
          <div class="v7-tile"><b>${DB.history?.length||0}</b><small>Transactions stored</small></div>
        </div>
      </div>
      <div class="card"><div class="card-header">🧠 Smart Trip Optimizer</div>
        <div class="v7-grid">
          <div class="input-group"><label>Route</label><select id="v7Route" onchange="v7Plan()">${optRoutes('cebu_tagbilaran')}</select></div>
          <div class="input-group"><label>Passenger Class</label><select id="v7Class" onchange="v7Plan()">${optClass('TC/OA')}</select></div>
          <div class="input-group"><label>Passengers</label><input id="v7Pax" type="number" min="1" value="1" oninput="v7Plan()"></div>
          <div class="input-group"><label>Total Weight kg</label><input id="v7Weight" type="number" min="0" step="0.1" value="0" oninput="v7Plan()"></div>
          <div class="input-group"><label>Baggage Mode</label><select id="v7Mode" onchange="v7Plan()"><option value="normal">Normal</option><option value="fragile">Fragile</option></select></div>
          <div class="input-group"><label>Rounding</label><select id="v7Round" onchange="v7Plan()"><option value="exact">Exact</option><option value="ceil">Ceiling</option><option value="floor">Floor</option></select></div>
        </div>
        <div class="grid2"><button class="primary block" onclick="v7Plan(true)">Generate Smart Quote</button><button class="accent block" onclick="v7ApplyToCalculator()">Send to Calculator</button></div>
        <div id="v7PlanOut"></div>
      </div>
      <div class="card v7-card"><div class="card-header">🛰 Route Orbit Map</div>${orbitHtml()}</div>
      <div class="card"><div class="card-header">⚓ Port Pulse + Risk Forecast</div><div id="v7PulseGrid" class="v7-grid"></div></div>
      <div class="card"><div class="card-header">🎫 Boarding Pass Generator</div><div class="v7-grid"><div class="input-group"><label>Passenger Name</label><input id="v7PassName" placeholder="Enter passenger name"></div><div class="input-group"><label>Route</label><select id="v7PassRoute">${optRoutes('cebu_tagbilaran')}</select></div></div><button class="primary block" onclick="v7GeneratePass()">Generate Smart Boarding Pass</button><div id="v7PassOut" style="margin-top:10px"></div></div>
      <div class="card"><div class="card-header">🛡 AI Anomaly Detector</div><div id="v7Anomaly"></div></div>
      <div class="card"><div class="card-header">📡 Live Innovation Console</div><div class="v7-console" id="v7Console"></div></div>
    `;
    v7Plan();renderPulse();renderAnomalies();renderConsole();
  };
  function orbitHtml(){const pts={cebu:[50,50],cebu_tagbilaran:[23,32],cebu_maasin:[30,72],cebu_surigao:[74,75],cebu_siquijor:[69,58],cebu_dumaguete:[76,41],cebu_ormoc:[66,24],cebu_palompon:[38,20],cebu_getafe:[18,55]};const ports=V7_ROUTES.map(r=>`<div class="v7-port" style="left:${pts[r][0]}%;top:${pts[r][1]}%">${label(r).split(' to ')[1]}</div>`).join('');return`<div class="v7-orbit"><div class="v7-port cebu">CEBU HUB</div>${ports}</div>`;}
  window.v7Plan=function(saveQuote){try{const route=$v('v7Route')?.value||'cebu_tagbilaran';const cls=$v('v7Class')?.value||'TC/OA';const pax=Math.max(1,parseInt($v('v7Pax')?.value||'1',10));const weight=Math.max(0,Number($v('v7Weight')?.value||0));const mode=$v('v7Mode')?.value||'normal';const rounding=$v('v7Round')?.value||'exact';const f=fare7(route,cls);const bag=baggage7(route,mode,cls==='BC'?'business':'tourist',pax,weight,rounding);const passenger=f.total*pax;const total=passenger+bag.total;const load=loadScore(route);const plan=V7_PLAN[route];const out=`<div class="v7-plan"><div class="quote-line"><span>Route</span><strong>${label(route)}</strong></div><div class="quote-line"><span>Route Type</span><strong>${plan.type}</strong></div><div class="quote-line"><span>Gate / Zone</span><strong>${plan.gate} • ${plan.travel}</strong></div>${f.legs.map(l=>`<div class="quote-line"><span>${l.label}</span><strong>${peso(l.fare)} × ${pax}</strong></div>`).join('')}<hr style="border-color:var(--border);margin:8px 0"><div class="quote-line"><span>Passenger Total</span><strong>${peso(passenger)}</strong></div><div class="quote-line"><span>Baggage Total</span><strong>${peso(bag.total)}</strong></div><div class="quote-line"><span>Free Allowance</span><strong>${bag.freeTotal.toFixed(1)}kg</strong></div><div class="quote-line"><span>Chargeable</span><strong>${bag.E.toFixed(2)}kg</strong></div><div class="v7-total">Grand Total: ${peso(total)}</div><div class="v7-meter"><span style="width:${load}%;background:${riskColor(load)}"></span></div><small style="color:var(--text3)">Load prediction: ${load}% • ${plan.eta}</small><div class="grid2" style="margin-top:8px"><button class="sm primary" onclick="v7CopyQuote()">Copy Quote</button><button class="sm accent" onclick="v7GeneratePassFromPlan()">Create Boarding Pass</button></div></div>`;$v('v7PlanOut').innerHTML=out;window.__v7Quote=`${label(route)}\nClass: ${cls}\nPax: ${pax}\nPassenger: ${peso(passenger)}\nBaggage: ${peso(bag.total)}\nGrand Total: ${peso(total)}\nGate: ${plan.gate}\nTravel: ${plan.travel}`;window.__v7Plan={route,cls,pax,weight,mode,rounding,total,passenger,baggage:bag.total};if(saveQuote){audit7('smart quote generated for '+label(route));note('Smart quote generated.');}}catch(e){console.error(e);if($v('v7PlanOut'))$v('v7PlanOut').innerHTML='<div class="v7-plan warn">Cannot generate quote. Check route/slab data.</div>';}};
  window.v7CopyQuote=function(){const txt=window.__v7Quote||'No quote yet.';if(navigator.clipboard)navigator.clipboard.writeText(txt).then(()=>note('Smart quote copied.')).catch(()=>note(txt));else note(txt);};
  window.v7ApplyToCalculator=function(){const p=window.__v7Plan||{};showView('calculator');setTimeout(()=>{if($v('calcRoute'))$v('calcRoute').value=p.route||'cebu_tagbilaran';if($v('calcMode'))$v('calcMode').value=p.mode||'normal';if($v('pax'))$v('pax').value=p.pax||1;if($v('weight'))$v('weight').value=p.weight||0;if($v('rounding'))$v('rounding').value=p.rounding||'exact';if(typeof compute==='function')compute();note('V7 quote sent to preserved calculator.');},80);};
  function renderPulse(){const box=$v('v7PulseGrid');if(!box)return;box.innerHTML=V7_ROUTES.map(r=>{const s=loadScore(r);return`<div class="v7-tile"><b>${label(r).split(' to ')[1]}</b><small>${V7_PLAN[r].gate} • ${V7_PLAN[r].travel}</small><div class="v7-meter"><span style="width:${s}%;background:${riskColor(s)}"></span></div><small>Load ${s}% • Risk ${V7_PLAN[r].risk}%</small></div>`}).join('');}
  function renderAnomalies(){const list=(DB.history||[]).slice(0,80);const issues=[];list.forEach((h,i)=>{if(Number(h.weight)>80)issues.push(`Heavy baggage: ${label(h.route)} ${h.weight}kg`);if(Number(h.total)<=0&&Number(h.weight)>0)issues.push(`Possible zero-fee issue: ${label(h.route)} ${h.weight}kg`);if(i>0&&h.route===list[i-1].route&&h.weight===list[i-1].weight&&Math.abs(new Date(h.time)-new Date(list[i-1].time))<60000)issues.push(`Possible duplicate transaction: ${label(h.route)} ${h.weight}kg`);});$v('v7Anomaly').innerHTML=issues.length?issues.slice(0,8).map(x=>`<div class="v7-plan warn">⚠️ ${x}</div>`).join(''):'<div class="v7-plan ok">✅ No major anomalies detected in recent transactions.</div>';}
  function renderConsole(){const box=$v('v7Console');if(!box)return;const now=new Date().toLocaleTimeString();const rows=[`[${now}] V7 innovation pack online`,`[${now}] Calculator core status: preserved`,`[${now}] Main Cebu route filter: active`,`[${now}] Liloan route: removed/not included`,`[${now}] AI multilingual hints: English/Tagalog/Bisaya keywords loaded`,`[${now}] Risk engine watching ${V7_ROUTES.length} routes`];box.innerHTML=rows.map(r=>`<div>${r}</div>`).join('');}
  window.v7GeneratePass=function(){const name=($v('v7PassName')?.value||'Passenger').trim();const route=$v('v7PassRoute')?.value||'cebu_tagbilaran';renderPass(name,route,$v('v7PassOut'));};
  window.v7GeneratePassFromPlan=function(){const p=window.__v7Plan||{};renderPass('Passenger',p.route||'cebu_tagbilaran',$v('v7PlanOut'));};
  function renderPass(name,route,target){const plan=V7_PLAN[route];const code='OFF-'+Date.now().toString().slice(-7);const group=plan.legs.length>1?'CONNECT':'DIRECT';const html=`<div class="v7-pass"><h3>⛴ OCEAN FAST FERRIES</h3><div class="v7-pass-grid"><div><div class="v7-pass-row"><span>Name</span><b>${name}</b></div><div class="v7-pass-row"><span>Route</span><b>${label(route)}</b></div><div class="v7-pass-row"><span>Gate</span><b>${plan.gate}</b></div><div class="v7-pass-row"><span>Group</span><b>${group}</b></div><div class="v7-pass-row"><span>Travel</span><b>${plan.travel}</b></div><div class="v7-pass-row"><span>Code</span><b>${code}</b></div><span class="v7-status">AI Verified • ${plan.eta}</span></div><div class="v7-qr" title="${code}"></div></div><button class="sm primary" style="margin-top:10px" onclick="window.print()">Print Pass</button></div>`;if(target)target.insertAdjacentHTML('beforeend',html);audit7('boarding pass generated '+code+' for '+label(route));}

  function patchComputeV7(){if(typeof compute==='function'&&!window.__v7ComputePatched){const old=compute;window.compute=compute=function(override=null){const res=old(override);setTimeout(()=>{try{const route=$v('calcRoute')?.value;if(!route||!V7_ROUTES.includes(route))return;const box=$v('resultCard');if(box&&!$v('v7AfterCompute')){const score=loadScore(route);box.insertAdjacentHTML('beforeend',`<div id="v7AfterCompute" class="v7-plan"><strong>V7 AI Ops Add-on</strong><br>Gate: ${V7_PLAN[route].gate} • Load prediction: ${score}% • Status: ${V7_PLAN[route].eta}<div class="v7-meter"><span style="width:${score}%;background:${riskColor(score)}"></span></div><button class="sm accent" onclick="showView('innovation')">Open Innovation Pack</button></div>`);}}catch(e){}},50);return res;};window.__v7ComputePatched=true;}}
  function patchAI7(){if(typeof aiOfflineRespond==='function'&&!window.__v7AIPatched){const base=aiOfflineRespond;window.aiOfflineRespond=aiOfflineRespond=function(q){const s=norm(q);if(/pila|tagpila|pamasahe|plite|plete|magkano/.test(s)&&!/kg|kilo|bagahe|baggage/.test(s)){const r=findRoute7(s);if(r&&r!=='liloan'){const cls=class7(s);const f=fare7(r,cls);return`${label(r)} fare (${cls}): ${peso(f.total)}\n${f.legs.map(l=>'• '+l.label+': '+peso(l.fare)).join('\n')}`;}}
      if(/bagahe|bagahi|kargada|maleta|luggage|baggage/.test(s)){const kg=(s.match(/(\d+(?:\.\d+)?)\s*(kg|kilo|kilos)/)||[])[1];if(kg){const r=findRoute7(s)||'cebu_tagbilaran';const pax=Number((s.match(/(\d+)\s*(pax|passenger|pasahero|passengers)/)||[])[1]||1);const mode=/fragile|cargo|kargada/.test(s)?'fragile':'normal';const b=baggage7(r,mode,/business|bc/.test(s)?'business':'tourist',pax,Number(kg),'exact');return`Baggage estimate for ${label(r)}:\n${pax} pax • ${kg}kg • ${mode}\nFree: ${b.freeTotal}kg\nChargeable: ${b.E.toFixed(2)}kg\nBaggage fee: ${peso(b.total)}`;}}
      if(/innovation|future|futuristic|ai ops|boarding pass|risk|forecast|optimizer/.test(s))return'V7 Innovation Packs include Smart Trip Optimizer, Boarding Pass Generator, Route Orbit Map, Port Pulse risk forecast, AI anomaly detector, multilingual AI, and quick command dock. Open the Innovation Packs tab.';
      if(/gate|boarding|sakay|terminal/.test(s)){const r=findRoute7(s);if(r&&r!=='liloan')return`${label(r)} uses gate ${V7_PLAN[r].gate}. Type: ${V7_PLAN[r].type}. Travel: ${V7_PLAN[r].travel}. Status: ${V7_PLAN[r].eta}.`;}
      if(/liloan/.test(s))return'Cebu to Liloan is removed/not included. Main routes only: Tagbilaran, Maasin, Surigao, Siquijor, Dumaguete, Ormoc, Palompon, and Getafe.';
      return base(q);};window.__v7AIPatched=true;}}
  function addDock(){if($v('v7CommandBtn'))return;const b=document.createElement('button');b.id='v7CommandBtn';b.className='v7-command-btn';b.textContent='🚀';b.onclick=()=>{$v('v7MiniDock')?.classList.toggle('open')};document.body.appendChild(b);const d=document.createElement('div');d.id='v7MiniDock';d.className='v7-mini-dock';d.innerHTML=`<button onclick="showView('innovation')">🚀 Innovation Packs</button><button onclick="showView('calculator')">🧮 Preserved Calculator</button><button onclick="openV7Ask()">🤖 Ask AI</button><button onclick="v7QuickPass()">🎫 Quick Pass</button>`;document.body.appendChild(d);}
  window.openV7Ask=function(){const old=$v('v7AskModal');if(old){old.remove();return;}const m=document.createElement('div');m.className='v7-modal';m.id='v7AskModal';m.innerHTML=`<div class="v7-modal-box"><div class="card-header"><span>🤖 V7 AI Quick Ask</span><button class="sm" onclick="document.getElementById('v7AskModal').remove()">✕</button></div><input id="v7AskInput" placeholder="Try: pila Cebu to Siquijor, 2 pax 45kg Ormoc, gate Surigao..." onkeydown="if(event.key==='Enter')v7AskRun()"><div id="v7AskOut" class="v7-plan">English, Tagalog, and Bisaya-like words are supported offline.</div></div>`;document.body.appendChild(m);setTimeout(()=>$v('v7AskInput')?.focus(),50);};
  window.v7AskRun=function(){const q=$v('v7AskInput')?.value||'';$v('v7AskOut').textContent=aiOfflineRespond(q);};
  window.v7QuickPass=function(){showView('innovation');setTimeout(()=>{const out=$v('v7PassOut');if(out)renderPass('Passenger','cebu_tagbilaran',out);},120);};
  function patchDashboard7(){if(typeof buildDashboard==='function'&&!window.__v7DashPatched){const old=buildDashboard;window.buildDashboard=buildDashboard=function(){old();const v=$v('view-dashboard');if(v&&!$v('v7DashPack')){const top=V7_ROUTES.map(r=>({r,s:loadScore(r)})).sort((a,b)=>b.s-a.s).slice(0,3);v.insertAdjacentHTML('beforeend',`<div id="v7DashPack" class="card v7-card"><div class="card-header"><span>🚀 V7 Innovation Snapshot</span><span class="v7-badge">New Pack</span></div><div class="v7-grid3">${top.map(x=>`<div class="v7-tile"><b>${label(x.r).split(' to ')[1]}</b><small>Predicted load ${x.s}%</small><div class="v7-meter"><span style="width:${x.s}%;background:${riskColor(x.s)}"></span></div></div>`).join('')}</div><button class="primary block" style="margin-top:10px" onclick="showView('innovation')">Open Innovation Packs</button></div>`);}};window.__v7DashPatched=true;}}
  function bootV7(){try{ensureInnovationView();syncV7();patchMenus();patchComputeV7();patchAI7();patchDashboard7();addDock();if(typeof buildDrawerMenu==='function')buildDrawerMenu();if($v('view-dashboard')?.classList.contains('active')&&currentRole)showView('dashboard');window.__OFF_PATCH_VERSION=V7_VERSION;audit7('innovation pack loaded');}catch(e){console.error('V7 innovation patch error',e);}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootV7);else bootV7();
})();
