
(function(){
  'use strict';
  if(window.__OJ_V28_SERVICE_INTELLIGENCE_OS__) return;
  window.__OJ_V28_SERVICE_INTELLIGENCE_OS__ = true;
  const VERSION='V28 Service Intelligence OS';
  const CLAIM_KEY='oj_v22_claims';
  const DAMAGE_KEY='oj_damage_master_log_v11';
  const HEALTH_KEY='oj_v22_health';
  const NOTICE_KEY='oj_v28_public_notices';
  const OUTBOX_KEY='oj_v28_outbox';
  const SETTINGS_KEY='oj_v28_settings';
  const LOG_KEY='oj_v28_audit';
  const VIEWS=['v28-os'];
  const DESTS=['TAGBILARAN','ORMOC','DUMAGUETE','SIQUIJOR','SURIGAO','MAASIN','PALOMPON','GETAFE'];
  const $=id=>document.getElementById(id);
  const qsa=s=>Array.from(document.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const now=()=>new Date().toLocaleString('en-PH',{timeZone:'Asia/Manila',hour12:true});
  const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(e){return f}};
  const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){audit('save_error',k+': '+e.message);return false}};
  const claims=()=>load(CLAIM_KEY,[]);
  const damage=()=>{const v=load(DAMAGE_KEY,[]); return Array.isArray(v)?v:(Array.isArray(v.cases)?v.cases:[])};
  const notices=()=>load(NOTICE_KEY,[]);
  const outbox=()=>load(OUTBOX_KEY,[]);
  const settings=()=>Object.assign({fast:true,bigButtons:false,lastAudit:'Never'},load(SETTINGS_KEY,{}));
  function toast(msg){if(typeof window.toast==='function') return window.toast(msg); if(typeof window.fallbackToast==='function') return window.fallbackToast(msg); const d=document.createElement('div');d.textContent=msg;d.style.cssText='position:fixed;left:50%;top:16px;transform:translateX(-50%);z-index:99999;background:#0b1028;color:#49f7ff;border:1px solid rgba(73,247,255,.45);padding:10px 14px;border-radius:999px;font-weight:800;box-shadow:0 10px 30px rgba(0,0,0,.35)';document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
  function audit(type,msg){const a=load(LOG_KEY,[]);a.unshift({time:now(),type,msg:String(msg||'')});save(LOG_KEY,a.slice(0,120));}
  function ensureView(name){let v=$('view-'+name); if(!v){v=document.createElement('div');v.id='view-'+name;v.className='view';(document.querySelector('.app')||document.body).appendChild(v);} return v;}
  function showLocal(name){VIEWS.forEach(ensureView);qsa('.view').forEach(v=>v.classList.remove('active'));const v=ensureView(name);v.classList.add('active');qsa('.drawer-item').forEach(i=>i.classList.toggle('active',i.dataset.view===name)); if(name==='v28-os') renderOS();}
  function addDrawer(){const m=$('drawerMenu'); if(!m||m.querySelector('[data-view="v28-os"]')) return; const html=`<div class="drawer-item" data-view="v28-os" onclick="showView('v28-os')"><i>🧠</i> V28 Ops OS</div>`; const anchor=m.querySelector('[data-view="v27-nexus"]')||m.querySelector('[data-view="portal"]'); if(anchor) anchor.insertAdjacentHTML('beforebegin',html); else m.insertAdjacentHTML('beforeend',html);}
  function patchNav(){if(window.__v28NavPatched) return; window.__v28NavPatched=true; const oldShow=window.showView; window.showView=function(name){if(name==='v28-os'){showLocal(name);return;} return oldShow?oldShow.apply(this,arguments):showLocal(name)}; const oldBuild=window.buildDrawerMenu; window.buildDrawerMenu=function(){const r=oldBuild?oldBuild.apply(this,arguments):undefined; addDrawer(); return r}; addDrawer();}
  function metrics(){
    const c=claims(), d=damage(), tx=(window.DB&&Array.isArray(window.DB.history)?window.DB.history:load('ojDB',{}).history)||[];
    const active=c.filter(x=>!['Closed','Resolved','Rejected'].includes(x.status||''));
    const high=c.filter(x=>(x.priority||'').toLowerCase()==='high'||riskClaim(x)>=70);
    const critical=d.filter(x=>(x.severity||'').toLowerCase()==='critical');
    const pending=outbox().filter(x=>x.status!=='done');
    const storage=storageStats();
    const ready=Math.max(8,Math.min(100,Math.round(100 - active.length*2.4 - critical.length*1.7 - pending.length*4 - Math.max(0,storage.mb-3)*4)));
    return {claims:c,damage:d,tx,active,high,critical,pending,storage,ready,notices:notices()};
  }
  function storageStats(){let bytes=0,items=[];try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i),v=localStorage.getItem(k)||'';const b=(k.length+v.length)*2;bytes+=b;items.push({k,b});}}catch(e){}items.sort((a,b)=>b.b-a.b);return{bytes,mb:bytes/1024/1024,pct:Math.min(100,Math.round(bytes/(5*1024*1024)*100)),items:items.slice(0,8)}}
  function riskClaim(c){let s=0; const t=(c.type||c.category||c.description||'').toLowerCase(); if(t.includes('damage')||t.includes('broken')||t.includes('lost'))s+=30; if((c.priority||'').toLowerCase()==='high')s+=30; if(['Submitted','Under Review','Processing'].includes(c.status||''))s+=20; if(!(c.lastName||c.psn||c.tag))s+=15; const age=Math.max(0,Date.now()-new Date(c.createdAt||c.created||Date.now()).getTime())/36e5; if(age>12)s+=15; return Math.min(100,Math.round(s));}
  function routePressure(dest){const m=metrics(); const key=String(dest||'').toUpperCase(); const c=m.claims.filter(x=>String(x.destination||x.route||'').toUpperCase().includes(key)).length; const d=m.damage.filter(x=>String(x.destination||'').toUpperCase().includes(key)).length; return Math.min(100,20+c*8+d*9+Math.round(Math.random()*8));}
  function renderOS(tab='overview'){const v=ensureView('v28-os'); const active=t=>tab===t?'active':''; v.innerHTML=`
    <div class="v28-shell card">
      <div class="v28-hero">
        <div class="v28-title"><div><h2>🧠 V28 Service Intelligence OS</h2><div class="v28-sub">Major upgrade focused on site-wide efficiency: passenger self-service, staff triage, data quality, notice control, offline outbox, and mobile readiness.</div></div><span class="v28-chip lime">REAL BUILD</span></div>
        <div class="v28-tabs"><button class="${active('overview')}" onclick="v28Tab('overview')">Overview</button><button class="${active('workflow')}" onclick="v28Tab('workflow')">Workflows</button><button class="${active('data')}" onclick="v28Tab('data')">Data Quality</button><button class="${active('notices')}" onclick="v28Tab('notices')">Notices</button></div>
        <div id="v28Body"></div>
      </div>
    </div>`; renderTab(tab);}
  window.v28Tab=function(tab){renderTab(tab);qsa('#view-v28-os .v28-tabs button').forEach(b=>b.classList.remove('active')); const labels={overview:0,workflow:1,data:2,notices:3}; const btn=qsa('#view-v28-os .v28-tabs button')[labels[tab]||0]; if(btn)btn.classList.add('active');};
  function renderTab(tab){const f={overview:overviewHTML,workflow:workflowHTML,data:dataHTML,notices:noticesHTML}[tab]||overviewHTML; const b=$('v28Body'); if(b)b.innerHTML=f();}
  function overviewHTML(){const m=metrics(); const readinessColor=m.ready>82?'lime':m.ready>62?'amber':'red';return `
    <div class="v28-grid"><div class="v28-kpi"><b>${m.ready}%</b><span>Site Readiness</span><div class="v28-meter" style="margin-top:10px"><span style="width:${m.ready}%"></span></div></div><div class="v28-kpi"><b>${m.active.length}</b><span>Active Claims</span><small>${m.high.length} high priority</small></div><div class="v28-kpi"><b>${m.critical.length}</b><span>Critical Damage</span><small>${m.damage.length} evidence cases</small></div><div class="v28-kpi"><b>${m.storage.mb.toFixed(2)}MB</b><span>Local Storage</span><small>${m.pending.length} pending outbox</small></div></div>
    <div class="v28-card"><div class="v28-title"><div><h2>Command Recommendation</h2><div class="v28-sub">Automated recommendation based on local claims, damage records, outbox, and storage pressure.</div></div><span class="v28-chip ${readinessColor}">${m.ready>82?'STABLE':m.ready>62?'WATCH':'ACTION'}</span></div>${recommendations(m).map((x,i)=>`<div class="v28-step" data-n="${i+1}"><b>${esc(x.title)}</b><br><small>${esc(x.text)}</small></div>`).join('')}</div>
    <div class="v28-grid2"><div class="v28-card"><div class="v28-title"><h2>Route Pressure Radar</h2><span class="v28-chip pink">Simulated</span></div>${DESTS.map(d=>{const p=routePressure(d);return`<div style="margin:9px 0"><div style="display:flex;justify-content:space-between;font-size:.78rem"><b>${d}</b><span>${p}%</span></div><div class="v28-meter"><span style="width:${p}%"></span></div></div>`}).join('')}</div><div class="v28-card"><div class="v28-title"><h2>Mini Live Map</h2><button class="sm primary" onclick="showView('map')">Open Map</button></div><div class="v28-mapline"><span class="v28-port" style="left:14%;top:70%">CEBU</span><span class="v28-port" style="left:82%;top:26%">BOHOL</span><span class="v28-port" style="left:70%;top:78%">ORMOC</span><span class="v28-vessel"></span></div><div class="v28-actions"><button class="accent block" onclick="v28ExportDayPack()">Export Day Pack</button><button class="block" onclick="v28RunAudit()">Run Audit</button></div></div></div>`}
  function recommendations(m){const r=[]; if(m.storage.mb>4)r.push({title:'Export backup now',text:'Local browser storage is high. Download a Day Pack before adding more photos.'}); if(m.pending.length)r.push({title:'Review offline outbox',text:m.pending.length+' local action(s) are waiting. Export or mark as completed before shift end.'}); if(m.critical.length)r.push({title:'Supervisor review required',text:m.critical.length+' critical damage evidence case(s) need review.'}); if(m.active.length>8)r.push({title:'Open staff triage',text:'Active claims are building up. Sort by risk and update the oldest cases.'}); if(!r.length)r.push({title:'System is ready',text:'No urgent site, storage, or service risks detected from local records.'}); r.push({title:'Use passenger self-service first',text:'Guide passengers to Claim Status, Report Baggage, and Smart Portal before staff escalation.'}); return r.slice(0,5)}
  function workflowHTML(){return `<div class="v28-grid2"><div class="v28-card"><div class="v28-title"><h2>Passenger Flow Builder</h2><span class="v28-chip">Self-service</span></div><div class="input-group"><label>Passenger need</label><select id="v28Need" onchange="v28BuildFlow()"><option value="damage">Damaged baggage</option><option value="lost">Lost baggage</option><option value="fare">Check fare</option><option value="schedule">Check schedule</option><option value="status">Track claim</option></select></div><div id="v28FlowOut"></div></div><div class="v28-card"><div class="v28-title"><h2>Staff Action Launcher</h2><span class="v28-chip pink">Fast ops</span></div><input id="v28Search" placeholder="Search action: damage, backup, fare, claim, map..." oninput="v28SearchActions()"><div id="v28SearchOut" style="margin-top:8px"></div></div></div><div class="v28-card"><div class="v28-title"><h2>One-Minute Shift Setup</h2><span class="v28-chip lime">Checklist</span></div><div class="v28-flow">${['Open Site Health Center and confirm storage is below warning level.','Export yesterday or previous-shift Day Pack if not yet saved.','Open Staff Counter and review high-priority active claims.','Check Public Notices for route advisories.','Keep Damage Detector ready for claim-stub, full baggage, and close-up photos.'].map((x,i)=>`<div class="v28-step" data-n="${i+1}">${esc(x)}</div>`).join('')}</div><div class="v28-actions"><button class="primary block" onclick="showView('sitehealth')">Site Health</button><button class="accent block" onclick="showView('staffcounter')">Staff Counter</button><button class="block" onclick="showView('damage')">Damage Detector</button></div></div>`}
  function dataHTML(){const m=metrics(); const risky=m.claims.map(c=>Object.assign({},c,{risk:riskClaim(c)})).sort((a,b)=>b.risk-a.risk).slice(0,12); const dup=duplicates(m.claims); const storage=m.storage.items.map(i=>`<div class="v28-row"><div><b>${esc(i.k)}</b><small>${(i.b/1024).toFixed(1)} KB</small></div></div>`).join('')||'<p class="muted">No local storage items found.</p>';return `<div class="v28-grid"><div class="v28-kpi"><b>${risky.filter(x=>x.risk>=70).length}</b><span>Risk Claims</span><small>Score ≥70</small></div><div class="v28-kpi"><b>${dup.length}</b><span>Duplicate Signals</span><small>Same tag / last name</small></div><div class="v28-kpi"><b>${m.storage.pct}%</b><span>Storage Load</span><small>${m.storage.mb.toFixed(2)}MB</small></div></div><div class="v28-card"><div class="v28-title"><h2>Claim Risk Queue</h2><button class="sm accent" onclick="v28ExportRiskCSV()">Export CSV</button></div><div class="v28-table"><table><thead><tr><th>Risk</th><th>Claim</th><th>Status</th><th>Issue</th><th>Action</th></tr></thead><tbody>${risky.map(c=>`<tr><td><span class="v28-chip ${c.risk>=70?'red':c.risk>=45?'amber':'lime'}">${c.risk}</span></td><td>${esc(c.id||c.caseId||'No ID')}<br><small>${esc(c.lastName||c.tag||'')}</small></td><td>${esc(c.status||'Submitted')}</td><td>${esc((c.description||c.type||'').slice(0,70))}</td><td><button class="sm" onclick="v28MarkReview('${esc(c.id||'')}')">Review</button></td></tr>`).join('')||'<tr><td colspan="5">No claims found.</td></tr>'}</tbody></table></div></div><div class="v28-grid2"><div class="v28-card"><div class="v28-title"><h2>Duplicate Signals</h2><button class="sm" onclick="v28FlagDuplicates()">Flag duplicates</button></div>${dup.map(x=>`<div class="v28-row"><div><b>${esc(x.key)}</b><small>${x.count} possible records</small></div></div>`).join('')||'<p class="muted">No duplicate signals detected.</p>'}</div><div class="v28-card"><div class="v28-title"><h2>Storage Audit</h2><button class="sm danger" onclick="v28CompactLogs()">Compact logs</button></div>${storage}</div></div>`}
  function noticesHTML(){const ns=notices();return `<div class="v28-grid2"><div class="v28-card"><div class="v28-title"><h2>Notice Composer</h2><span class="v28-chip amber">Local</span></div><div class="input-group"><label>Audience</label><select id="v28NoticeAudience"><option>Passengers</option><option>Baggage Staff</option><option>Cashiers</option><option>All Ports</option></select></div><div class="input-group"><label>Title</label><input id="v28NoticeTitle" placeholder="Example: Cebu-Tagbilaran boarding reminder"></div><div class="input-group"><label>Message</label><textarea id="v28NoticeMsg" rows="4" placeholder="Write route advisory, claim instruction, or port reminder..."></textarea></div><div class="v28-actions"><button class="primary block" onclick="v28SaveNotice()">Save Notice</button><button class="accent block" onclick="v28ExportNotices()">Export Notices</button></div></div><div class="v28-card"><div class="v28-title"><h2>Public Notice Board</h2><span class="v28-chip pink">${ns.length} active</span></div>${ns.map(n=>`<div class="v28-notice"><span class="v28-chip">${esc(n.audience)}</span><h3 style="margin:8px 0;color:#fff">${esc(n.title)}</h3><small>${esc(n.time)}</small><p>${esc(n.msg)}</p><button class="sm danger" onclick="v28DeleteNotice('${esc(n.id)}')">Delete</button></div>`).join('')||'<p class="muted">No V28 notices saved yet.</p>'}</div></div><div class="v28-card"><div class="v28-title"><h2>Offline Outbox</h2><button class="sm" onclick="v28ClearOutboxDone()">Clear done</button></div>${outbox().map(x=>`<div class="v28-row"><div><b>${esc(x.type)}</b><small>${esc(x.time)} • ${esc(x.status||'pending')}</small></div><button class="sm" onclick="v28OutboxDone('${esc(x.id)}')">Done</button></div>`).join('')||'<p class="muted">Outbox empty.</p>'}</div>`}
  window.v28BuildFlow=function(){const need=$('v28Need')?.value||'damage'; const map={damage:[['Open Damage Detector','Capture claim stub, full baggage, and damage close-up.'],['Confirm passenger details','Check PSN, last name, route, and tag number.'],['Save evidence','Review evidence score and lock if ready.'],['Give claim reference','Passenger tracks status in Claim Status.']],lost:[['Open Report Baggage','Create lost baggage record with tag, route, last seen port.'],['Assign priority','Mark high if medicine, ID, or fragile item is involved.'],['Staff counter review','Update status every handling step.']],fare:[['Open Fares','Select route and passenger class.'],['Use official baggage calculator separately','Chat assistant must not compute official baggage fees.']],schedule:[['Open Schedules','Check route and next departure.'],['Create notice if needed','Publish advisory for late trip or port changes.']],status:[['Open Claim Status','Search claim number or passenger last name.'],['Show timeline','Explain Submitted → Under Review → Processing → Closed.']]}; const out=$('v28FlowOut'); if(out) out.innerHTML='<div class="v28-flow">'+map[need].map((x,i)=>`<div class="v28-step" data-n="${i+1}"><b>${esc(x[0])}</b><br><small>${esc(x[1])}</small></div>`).join('')+'</div>';};
  window.v28SearchActions=function(){const q=($('v28Search')?.value||'').toLowerCase(); const acts=[['damage','Damage Detector','damage'],['claim','Claim Status','claimstatus'],['report','Report Baggage','lostbaggage'],['staff','Staff Counter','staffcounter'],['fare','Fares','fares'],['schedule','Schedules','schedules'],['backup','Site Health','sitehealth'],['map','Live Map','map'],['admin','Admin Panel','admin'],['safe','Safe Mode','safemode'],['export','Export Center','exportcenter']]; const list=acts.filter(a=>!q||a.join(' ').toLowerCase().includes(q)).slice(0,8); const out=$('v28SearchOut'); if(out) out.innerHTML=list.map(a=>`<div class="v28-row"><div><b>${a[1]}</b><small>Open ${a[2]}</small></div><button class="sm primary" onclick="showView('${a[2]}')">Open</button></div>`).join('')||'<p class="muted">No action found.</p>';};
  window.v28RunAudit=function(){const s=settings();s.lastAudit=now();save(SETTINGS_KEY,s); audit('audit','Manual data quality audit executed'); toast('V28 audit complete.'); renderOS('data')};
  window.v28MarkReview=function(id){const arr=claims(); const c=arr.find(x=>x.id===id); if(c){c.status='Under Review';c.updatedAt=now();save(CLAIM_KEY,arr); enqueue('claim_review','Marked '+id+' Under Review');toast('Claim marked Under Review.');renderTab('data')}};
  function duplicates(arr){const map={}; arr.forEach(c=>{['tag','tagNo','lastName','psn'].forEach(k=>{const v=String(c[k]||'').trim().toLowerCase(); if(v) (map[k+': '+v]||(map[k+': '+v]=[])).push(c)})}); return Object.entries(map).filter(([k,v])=>v.length>1).map(([k,v])=>({key:k,count:v.length,items:v}))}
  window.v28FlagDuplicates=function(){const arr=claims(); const d=duplicates(arr); d.forEach(x=>x.items.forEach(c=>{c.duplicateSignal=true;c.updatedAt=now()})); save(CLAIM_KEY,arr); enqueue('data_quality','Flagged '+d.length+' duplicate signal groups'); toast('Duplicate signals flagged.'); renderTab('data')};
  window.v28CompactLogs=function(){const h=load(HEALTH_KEY,[]).slice(0,40); const a=load(LOG_KEY,[]).slice(0,40); save(HEALTH_KEY,h); save(LOG_KEY,a); toast('Logs compacted.'); renderTab('data')};
  function enqueue(type,msg){const o=outbox();o.unshift({id:'V28-'+Date.now().toString(36),type,msg,time:now(),status:'pending'});save(OUTBOX_KEY,o.slice(0,80));}
  window.v28OutboxDone=function(id){const o=outbox();const x=o.find(i=>i.id===id);if(x)x.status='done';save(OUTBOX_KEY,o);renderTab('notices')};
  window.v28ClearOutboxDone=function(){save(OUTBOX_KEY,outbox().filter(x=>x.status!=='done'));renderTab('notices')};
  window.v28SaveNotice=function(){const title=($('v28NoticeTitle')?.value||'').trim(), msg=($('v28NoticeMsg')?.value||'').trim(), audience=$('v28NoticeAudience')?.value||'Passengers'; if(!title||!msg){toast('Add title and message.');return;} const ns=notices();ns.unshift({id:'N'+Date.now().toString(36),title,msg,audience,time:now()});save(NOTICE_KEY,ns.slice(0,30));enqueue('notice','Saved notice: '+title);toast('Notice saved.');renderTab('notices')};
  window.v28DeleteNotice=function(id){save(NOTICE_KEY,notices().filter(n=>n.id!==id));toast('Notice deleted.');renderTab('notices')};
  window.v28ExportNotices=function(){download(JSON.stringify({version:VERSION,exportedAt:now(),notices:notices()},null,2),'application/json','oceanjet_v28_notices.json')};
  window.v28ExportRiskCSV=function(){const rows=[['risk','id','status','priority','lastName','tag','description'].join(',')].concat(claims().map(c=>[riskClaim(c),c.id,c.status,c.priority,c.lastName,c.tag,String(c.description||'').replace(/[\r\n,]+/g,' ')].map(csv).join(',')));download(rows.join('\n'),'text/csv','oceanjet_v28_claim_risk_queue.csv')};
  window.v28ExportDayPack=function(){const m=metrics(); const data={version:VERSION,exportedAt:now(),readiness:m.ready,claims:m.claims,damage:m.damage,transactions:m.tx,notices:m.notices,outbox:outbox(),storage:m.storage,logs:load(LOG_KEY,[])};download(JSON.stringify(data,null,2),'application/json','oceanjet_v28_day_pack.json');enqueue('backup','Day Pack exported');toast('V28 Day Pack exported.')};
  function csv(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
  function download(data,type,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
  function patchDashboard(){try{const v=$('view-dashboard'); if(!v||$('v28Dash')) return; const m=metrics(); v.insertAdjacentHTML('afterbegin',`<div id="v28Dash" class="card v28-shell"><div class="v28-title"><div><h2>🧠 V28 Service Intelligence</h2><div class="v28-sub">Readiness ${m.ready}% • ${m.active.length} active claims • ${m.pending.length} outbox items</div></div><button class="sm primary" onclick="showView('v28-os')">Open</button></div></div>`)}catch(e){}}
  function patchMap(){try{const v=$('view-map'); if(!v||$('v28Map')) return; v.insertAdjacentHTML('afterbegin',`<div id="v28Map" class="card v28-shell"><div class="v28-title"><div><h2>🗺️ V28 Route Pressure Layer</h2><div class="v28-sub">Adds service pressure and passenger disruption context to the existing map tab.</div></div><button class="sm accent" onclick="showView('v28-os')">Analyze</button></div></div>`)}catch(e){}}
  function boot(){try{document.body.classList.add('v28-mobile-polish'); VIEWS.forEach(ensureView); patchNav(); if(typeof window.buildDrawerMenu==='function') window.buildDrawerMenu(); setTimeout(()=>{patchDashboard();patchMap();},700); audit('boot',VERSION+' loaded'); console.log(VERSION+' loaded');}catch(e){console.error('V28 boot error',e);audit('boot_error',e.message);toast('V28 recovery: '+e.message)}}
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})();
