
(function(){
  if(window.__OJ42_CLEAN_HOME__) return; window.__OJ42_CLEAN_HOME__='V42_CLEAN_HOME';
  const VERSION='OceanJet V42 Clean Home Organizer';
  const $=id=>document.getElementById(id);
  const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const ROLE_KEY='oj41_role', LEGACY_KEY='oj_v35_active_role';
  const roleLabel={pax:'Passenger',cashier:'Cashier',admin:'Admin'};
  function norm(r){r=String(r||'pax').toLowerCase(); if(['admin','supervisor','sup'].includes(r))return 'admin'; if(['cashier','staff','counter'].includes(r))return 'cashier'; return 'pax';}
  function getRole(){try{return norm(sessionStorage.getItem(ROLE_KEY)||sessionStorage.getItem(LEGACY_KEY)||localStorage.getItem(ROLE_KEY)||'pax')}catch(e){return 'pax'}}
  function setRole(r){r=norm(r); try{sessionStorage.setItem(ROLE_KEY,r);sessionStorage.setItem(LEGACY_KEY,r);localStorage.setItem(ROLE_KEY,r)}catch(e){} try{window.currentRole=r==='admin'?'supervisor':r==='cashier'?'cashier':null}catch(e){} document.body.classList.toggle('oj42-role-pax',r==='pax');document.body.classList.toggle('oj42-role-cashier',r==='cashier');document.body.classList.toggle('oj42-role-admin',r==='admin');document.body.classList.toggle('oj41-role-pax',r==='pax');document.body.classList.toggle('oj41-role-cashier',r==='cashier');document.body.classList.toggle('oj41-role-admin',r==='admin');document.body.classList.toggle('oj35-pax',r==='pax');document.body.classList.toggle('oj35-cashier',r==='cashier');document.body.classList.toggle('oj35-admin',r==='admin'); const badge=$('roleBadge'); if(badge) badge.textContent=(r==='pax'?'👤 ':r==='cashier'?'💼 ':'👑 ')+roleLabel[r];}
  const MENU={
    pax:[{title:'Passenger essentials',hint:'public only',items:[['calculator','🧮','Baggage Fee','Compute baggage charge'],['damage','📸','Damage Report','Open evidence scanner'],['fares','💵','Fares','Passenger prices'],['schedules','🕐','Schedules','Trip guide'],['claimstatus','🔎','Claim Status','Track local claim']]},{title:'Staff access',hint:'login required',items:[['login-cashier','💼','Cashier Login','Counter tools'],['login-admin','🔐','Admin Login','Full access']]}],
    cashier:[{title:'Counter workflow',hint:'daily tools',items:[['calculator','🧮','Calculator + Receipt','Baggage fee PDF'],['damage','📸','Damage Evidence','Capture report'],['ar','📹','AR Scanner','Camera scanner'],['lostbaggage','🧳','Claim Form','Lost/damage intake'],['history','📋','Transactions','Daily records'],['reports','📄','PDF Center','Export reports']]},{title:'Reference',hint:'quick lookup',items:[['fares','💵','Fares','Price matrix'],['schedules','🕐','Schedules','Routes']]},{title:'Access',hint:'role control',items:[['login-admin','🔐','Admin Login','Unlock all'],['logout','🚪','Passenger Mode','Public view']]}],
    admin:[{title:'Operations',hint:'front desk',items:[['calculator','🧮','Baggage Calculator','Official pricing'],['damage','📸','Damage Evidence','AR/reporting'],['ar','📹','AR Scanner','Camera capture'],['fares','💵','Fare Matrix','Passenger prices'],['schedules','🕐','Schedules','Route board']]},{title:'Records + reports',hint:'audit ready',items:[['history','📋','Transactions','Receipt history'],['reports','📄','PDF Reports','Professional exports'],['admin','⚙️','Admin Panel','Settings/backups']]},{title:'Maintenance',hint:'organized advanced',items:[['sitehealth','🛟','Site Health','Diagnostics'],['advanced','🧬','Advanced Modules','Hidden old tools'],['logout','🚪','Passenger Mode','Return public']]}]
  };
  function expectedViews(){return (MENU[getRole()]||MENU.pax).flatMap(g=>g.items.map(i=>i[0]));}
  function itemHTML(i){return `<div class="drawer-item oj42-menuItem" data-view="${esc(i[0])}" onclick="oj42Open('${esc(i[0])}')"><i>${i[1]}</i><span class="oj42-itemText"><b>${esc(i[2])}</b><small>${esc(i[3])}</small></span><span class="oj42-chevron">›</span></div>`}
  function buildDrawer42(){const box=$('drawerMenu'); if(!box)return; const role=getRole(); setRole(role); const groups=MENU[role]||MENU.pax; box.innerHTML=`<div class="oj42-drawerShell"><div class="oj42-drawerHead"><b>OceanJet Baggage Desk</b><small>Clean role-based navigation. No duplicate test modules in the main drawer.</small><span class="oj42-rolePill">${role==='pax'?'👤':role==='cashier'?'💼':'👑'} ${esc(roleLabel[role])} Mode</span></div>${groups.map(g=>`<section class="oj42-menuGroup"><div class="oj42-menuLabel"><span>${esc(g.title)}</span><span class="oj42-menuCount">${esc(g.hint)}</span></div><div class="oj42-menuList">${g.items.map(itemHTML).join('')}</div></section>`).join('')}<div class="oj42-safeNote">Admin keeps full access, but advanced/experimental modules are grouped away so the app feels like a clean professional home screen.</div></div>`; qsa('.oj42-menuItem',box).forEach(x=>{x.classList.remove('oj35-lock','v14-hidden','oj41-lock');x.style.display='';x.style.visibility='';}); markActive(); }
  function drawerSig(){const box=$('drawerMenu'); if(!box)return ''; return qsa('.oj42-menuItem',box).map(x=>x.dataset.view||'').join('|')}
  function expectedSig(){return expectedViews().join('|')}
  function enforceDrawer42(){const box=$('drawerMenu'); if(!box)return; qsa('.drawer-item:not(.oj42-menuItem)',box).forEach(x=>x.remove()); if(drawerSig()!==expectedSig() || !box.querySelector('.oj42-drawerShell')) buildDrawer42(); qsa('.drawer-item:not(.oj42-menuItem)',box).forEach(x=>x.remove()); qsa('.oj42-menuItem',box).forEach(x=>{x.classList.remove('oj35-lock','v14-hidden','oj41-lock');x.style.display='';x.style.visibility='';}); removeClutter(); markActive();}
  function markActive(){let active=(qsa('.view.active')[0]?.id||'').replace(/^view-/,'').replace(/^oj42-/,''); if(/home$|oj41-home|v35-home|dashboard/.test(active)) active='home'; qsa('#drawerMenu .oj42-menuItem').forEach(x=>x.classList.toggle('active',(x.dataset.view||'')===active));}
  function closeDrawer(){try{$('sideDrawer')?.classList.remove('open');$('overlay')?.classList.remove('show');$('hamburger')?.classList.remove('open')}catch(e){}}
  function ensureView(name){const id=name.startsWith('view-')?name:'view-'+name; let v=$(id); if(!v){v=document.createElement('div');v.id=id;v.className='view';(document.querySelector('.app')||document.body).appendChild(v)} return v}
  function activate(name){qsa('.view').forEach(v=>v.classList.remove('active')); const v=ensureView(name); v.classList.add('active'); closeDrawer(); markActive(); try{window.scrollTo({top:0,behavior:'smooth'})}catch(e){window.scrollTo(0,0)} return v}
  function stats(){let tx=0,rev=0,kg=0,damage=0,claims=0;try{const db=JSON.parse(localStorage.getItem('ojDB')||'{}'); const h=Array.isArray(db.history)?db.history:[]; tx=h.length; rev=h.reduce((a,b)=>a+(Number(b.total)||0),0); kg=db?.stats?.totalKg||0}catch(e){} try{const d=JSON.parse(localStorage.getItem('oj_damage_master_v11_backup')||'{}'); damage=(d.cases||[]).length}catch(e){} try{claims=(JSON.parse(localStorage.getItem('oj_v22_claims')||'[]')||[]).length}catch(e){} return {tx,rev,kg,damage,claims};}
  function kpis(){const s=stats();return `<div class="oj42-kpiGrid"><div class="oj42-kpi"><b>${s.tx}</b><span>Transactions</span></div><div class="oj42-kpi"><b>${s.damage+s.claims}</b><span>Claims/Evidence</span></div><div class="oj42-kpi"><b>₱${Math.round(s.rev).toLocaleString('en-PH')}</b><span>Recorded sales</span></div></div>`}
  function card(ico,title,sub,target,tone=''){return `<button class="oj42-cardBtn ${tone}" onclick="oj42Open('${esc(target)}')"><span><i>${ico}</i><b>${esc(title)}</b><small>${esc(sub)}</small></span><span class="oj42-chip ${tone==='hot'?'pink':tone==='gold'?'gold':tone==='green'?'green':''}">Open</span></button>`}
  function step(n,title,sub,tag='Ready'){return `<div class="oj42-step"><div class="oj42-stepNum">${n}</div><div><b>${esc(title)}</b><small>${esc(sub)}</small></div><span class="oj42-chip green">${esc(tag)}</span></div>`}
  function quickFind(){const q=($('oj42Quick')?.value||'').toLowerCase(); const table=[['calc','calculator'],['fee','calculator'],['bag','calculator'],['damage','damage'],['scanner','damage'],['ar','ar'],['fare','fares'],['price','fares'],['schedule','schedules'],['claim','claimstatus'],['receipt','reports'],['pdf','reports'],['admin','login-admin'],['cashier','login-cashier']]; const hit=table.find(x=>q.includes(x[0])); if(hit) open42(hit[1]); else toast('Search: try baggage, damage, fare, schedule, claim, PDF, cashier, or admin.');}
  function renderHome42(){const role=getRole(); const v=activate('oj41-home'); let title,sub,chip,tone,cards,steps,sectionLabel;
    if(role==='cashier'){title='Counter Desk Home';sub='Cashier tools are arranged by real counter workflow: compute, receipt, evidence, claim, then report.';chip='CASHIER';tone='gold';sectionLabel='Counter workflow';cards=card('🧮','Baggage calculator','Compute fee and prepare PDF receipt.','calculator','green')+card('📸','Damage evidence','Capture/report damaged baggage.','damage','hot')+card('📹','AR scanner','Open camera scanner for baggage damage.','ar')+card('🧳','Claim form','Lost/damaged baggage intake.','lostbaggage','gold')+card('📋','Transactions','View cashier transaction history.','history')+card('📄','PDF center','Export professional receipts and reports.','reports','green');steps=step(1,'Compute baggage fee','Use preserved official calculator logic.')+step(2,'Issue PDF receipt','Export passenger-ready receipt/report.')+step(3,'Record damage/claim','Capture evidence and keep records organized.');}
    else if(role==='admin'){title='Admin Control Tower';sub='Admin has everything, but the home screen stays clean. Old experimental modules are hidden under Advanced Modules.';chip='FULL ACCESS';tone='hot';sectionLabel='Admin workflow';cards=card('🧮','Baggage calculator','Preserved official baggage logic.','calculator','green')+card('📸','Damage + AR','Evidence detector/scanner workflow.','damage','hot')+card('💵','Fare matrix','Passenger and baggage price reference.','fares','gold')+card('📄','PDF reports','Receipts, transactions, claims, audit.','reports','green')+card('⚙️','Admin panel','Settings, backup, and controls.','admin','hot')+card('🧬','Advanced modules','Grouped old tools, not mixed in main tabs.','advanced');steps=step(1,'Daily operation tools','Passenger/cashier tools are accessible.')+step(2,'Reports and audit','PDF-first export center for records.')+step(3,'Maintenance only when needed','Technical modules kept in Advanced.');}
    else {title='Passenger Home';sub='Default public mode. Passengers only see simple tools: baggage fee, fares, schedules, damage report, and claim tracking.';chip='DEFAULT';tone='green';sectionLabel='Passenger essentials';cards=card('🧮','Check baggage fee','Use the preserved OceanJet baggage calculator.','calculator','green')+card('📸','Report damage','Open baggage damage detector / AR evidence flow.','damage','hot')+card('💵','View fares','Passenger and baggage price guide.','fares','gold')+card('🕐','Schedules','Route and trip schedule guide.','schedules')+card('🔎','Track claim','Lookup local claim status.','claimstatus')+card('💼','Staff login','Cashier/Admin tools stay locked.','login-cashier');steps=step(1,'Open passenger tools','No login required for public use.')+step(2,'Calculate or report','Baggage fee and damage report stay easy.')+step(3,'Staff login only when needed','Counter/admin tools are hidden from passengers.');}
    v.innerHTML=`<div class="oj42-page"><div class="oj42-hero"><div class="oj42-title"><div><h1>${esc(title)}</h1><div class="oj42-sub">${esc(sub)}</div></div><span class="oj42-chip ${tone==='hot'?'pink':tone==='gold'?'gold':'green'}">${esc(chip)}</span></div>${kpis()}<div class="oj42-miniSearch"><input id="oj42Quick" placeholder="Quick open: baggage, damage, fare, schedule, claim, PDF..." onkeydown="if(event.key==='Enter')oj42QuickFind()"><button onclick="oj42QuickFind()">Open</button></div></div><div class="oj42-section"><div class="oj42-sectionHead"><b>${esc(sectionLabel)}</b><small>clean home tiles</small></div><div class="oj42-cardGrid">${cards}</div></div><div class="oj42-section"><div class="oj42-sectionHead"><b>Organized flow</b><small>no messy tabs</small></div><div class="oj42-steps">${steps}</div></div></div>`;}
  function toast(msg){try{if(typeof window.toast41==='function') return window.toast41(msg); if(typeof window.toast35==='function') return window.toast35(msg);}catch(e){} let d=$('oj42Toast'); if(!d){d=document.createElement('div');d.id='oj42Toast';d.style.cssText='position:fixed;left:18px;right:18px;bottom:22px;z-index:999999;padding:13px 16px;border-radius:18px;background:rgba(5,10,24,.94);border:1px solid rgba(93,247,255,.35);color:#fff;font-weight:800;text-align:center;box-shadow:0 16px 50px rgba(0,0,0,.4)';document.body.appendChild(d)} d.textContent=msg; d.style.display='block'; clearTimeout(d._t); d._t=setTimeout(()=>d.style.display='none',2300);}

  function getClaims42(){let out=[];const keys=['oj_v22_claims','oj_v23_claims','oj_v24_tickets','oj_v25_queue','oj_v26_interactions','oj_v27_claims','oj_v29_claims','oj_v30_service_tickets','oj_v33_field_records'];keys.forEach(k=>{try{const v=JSON.parse(localStorage.getItem(k)||'[]'); if(Array.isArray(v)) out=out.concat(v.map(x=>Object.assign({__key:k},x)));}catch(e){}});return out;}
  function claimId42(x,i){return x.id||x.claimId||x.ticketId||x.ref||x.reference||x.caseId||('LOCAL-'+String(i+1).padStart(3,'0'))}
  function claimStatus42(x){return x.status||x.state||x.stage||'Submitted'}
  function renderClaimStatus42(){const v=activate('claimstatus');const rows=getClaims42();v.innerHTML=`<div class="oj42-page"><div class="oj42-hero"><div class="oj42-title"><div><h1>Claim Status</h1><div class="oj42-sub">Passenger-safe local claim lookup. Search claim number, last name, baggage tag, route, or issue.</div></div><span class="oj42-chip green">PUBLIC</span></div></div><div class="oj42-section"><div class="oj42-sectionHead"><b>Search claim</b><small>${rows.length} local record(s)</small></div><div class="oj42-miniSearch"><input id="oj42ClaimQuery" placeholder="Enter claim number, last name, PSN, tag, or route" oninput="oj42FilterClaims()"><button onclick="oj42FilterClaims()">Search</button></div><div id="oj42ClaimResults" class="oj42-steps" style="margin-top:12px"></div></div></div>`;window.oj42FilterClaims=function(){const q=($('oj42ClaimQuery')?.value||'').toLowerCase().trim();const list=rows.filter((x,i)=>!q||JSON.stringify(x).toLowerCase().includes(q)||claimId42(x,i).toLowerCase().includes(q)).slice(0,30);const box=$('oj42ClaimResults');if(!box)return;box.innerHTML=list.length?list.map((x,i)=>`<div class="oj42-step"><div class="oj42-stepNum">${i+1}</div><div><b>${esc(claimId42(x,i))}</b><small>${esc(claimStatus42(x))} • ${esc(x.route||x.trip||x.port||'OceanJet baggage record')} • ${esc(x.name||x.lastName||x.passenger||x.tag||x.baggageTag||'No passenger/tag saved')}</small></div><span class="oj42-chip green">${esc(claimStatus42(x))}</span></div>`).join(''):'<div class="oj42-safeNote">No matching local claim found on this device. Staff may need to check the master log or create a new claim record.</div>';};window.oj42FilterClaims();}

  function removeClutter(){['oj33Fab','v11Dock','v10Dock','v9CleanDock','v8Dock','v7Dock','oj35Fab','oj30Fab','oj29Fab'].forEach(id=>{const el=$(id); if(el){el.classList.add('oj42-hidden'); el.style.display='none';}}); qsa('button,div,a').forEach(el=>{const txt=(el.textContent||'').trim(); const cs=getComputedStyle(el); if(/^(🧭\s*)?V\s?33$/i.test(txt) && cs.position==='fixed'){el.classList.add('oj42-hidden'); el.style.display='none';}});}
  function open42(target){target=String(target||'home'); if(target==='home'||target==='dashboard'||target==='v35-home'||target==='oj41-home'){setRole(getRole());renderHome42();enforceDrawer42();return;} if(target==='logout'){setRole('pax');renderHome42();enforceDrawer42();toast('Returned to Passenger Mode.');return;} if(target==='claimstatus'){renderClaimStatus42();enforceDrawer42();return;} if(target==='login-cashier'||target==='login-admin'||target==='reports'||target==='advanced'){try{ if(typeof window.oj41Open==='function'){window.oj41Open(target); setTimeout(enforceDrawer42,80); return;} }catch(e){console.warn(e)}} try{ if(typeof window.oj41Open==='function'){window.oj41Open(target); setTimeout(enforceDrawer42,80); return;} }catch(e){console.warn('oj41Open fallback',e)} try{ if(typeof window.__oj42LegacyShow==='function'){window.__oj42LegacyShow(target); setTimeout(enforceDrawer42,80); return;} }catch(e){console.warn('legacy fallback',e)} activate(target);}
  window.oj42Open=open42; window.oj42QuickFind=quickFind;
  function patchNav(){ if(!window.__oj42LegacyShow && typeof window.showView==='function') window.__oj42LegacyShow=window.showView; window.showView=function(name){return open42(name)}; try{showView=window.showView}catch(e){} window.navigate=function(name){return open42(name)}; window.buildDrawerMenu=buildDrawer42; try{buildDrawerMenu=window.buildDrawerMenu}catch(e){} window.toggleDrawer=function(){enforceDrawer42();$('sideDrawer')?.classList.toggle('open');$('overlay')?.classList.toggle('show');$('hamburger')?.classList.toggle('open')}; window.closeDrawer=closeDrawer; }
  function watch(){const box=$('drawerMenu'); if(!box||box.__oj42Watch)return; box.__oj42Watch=true; let t=null; new MutationObserver(()=>{clearTimeout(t);t=setTimeout(enforceDrawer42,25)}).observe(box,{childList:true,subtree:true,characterData:true});}
  function keepHome42(){const a=qsa('.view.active')[0]; if(!a || a.id==='view-oj41-home' || a.id==='view-oj42-home' || a.id==='view-dashboard') renderHome42();}
  function boot(){document.body.classList.add('oj42-ready'); document.title='OceanJet Baggage Pro V42'; setRole(getRole()); patchNav(); buildDrawer42(); watch(); removeClutter(); renderHome42(); [250,600,1000,1800,3000,5000,8000,12000].forEach(ms=>setTimeout(enforceDrawer42,ms)); [700,1200,1700,2600,4200,6200,8500,12500].forEach(ms=>setTimeout(()=>{enforceDrawer42();keepHome42();},ms)); if(!window.__oj42Interval){window.__oj42Interval=setInterval(enforceDrawer42,1800)} console.log(VERSION+' loaded');}
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})();
