
(function(){
  if(window.__OJ_V27_MAJOR_COMMAND_UPGRADE__) return;
  window.__OJ_V27_MAJOR_COMMAND_UPGRADE__ = true;

  const VERSION = 'V27_MAJOR_COMMAND_UPGRADE';
  const KEYS = {
    claims:'oj_v22_claims', damage:'oj_damage_master_log_v11', sync:'oj_v26_sync_queue', messages:'oj_v26_messages', journeys:'oj_v26_journeys',
    audit:'oj_v26_audit', notices:'oj_v25_notices', tickets:'oj_v24_service_tickets', feedback:'oj_v24_feedback', prefs:'oj_v27_prefs', shifts:'oj_v27_shifts', tasks:'oj_v27_tasks', snapshots:'oj_v27_snapshots', content:'oj_v22_content'
  };
  const $ = id => document.getElementById(id);
  const qs = (s,r=document) => r.querySelector(s);
  const qsa = (s,r=document) => Array.from(r.querySelectorAll(s));
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const now = () => new Date().toLocaleString('en-PH',{timeZone:'Asia/Manila',hour12:true});
  const today = () => new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'});
  const uid = p => p+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase();
  function load(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){return f}}
  function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){audit('storage_error',e.message);return false}}
  function toast(msg){try{if(typeof window.toast==='function')return window.toast(msg)}catch(e){} const t=document.createElement('div');t.textContent=msg;t.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);background:#07112a;color:white;border:1px solid #6ffcff;border-radius:999px;padding:10px 15px;font:800 12px system-ui;z-index:99999;box-shadow:0 8px 28px #0009';document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
  function audit(type,msg){const a=load(KEYS.audit,[]);a.unshift({id:uid('AUD'),type,msg:String(msg||''),at:now(),online:navigator.onLine});save(KEYS.audit,a.slice(0,220));}
  function prefs(){return Object.assign({fast:false,big:false,kiosk:false,lastSnapshot:''},load(KEYS.prefs,{}))}
  function setPrefs(p){save(KEYS.prefs,p);document.body.classList.toggle('oj-v27-fast',!!p.fast);document.body.classList.toggle('v27-big',!!p.big);document.body.classList.toggle('oj-v27-kiosk',!!p.kiosk)}
  function isAdmin(){try{return sessionStorage.getItem('oj_v22_admin_unlocked')==='1'||localStorage.getItem('oj_v22_admin_unlocked')==='1'}catch(e){return false}}
  function unlockAdmin(u,p){const ok=(u==='admin'&&p==='admin')||(u==='demo'&&p==='demo')||(u==='supervisor'&&p==='supervisor');if(ok){sessionStorage.setItem('oj_v22_admin_unlocked','1');audit('admin_unlock','V27 local admin unlock');return true}return false}
  function ensureView(name){let v=$('view-'+name);if(!v){v=document.createElement('div');v.id='view-'+name;v.className='view';(qs('.app')||document.body).appendChild(v)}return v}
  function openClaims(){return [...load(KEYS.claims,[]),...load(KEYS.damage,[])].filter(c=>!['Closed','Resolved','Rejected','Done'].includes(String(c.status||'New')))}
  function allClaims(){return [...load(KEYS.claims,[]),...load(KEYS.damage,[])]}
  function statusOf(c){return String(c.status||c.claimStatus||'New')}
  function claimId(c){return c.claimId||c.caseId||c.id||c.ticketId||'NO-ID'}
  function tagOf(c){return c.tagNo||c.tag||c.baggageTag||''}
  function routeOf(c){return c.route||c.destination||c.dest||'Unknown'}
  function risk(c){const text=JSON.stringify(c).toLowerCase();let n=12;if(/critical|urgent|wet|missing|crack|broken|wheel|handle|priority/.test(text))n+=38;if(!tagOf(c))n+=13;if(!(c.lastName||c.name||c.passengerName))n+=9;if(!(c.contact||c.phone||c.email))n+=9;if(statusOf(c)==='New')n+=9;return Math.min(100,n)}
  function storage(){let bytes=0,rows=[];try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';const v=localStorage.getItem(k)||'';const b=(k.length+v.length)*2;bytes+=b;rows.push({k,b})}}catch(e){}return{bytes,mb:bytes/1048576,pct:Math.min(100,Math.round(bytes/(4.8*1048576)*100)),rows:rows.sort((a,b)=>b.b-a.b)}}
  function metrics(){const oc=openClaims();const ac=allClaims();const urgent=oc.filter(c=>risk(c)>=65);const sync=load(KEYS.sync,[]);const st=storage();const msgs=load(KEYS.messages,[]);const notices=load(KEYS.notices,[]);const ready=Math.max(0,100-urgent.length*8-sync.length*2-Math.max(0,st.pct-72));return{oc,ac,urgent,sync,st,msgs,notices,ready}}
  function routeLabel(r){try{if(typeof window.label==='function')return window.label(r)}catch(e){} const map={cebu_tagbilaran:'Cebu → Tagbilaran',cebu_maasin:'Cebu → Maasin',cebu_surigao:'Cebu → Surigao',cebu_siquijor:'Cebu → Siquijor',cebu_dumaguete:'Cebu → Dumaguete',cebu_ormoc:'Cebu → Ormoc',cebu_palompon:'Cebu → Palompon',cebu_getafe:'Cebu → Getafe'};return map[r]||String(r||'All routes').replace(/_/g,' → ').replace(/\b\w/g,c=>c.toUpperCase())}
  function routes(){return ['cebu_tagbilaran','cebu_maasin','cebu_surigao','cebu_siquijor','cebu_dumaguete','cebu_ormoc','cebu_palompon','cebu_getafe']}
  function routeOptions(sel){return routes().map(r=>`<option value="${r}" ${r===sel?'selected':''}>${esc(routeLabel(r))}</option>`).join('')}
  function action(ico,title,sub,view){return `<button class="v27-action" onclick="showView('${view}')"><span class="ico">${ico}</span><b>${esc(title)}</b><small>${esc(sub)}</small></button>`}
  function kpis(m){return `<div class="v27-grid3" style="margin-top:12px"><div class="v27-kpi"><b>${m.ready}%</b><span>Site Ready</span></div><div class="v27-kpi"><b>${m.oc.length}</b><span>Open Claims</span></div><div class="v27-kpi"><b>${m.urgent.length}</b><span>Priority</span></div></div>`}
  function colorBy(v){return v>=80?'green':v>=55?'amber':'red'}

  function renderNexus(){const m=metrics();ensureView('v27-nexus').innerHTML=`
    <div class="card v27-shell"><div class="v27-title"><div><h1>🚀 V27 Command Nexus</h1><div class="v27-sub">Major upgrade layer for faster passenger service, smarter staff decisions, stronger data safety, and mobile-first GitHub Pages operation.</div></div><span class="v27-chip ${colorBy(m.ready)}">${m.ready}% READY</span></div>${kpis(m)}<div class="v27-meter" style="margin-top:12px"><span style="width:${m.ready}%"></span></div></div>
    <div class="card"><div class="card-header">One-screen command shortcuts</div><div class="v27-grid">${action('🔎','Smart Search','Find claim, route, tool, or action instantly','v27-search')}${action('📱','Passenger Kiosk','Large-button public mode for phones at the port','v27-kiosk')}${action('⏱️','SLA Board','Prioritize claims and overdue work','v27-sla')}${action('🧑‍✈️','Shift Planner','Generate staff tasks for today','v27-shift')}${action('🛡️','Data Guardian','Backup, dedupe, compact, and diagnose','v27-guardian')}${action('🗺️','Map Intelligence','Open upgraded live map overlay','map')}</div></div>
    <div class="card"><div class="card-header">Live Recommendation Engine</div>${recommendations(m)}</div><div class="v27-spacer"></div>`}
  function recommendations(m){const rows=[];if(m.urgent.length)rows.push(['red','High-priority claims detected',m.urgent.length+' claim(s) need staff triage now.','v27-sla']);if(m.sync.length)rows.push(['amber','Pending offline queue',m.sync.length+' record(s) should be exported or synced.','sync']);if(m.st.pct>75)rows.push(['amber','Storage is getting high','Export backup and run duplicate cleanup.','v27-guardian']);if(!rows.length)rows.push(['green','Good operational state','No major local risk detected. Continue normal operations.','v27-kiosk']);return rows.map(r=>`<div class="v27-row"><div><strong>${esc(r[1])}</strong><small>${esc(r[2])}</small></div><button class="sm" onclick="showView('${r[3]}')">Open</button></div>`).join('')}

  function renderSearch(){ensureView('v27-search').innerHTML=`
    <div class="card v27-shell"><div class="v27-title"><div><h2>🔎 Smart Search + Action Launcher</h2><div class="v27-sub">Search claims, baggage tags, routes, notices, messages, and app tools from one mobile-friendly screen.</div></div><span class="v27-chip blue">COMMAND</span></div></div>
    <div class="v27-searchbox"><input id="v27SearchInput" placeholder="Type claim ID, baggage tag, route, fare, damage, backup..." oninput="v27RunSearch()"><div class="v27-tabbar"><button onclick="v27Quick('damage')">damage</button><button onclick="v27Quick('fare')">fare</button><button onclick="v27Quick('backup')">backup</button><button onclick="v27Quick('admin')">admin</button><button onclick="v27Quick('map')">map</button></div></div>
    <div class="card"><div class="card-header">Results</div><div id="v27SearchResults"><p class="muted">Start typing to search.</p></div></div><div class="v27-spacer"></div>`;setTimeout(()=>$('v27SearchInput')&&$('v27SearchInput').focus(),120)}
  window.v27Quick=function(q){const i=$('v27SearchInput');if(i){i.value=q;v27RunSearch()}}
  window.v27RunSearch=function(){const q=($('v27SearchInput')?.value||'').trim().toLowerCase();const box=$('v27SearchResults');if(!box)return;if(!q){box.innerHTML='<p class="muted">Start typing to search.</p>';return}const tools=[['calculator','🧮 Baggage Calculator','Official baggage fee calculator'],['fares','💵 Fares','Passenger fare table'],['schedules','🕐 Schedules','Trip schedule board'],['damage','🧳 Damage Detector','Capture damage evidence'],['claimstatus','🔎 Claim Status','Track claim number'],['map','🗺️ Live Map','Vessel and route map'],['v27-guardian','🛡️ Data Guardian','Backup and repair'],['admin','🔐 Admin Panel','Protected admin tools']];const rows=[];tools.forEach(t=>{if((t[1]+' '+t[2]+' '+t[0]).toLowerCase().includes(q))rows.push({type:'Tool',title:t[1],sub:t[2],view:t[0]})});allClaims().forEach(c=>{const text=JSON.stringify(c).toLowerCase();if(text.includes(q))rows.push({type:'Claim',title:claimId(c)+' • '+statusOf(c),sub:`${tagOf(c)||'No tag'} • ${routeOf(c)} • risk ${risk(c)}%`,view:'v27-sla'})});load(KEYS.notices,[]).forEach(n=>{const text=JSON.stringify(n).toLowerCase();if(text.includes(q))rows.push({type:'Notice',title:n.title||'Notice',sub:n.body||n.message||'',view:'noticeboard'})});box.innerHTML=rows.length?rows.slice(0,30).map(r=>`<div class="v27-row"><div><strong><span class="v27-chip">${esc(r.type)}</span> ${esc(r.title)}</strong><small>${esc(r.sub)}</small></div><button class="sm" onclick="showView('${r.view}')">Open</button></div>`).join(''):'<p class="muted">No local result found. Try route, claim ID, damage, fare, backup, or map.</p>'}

  function renderKiosk(){const p=prefs();ensureView('v27-kiosk').innerHTML=`
    <div class="card v27-shell"><div class="v27-title"><div><h2>📱 Passenger Kiosk Mode</h2><div class="v27-sub">Simple public interface for passengers. Large buttons, less clutter, and guided next steps.</div></div><span class="v27-chip pink">PUBLIC</span></div></div>
    <div class="card"><div class="card-header">Passenger needs</div><div class="v27-grid">${action('💵','Check Fare','See passenger fares by route','fares')}${action('🕐','Check Schedule','Find trip schedule','schedules')}${action('🧮','Baggage Fee','Use official baggage calculator','calculator')}${action('🧳','Report Damage','Open baggage damage workflow','damage')}${action('🔎','Track Claim','Check damage/lost baggage status','claimstatus')}${action('🗺️','Live Map','View routes and ETA board','map')}</div></div>
    <div class="card"><div class="card-header">Accessibility controls</div><div class="v27-grid"><button class="primary block" onclick="v27ToggleBig()">${p.big?'Normal Buttons':'Bigger Buttons'}</button><button class="accent block" onclick="v27ToggleFast()">${p.fast?'Disable Fast Mode':'Enable Fast Mode'}</button></div><p class="v27-privacy">Fast Mode reduces animations for low-end Android phones. Bigger Buttons make the site easier for elderly passengers and field staff.</p></div><div class="v27-spacer"></div>`}
  window.v27ToggleBig=function(){const p=prefs();p.big=!p.big;setPrefs(p);toast(p.big?'Bigger buttons enabled':'Normal button size');renderKiosk()}
  window.v27ToggleFast=function(){const p=prefs();p.fast=!p.fast;setPrefs(p);toast(p.fast?'Fast Mode enabled':'Fast Mode disabled');renderKiosk()}

  function renderSLA(){const cs=openClaims().sort((a,b)=>risk(b)-risk(a));ensureView('v27-sla').innerHTML=`
    <div class="card v27-shell"><div class="v27-title"><div><h2>⏱️ SLA + Priority Board</h2><div class="v27-sub">Ranks damage/lost baggage claims by risk, missing information, and status so staff can act faster.</div></div><span class="v27-chip ${cs.length?'amber':'green'}">${cs.length} OPEN</span></div></div>
    <div class="card"><div class="card-header">Triage Queue</div>${cs.length?cs.map(claimRow).join(''):'<p class="muted">No open claims found.</p>'}</div>
    <div class="card"><div class="card-header">Triage Rules</div><div class="v27-list"><div class="v27-soft">Critical keywords, missing tag, missing passenger name/contact, and New status increase priority.</div><button class="primary block" onclick="v27ExportSLA()">Export SLA Board CSV</button></div></div><div class="v27-spacer"></div>`}
  function claimRow(c){const r=risk(c);const cls=r>=70?'red':r>=50?'amber':'green';return `<div class="v27-row"><div><strong>${esc(claimId(c))} <span class="v27-chip ${cls}">${r}%</span></strong><small>${esc(statusOf(c))} • ${esc(routeOf(c))} • Tag: ${esc(tagOf(c)||'missing')}</small></div><div class="right"><button class="sm" onclick="v27SetClaimStatus('${esc(claimId(c))}','Under Review')">Review</button><button class="sm" onclick="v27SetClaimStatus('${esc(claimId(c))}','Resolved')">Resolve</button></div></div>`}
  window.v27SetClaimStatus=function(id,status){let changed=false;for(const k of [KEYS.claims,KEYS.damage]){const arr=load(k,[]);arr.forEach(c=>{if(claimId(c)===id){c.status=status;c.v27UpdatedAt=now();changed=true}});save(k,arr)}toast(changed?'Status updated':'Claim not found');renderSLA()}
  window.v27ExportSLA=function(){const rows=[['id','status','route','tag','risk']].concat(openClaims().map(c=>[claimId(c),statusOf(c),routeOf(c),tagOf(c),risk(c)]));download(rows.map(r=>r.map(csv).join(',')).join('\n'),'text/csv','oceanjet_v27_sla_board_'+today()+'.csv')}

  function renderShift(){const m=metrics();const saved=load(KEYS.shifts,[]);ensureView('v27-shift').innerHTML=`
    <div class="card v27-shell"><div class="v27-title"><div><h2>🧑‍✈️ Shift Planner</h2><div class="v27-sub">Generates realistic staff tasks based on open claims, storage risk, sync queue, and public service needs.</div></div><span class="v27-chip blue">STAFF</span></div></div>
    <div class="card"><div class="card-header">Generate Today’s Plan</div><div class="grid2"><div class="input-group"><label>Shift</label><select id="v27Shift"><option>Morning</option><option>Midday</option><option>Evening</option><option>Night</option></select></div><div class="input-group"><label>Available Staff</label><input id="v27StaffCount" type="number" min="1" max="20" value="3"></div></div><button class="primary block" onclick="v27GenerateShift()">Generate Smart Shift Plan</button></div>
    <div class="card"><div class="card-header">Recommended Workload Now</div>${shiftTasks(m).map(t=>`<div class="v27-row"><div><strong>${esc(t.title)}</strong><small>${esc(t.detail)}</small></div><span class="v27-chip ${t.color}">${esc(t.owner)}</span></div>`).join('')}</div>
    <div class="card"><div class="card-header">Saved Plans</div>${saved.length?saved.slice(0,5).map(s=>`<div class="v27-row"><div><strong>${esc(s.id)} • ${esc(s.shift)}</strong><small>${esc(s.createdAt)} • ${s.tasks.length} task(s)</small></div><button class="sm" onclick="v27ExportShift('${s.id}')">Export</button></div>`).join(''):'<p class="muted">No saved shift plan yet.</p>'}</div><div class="v27-spacer"></div>`}
  function shiftTasks(m){const rows=[];rows.push({title:'Open passenger counter readiness',detail:'Verify calculator, fares, schedules, claim status, and kiosk mode before peak boarding.',owner:'Counter',color:'green'});if(m.urgent.length)rows.push({title:'Triage urgent baggage claims',detail:m.urgent.length+' claim(s) need review, missing data checks, or supervisor escalation.',owner:'Baggage',color:'red'});if(m.sync.length)rows.push({title:'Export pending sync queue',detail:'Download queue backup before changing devices or clearing browser data.',owner:'Supervisor',color:'amber'});if(m.st.pct>70)rows.push({title:'Storage protection task',detail:'Run Data Guardian backup and duplicate cleanup; current storage '+m.st.mb.toFixed(2)+'MB.',owner:'Admin',color:'amber'});rows.push({title:'Passenger notice check',detail:'Update public route/port advisories if schedules or gates changed.',owner:'Info',color:'blue'});return rows}
  window.v27GenerateShift=function(){const m=metrics();const item={id:uid('SHIFT'),shift:$('v27Shift')?.value||'Morning',staff:Number($('v27StaffCount')?.value||3),createdAt:now(),tasks:shiftTasks(m)};const rows=load(KEYS.shifts,[]);rows.unshift(item);save(KEYS.shifts,rows.slice(0,40));toast('Shift plan generated');renderShift()}
  window.v27ExportShift=function(id){const s=load(KEYS.shifts,[]).find(x=>x.id===id);if(!s)return;download(JSON.stringify(s,null,2),'application/json','oceanjet_shift_plan_'+id+'.json')}

  function renderGuardian(){const m=metrics();const p=prefs();ensureView('v27-guardian').innerHTML=`
    <div class="card v27-shell"><div class="v27-title"><div><h2>🛡️ Data Guardian + Site Reliability</h2><div class="v27-sub">Protects local browser data, checks health, exports backups, and helps prevent blank-screen recovery problems.</div></div><span class="v27-chip ${m.st.pct>80?'red':m.st.pct>65?'amber':'green'}">${m.st.pct}% STORAGE</span></div><div class="v27-meter" style="margin-top:12px"><span style="width:${m.st.pct}%"></span></div></div>
    <div class="card"><div class="card-header">Guardian Actions</div><div class="v27-grid">${guardianBtn('💾','Full Snapshot','Export all major local datasets','v27Snapshot()')}${guardianBtn('🧹','Dedupe Claims','Find duplicate claim IDs/tags','v27DedupeClaims()')}${guardianBtn('📦','Compact Logs','Trim oversized audit/message lists','v27CompactData()')}${guardianBtn('🧪','Run Site Test','Open deployment test center','showView(\'site-test\')')}${guardianBtn('⚡','Fast Mode','Toggle low-end Android mode','v27ToggleFastGlobal()')}${guardianBtn('🔐','Admin Notice','Protected notice/content composer','v27AdminNotice()')}</div></div>
    <div class="card"><div class="card-header">Storage Details</div>${m.st.rows.slice(0,8).map(x=>`<div class="v27-row"><div><strong>${esc(x.k)}</strong><small>${(x.b/1024).toFixed(1)} KB</small></div></div>`).join('')||'<p class="muted">No storage details found.</p>'}</div>
    <div class="card"><div class="card-header">Current Mode</div><div class="v27-row"><div><strong>Fast Mode: ${p.fast?'ON':'OFF'}</strong><small>Big Buttons: ${p.big?'ON':'OFF'} • Last snapshot: ${esc(p.lastSnapshot||'none')}</small></div></div></div><div class="v27-spacer"></div>`}
  function guardianBtn(ico,t,s,fn){return `<button class="v27-action" onclick="${fn}"><span class="ico">${ico}</span><b>${esc(t)}</b><small>${esc(s)}</small></button>`}
  window.v27ToggleFastGlobal=function(){const p=prefs();p.fast=!p.fast;setPrefs(p);toast(p.fast?'Fast Mode on':'Fast Mode off');renderGuardian()}
  window.v27Snapshot=function(){const data={version:VERSION,exportedAt:now(),claims:load(KEYS.claims,[]),damage:load(KEYS.damage,[]),sync:load(KEYS.sync,[]),messages:load(KEYS.messages,[]),journeys:load(KEYS.journeys,[]),notices:load(KEYS.notices,[]),tickets:load(KEYS.tickets,[]),feedback:load(KEYS.feedback,[]),shifts:load(KEYS.shifts,[]),audit:load(KEYS.audit,[]),prefs:prefs()};download(JSON.stringify(data,null,2),'application/json','oceanjet_v27_full_snapshot_'+today()+'.json');const p=prefs();p.lastSnapshot=now();setPrefs(p);audit('snapshot','V27 full snapshot exported');renderGuardian()}
  window.v27DedupeClaims=function(){let removed=0;for(const k of [KEYS.claims,KEYS.damage]){const arr=load(k,[]);const seen=new Set();const out=[];for(const c of arr){const key=(claimId(c)+'|'+tagOf(c)).toLowerCase();if(seen.has(key)){removed++;continue}seen.add(key);out.push(c)}save(k,out)}toast(removed?removed+' duplicate record(s) removed':'No duplicates found');renderGuardian()}
  window.v27CompactData=function(){const cuts=[[KEYS.audit,150],[KEYS.messages,120],[KEYS.sync,180],[KEYS.journeys,120],[KEYS.tickets,160],[KEYS.feedback,160]];cuts.forEach(([k,n])=>{const a=load(k,[]);if(Array.isArray(a)&&a.length>n)save(k,a.slice(0,n))});toast('Local logs compacted safely');renderGuardian()}
  window.v27AdminNotice=function(){if(!isAdmin()){showAdminGate();return}showNoticeComposer()}
  function showAdminGate(){ensureView('v27-guardian').innerHTML=`<div class="card v27-shell"><div class="v27-title"><div><h2>🔐 Admin Required</h2><div class="v27-sub">Public users can use the app, but publishing content remains protected.</div></div><span class="v27-chip red">LOCKED</span></div></div><div class="card"><div class="grid2"><div class="input-group"><label>Username</label><input id="v27AdminU" placeholder="admin"></div><div class="input-group"><label>Password</label><input id="v27AdminP" type="password" placeholder="admin"></div></div><button class="primary block" onclick="v27TryAdmin()">Unlock Admin Content Tools</button><button class="block" onclick="renderGuardian()">Back</button></div>`}
  window.v27TryAdmin=function(){if(unlockAdmin($('v27AdminU')?.value||'', $('v27AdminP')?.value||'')){toast('Admin unlocked');showNoticeComposer()}else toast('Invalid admin login')}
  function showNoticeComposer(){const c=load(KEYS.content,{});ensureView('v27-guardian').innerHTML=`<div class="card v27-shell"><div class="v27-title"><div><h2>📢 Admin Content Composer</h2><div class="v27-sub">Update local public instructions without editing code.</div></div><span class="v27-chip green">UNLOCKED</span></div></div><div class="card"><div class="input-group"><label>Passenger Help</label><textarea id="v27Help" rows="3">${esc(c.passengerHelp||'Keep ticket, PSN, and baggage tag ready.')}</textarea></div><div class="input-group"><label>Port Notice</label><textarea id="v27Notice" rows="3">${esc(c.portNotice||'Check route and gate before boarding.')}</textarea></div><button class="primary block" onclick="v27SaveContent()">Save Content</button><button class="block" onclick="renderGuardian()">Back to Guardian</button></div>`}
  window.v27SaveContent=function(){const c=load(KEYS.content,{});c.passengerHelp=$('v27Help')?.value||'';c.portNotice=$('v27Notice')?.value||'';save(KEYS.content,c);toast('Content saved locally');renderGuardian()}

  function renderMapIntel(){const v=ensureView('v27-mapintel');const m=metrics();v.innerHTML=`
    <div class="card v27-shell"><div class="v27-title"><div><h2>🗺️ V27 Live Map Intelligence</h2><div class="v27-sub">Mobile-friendly simulated route intelligence overlay. Works offline as a visual operations board.</div></div><span class="v27-chip ${navigator.onLine?'green':'amber'}">${navigator.onLine?'ONLINE':'OFFLINE'}</span></div></div>
    <div class="card"><div class="v27-map">${mapLayer()}</div></div>
    <div class="card"><div class="card-header">Route Intelligence</div>${routes().map((r,i)=>routeIntelRow(r,i,m)).join('')}</div><div class="v27-spacer"></div>`}
  function mapLayer(){const ports=[['CEB',14,48],['TAG',48,67],['ORM',38,35],['DUM',67,76],['SRG',82,26],['GET',31,58],['MSN',69,31],['SIQ',57,82]];const lines=[[16,49,47,66,24],[16,48,39,36,-24],[69,32,81,27,-18],[49,67,66,76,14],[69,76,58,82,-18],[16,48,31,58,18]];return lines.map(l=>`<div class="v27-route-line" style="left:${l[0]}%;top:${l[1]}%;width:${Math.hypot(l[2]-l[0],l[3]-l[1])*3.1}%;transform:rotate(${l[4]}deg)"></div>`).join('')+ports.map(p=>`<div class="v27-port" style="left:${p[1]}%;top:${p[2]}%">${p[0]}</div>`).join('')+routes().slice(0,6).map((r,i)=>`<div class="v27-vessel" style="left:${18+i*11}%;top:${42+(i%3)*12}%">${i+1}</div>`).join('')}
  function routeIntelRow(r,i,m){const load=(42+(i*11+m.oc.length*3))%96;const riskv=(18+(i*9+m.urgent.length*12))%100;const eta=25+i*9+(m.sync.length%5);return `<div class="v27-row"><div><strong>${esc(routeLabel(r))}</strong><small>ETA ${eta} min • Passenger load ${load}% • Risk ${riskv}%</small><div class="v27-meter" style="margin-top:7px"><span style="width:${riskv}%"></span></div></div><span class="v27-chip ${riskv>70?'red':riskv>45?'amber':'green'}">${riskv>70?'WATCH':riskv>45?'BUSY':'OK'}</span></div>`}

  function renderV27View(name){if(name==='v27-nexus')renderNexus();else if(name==='v27-search')renderSearch();else if(name==='v27-kiosk')renderKiosk();else if(name==='v27-sla')renderSLA();else if(name==='v27-shift')renderShift();else if(name==='v27-guardian')renderGuardian();else if(name==='v27-mapintel')renderMapIntel();}
  function patchDrawer(){const menu=$('drawerMenu');if(!menu)return;const items=[['v27-nexus','🚀','V27 Nexus'],['v27-search','🔎','Smart Search'],['v27-kiosk','📱','Passenger Kiosk'],['v27-sla','⏱️','SLA Board'],['v27-shift','🧑‍✈️','Shift Planner'],['v27-guardian','🛡️','Data Guardian']];for(let i=items.length-1;i>=0;i--){const [view,icon,label]=items[i];if(!menu.querySelector(`.drawer-item[data-view="${view}"]`)){const d=document.createElement('div');d.className='drawer-item';d.dataset.view=view;d.setAttribute('onclick',`navigate('${view}')`);d.innerHTML=`<i>${icon}</i> ${label}`;menu.insertBefore(d,menu.firstChild)}}}
  function patchNav(){const views=['v27-nexus','v27-search','v27-kiosk','v27-sla','v27-shift','v27-guardian','v27-mapintel'];const old=window.showView;if(old&&!old.__v27Major){window.showView=function(name){if(views.includes(name)){qsa('.view').forEach(v=>v.classList.remove('active'));ensureView(name).classList.add('active');renderV27View(name);qsa('#drawerMenu .drawer-item').forEach(el=>el.classList.toggle('active',el.dataset.view===name));try{window.scrollTo({top:0,behavior:prefs().fast?'auto':'smooth'})}catch(e){window.scrollTo(0,0)}return}const r=old.apply(this,arguments);setTimeout(()=>{patchDrawer();if(name==='dashboard')patchDashboard();if(name==='map')patchMap();},160);return r};try{showView=window.showView}catch(e){}window.showView.__v27Major=true}
    const oldBuild=window.buildDrawerMenu;if(oldBuild&&!oldBuild.__v27Major){window.buildDrawerMenu=function(){const r=oldBuild.apply(this,arguments);patchDrawer();return r};try{buildDrawerMenu=window.buildDrawerMenu}catch(e){}window.buildDrawerMenu.__v27Major=true}}
  function patchDashboard(){const v=$('view-dashboard');if(!v||$('v27DashCard'))return;const m=metrics();v.insertAdjacentHTML('afterbegin',`<div id="v27DashCard" class="card v27-shell"><div class="v27-title"><div><h2>🚀 V27 Major Command Upgrade</h2><div class="v27-sub">Nexus, smart search, kiosk mode, SLA board, shift planner, data guardian, and map intelligence are active.</div></div><span class="v27-chip ${colorBy(m.ready)}">${m.ready}% READY</span></div><div class="v27-grid" style="margin-top:12px">${action('🚀','Open Nexus','Main V27 command screen','v27-nexus')}${action('🔎','Search','Find tool, claim, route','v27-search')}${action('📱','Kiosk','Passenger simple mode','v27-kiosk')}${action('🛡️','Guardian','Backup and repair','v27-guardian')}</div></div>`)}
  function patchMap(){const v=$('view-map');if(!v||$('v27MapEnhance'))return;v.insertAdjacentHTML('afterbegin',`<div id="v27MapEnhance" class="card v27-shell"><div class="v27-title"><div><h2>🗺️ V27 Map Intelligence Overlay</h2><div class="v27-sub">Open the offline-ready command map with route risk, simulated ETA, and port pressure indicators.</div></div><button class="sm primary" onclick="showView('v27-mapintel')">Open</button></div></div>`)}
  function download(data,type,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),900)}
  function csv(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
  function boot(){try{document.body.classList.add('oj-v27-mobile');setPrefs(prefs());['v27-nexus','v27-search','v27-kiosk','v27-sla','v27-shift','v27-guardian','v27-mapintel'].forEach(ensureView);patchNav();if(typeof window.buildDrawerMenu==='function')window.buildDrawerMenu();patchDrawer();setTimeout(()=>{patchDashboard();patchMap()},700);window.addEventListener('online',()=>audit('network','online'));window.addEventListener('offline',()=>audit('network','offline'));audit('boot',VERSION+' loaded');console.log(VERSION+' loaded')}catch(e){console.error('V27 boot error',e);audit('boot_error',e.message);toast('V27 recovery: '+e.message)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
