
(function(){
  if(window.__OCEANJET_V30_REAL__) return;
  window.__OCEANJET_V30_REAL__ = true;
  const VERSION='V30 Service SuperApp OS';
  const VIEWS=['v30-os','v30-care','v30-claim','v30-sync','v30-admin'];
  const KEYS={tickets:'oj_v30_service_tickets',audit:'oj_v30_audit',prefs:'oj_v30_prefs',outbox:'oj_v30_outbox',config:'oj_v30_cloud_config',kb:'oj_v30_kb',snap:'oj_v30_snapshots'};
  const ROUTES=['cebu_tagbilaran','cebu_maasin','cebu_surigao','cebu_siquijor','cebu_dumaguete','cebu_ormoc','cebu_palompon','cebu_getafe'];
  const ROLE_LANES=[
    ['Passenger','Check route, claim status, help guide','showView("v30-care")','👤'],
    ['Baggage Staff','Create claim packet, triage queue','showView("v30-claim")','🧳'],
    ['Cashier','Open original baggage calculator','showView("calc")','💳'],
    ['Supervisor','Open protected admin console','showView("v30-admin")','🛡️']
  ];
  const $=id=>document.getElementById(id);
  const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const app=()=>document.querySelector('.app')||document.body;
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function load(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(e){return f}}
  function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){tip('Storage full. Export backup.');return false}}
  function now(){return new Date().toLocaleString('en-PH',{timeZone:'Asia/Manila',hour12:true})}
  function uid(p){return p+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
  function tip(msg){if(typeof window.toast==='function') try{return window.toast(msg)}catch(e){} const d=document.createElement('div');d.textContent=msg;d.style.cssText='position:fixed;top:14px;left:50%;transform:translateX(-50%);z-index:999999;background:#ff4fb8;color:white;padding:10px 14px;border-radius:999px;font-weight:900;box-shadow:0 8px 28px rgba(0,0,0,.35)';document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
  function audit(type,msg){const a=load(KEYS.audit,[]);a.unshift({at:now(),type,msg:String(msg||'')});save(KEYS.audit,a.slice(0,180))}
  function storage(){let size=0;try{for(let k in localStorage){if(Object.prototype.hasOwnProperty.call(localStorage,k)) size+=localStorage.getItem(k).length+k.length}}catch(e){} const mb=size*2/1024/1024;return {bytes:size*2,mb,pct:Math.min(99,Math.round(mb/5*100))}}
  function routeLabel(r){return String(r||'').replace('cebu_','Cebu → ').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
  function adminOK(){return sessionStorage.getItem('oj_v22_admin_unlocked')==='1'||localStorage.getItem('oj_v22_admin_unlocked')==='1'}
  function prefs(){return load(KEYS.prefs,{large:false,fast:false,kiosk:'auto'})}
  function setPrefs(p){save(KEYS.prefs,p);document.body.classList.toggle('v30-large-touch',!!p.large);document.body.classList.toggle('v30-fast',!!p.fast)}
  function tickets(){return load(KEYS.tickets,[])}
  function oldClaims(){let out=[];['oj_v22_claims','oj_v23_claims','oj_v24_tickets','oj_v25_queue','oj_v26_interactions','oj_v27_claims','oj_v29_claims'].forEach(k=>{const v=load(k,[]);if(Array.isArray(v))out=out.concat(v)});return out}
  function damages(){return load('oj_damage_master_log_v11',[])}
  function outbox(){return load(KEYS.outbox,[])}
  function metrics(){const t=tickets(), oc=oldClaims(), dm=damages(), ob=outbox(), st=storage(), aud=load(KEYS.audit,[]); const open=t.filter(x=>!['Closed','Resolved','Rejected','Synced'].includes(x.status)); const urgent=t.filter(x=>x.priority>=75||String(x.issue).match(/lost|critical|wet|broken|crack/i)); const ready=Math.max(18,Math.min(99,100-Math.round(st.pct*.18)-Math.min(18,ob.length*2)+Math.min(10,aud.length?8:0))); return {t,oc,dm,ob,st,aud,open,urgent,ready,total:t.length+oc.length+dm.length}}
  function ensureView(name){let v=$('view-'+name);if(!v){v=document.createElement('div');v.id='view-'+name;v.className='view';app().appendChild(v)}return v}
  function activate(name){qsa('.view').forEach(v=>v.classList.remove('active'));ensureView(name).classList.add('active');qsa('#drawerMenu .drawer-item').forEach(el=>el.classList.toggle('active',el.dataset.view===name));try{window.scrollTo({top:0,behavior:prefs().fast?'auto':'smooth'})}catch(e){window.scrollTo(0,0)}}
  function kpis(m){return `<div class="v30-grid"><div class="v30-kpi"><div><b>${m.ready}%</b><span>Site Readiness</span></div></div><div class="v30-kpi"><div><b>${m.open.length}</b><span>Open Tickets</span></div></div><div class="v30-kpi"><div><b>${m.urgent.length}</b><span>Priority</span></div></div><div class="v30-kpi"><div><b>${m.st.mb.toFixed(2)}MB</b><span>Local Storage</span></div></div></div>`}
  function action(ico,title,sub,fn,cls=''){return `<button class="v30-action ${cls}" onclick="${fn}"><span class="ico">${ico}</span><b>${esc(title)}</b><small>${esc(sub)}</small></button>`}
  function statusChip(s){const x=String(s||'New');const cls=/closed|resolved|synced/i.test(x)?'green':/urgent|critical|pending|review/i.test(x)?'amber':/reject|fail/i.test(x)?'red':'blue';return `<span class="v30-chip ${cls}">${esc(x)}</span>`}
  function priority(n){return n>=80?'red':n>=60?'amber':'green'}
  function qr(text){let h=0;for(let i=0;i<String(text).length;i++){h=((h<<5)-h)+String(text).charCodeAt(i);h|=0}let cells='';for(let i=0;i<81;i++){const on=((Math.abs(h)+i*17+i*i)%7)<3||[0,1,2,9,18,10,11,19,20,60,61,62,69,70,71,78,79,80].includes(i);cells+=`<i class="${on?'':'off'}"></i>`}return `<div class="v30-qr" aria-label="QR style receipt">${cells}</div>`}
  function download(content,type,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},250)}
  function renderOS(){const m=metrics();ensureView('v30-os').innerHTML=`
    <div class="card v30-shell"><div class="v30-title"><div><h1>🚢 V30 Service SuperApp OS</h1><div class="v30-sub">A mobile-first command layer for passengers, baggage staff, cashier workflows, claim automation, offline sync, and admin diagnostics. It keeps the original baggage calculator and damage detector intact.</div></div><span class="v30-chip green">REAL BUILD</span></div>${kpis(m)}<div class="v30-command-strip"><button class="primary" onclick="showView('v30-care')">Passenger Care</button><button class="accent" onclick="showView('v30-claim')">Claim Automation</button><button onclick="showView('v30-sync')">Sync Bridge</button><button onclick="showView('calc')">Baggage Calc</button></div></div>
    <div class="v30-hero"><span class="v30-orb" style="left:12%;top:24%"></span><span class="v30-orb o2" style="left:44%;top:60%"></span><span class="v30-orb o3" style="left:72%;top:38%"></span><div class="v30-hero-content"><div class="v30-title"><div><h2>Smart Site Launcher</h2><div class="v30-sub">Search or tap a role. Example: damage, fare, lost baggage, export, map, admin.</div></div><span class="v30-chip blue">MOBILE</span></div><div class="v30-search"><input id="v30Search" placeholder="What do you need to do?" onkeydown="if(event.key==='Enter')v30LaunchSearch()"><button class="primary" onclick="v30LaunchSearch()">Launch</button></div><div id="v30SearchResult" class="v30-soft">Ready for quick action.</div></div></div>
    <div class="card"><div class="card-header">Role lanes</div><div class="v30-grid">${ROLE_LANES.map(r=>action(r[3],r[0],r[1],r[2])).join('')}</div></div>
    <div class="card"><div class="card-header">Today’s service pulse</div>${pulseRows(m)}</div><div class="v30-spacer"></div>`}
  function pulseRows(m){const rows=[['Passenger flow',m.open.length?'Active requests need attention':'No new V30 tickets yet',m.open.length?'amber':'green'],['Damage evidence',`${m.dm.length} local damage record(s) detected`,m.dm.length?'blue':'amber'],['Offline sync',`${m.ob.length} queued item(s) pending`,m.ob.length?'amber':'green'],['Storage health',`${m.st.mb.toFixed(2)} MB used`,m.st.pct>70?'red':m.st.pct>45?'amber':'green']];return rows.map(r=>`<div class="v30-row"><div><strong>${r[0]}</strong><small>${r[1]}</small></div><span class="v30-chip ${r[2]}">${r[2]}</span></div>`).join('')}
  window.v30LaunchSearch=function(){const q=($('v30Search')?.value||'').toLowerCase();let action='showView("v30-os")',label='Open V30 Service OS'; if(/damage|claim|lost|bag|baggage|stub/.test(q)){action='showView("v30-claim")';label='Open Claim Automation'} else if(/fare|calc|cashier|kilo|kg/.test(q)){action='showView("calc")';label='Open Baggage Calculator'} else if(/schedule|route|passenger|help|status|journey/.test(q)){action='showView("v30-care")';label='Open Passenger Care'} else if(/map|fleet|vessel|eta/.test(q)){action='showView("map")';label='Open Live Map'} else if(/export|backup|sync|offline/.test(q)){action='showView("v30-sync")';label='Open Sync Bridge'} else if(/admin|privacy|security|config/.test(q)){action='showView("v30-admin")';label='Open Admin Console'} $('v30SearchResult').innerHTML=`<b>${esc(label)}</b><br><button class="primary block" onclick='${action}'>Continue</button>`;audit('search',q+' -> '+label)};
  function renderCare(){const m=metrics();ensureView('v30-care').innerHTML=`
    <div class="card v30-shell"><div class="v30-title"><div><h2>👤 Passenger Care Studio</h2><div class="v30-sub">Guides passengers to the correct next step: route help, claim status, lost baggage, damage report, or port assistance.</div></div><span class="v30-chip pink">PUBLIC</span></div>${kpis(m)}</div>
    <div class="card"><div class="card-header">Build passenger next-step guide</div><div class="grid2"><div class="input-group"><label>Passenger need</label><select id="v30Need"><option>Check baggage damage claim</option><option>Report lost baggage</option><option>Report damaged baggage</option><option>Check route or fare</option><option>Ask port assistance</option></select></div><div class="input-group"><label>Route</label><select id="v30Route">${ROUTES.map(r=>`<option value="${r}">${routeLabel(r)}</option>`).join('')}</select></div></div><div class="grid2"><div class="input-group"><label>Claim or tag number optional</label><input id="v30Lookup" placeholder="OJ-DMG / tag / PSN"></div><div class="input-group"><label>Passenger mobile optional</label><input id="v30Mobile" placeholder="09xx"></div></div><button class="primary block" onclick="v30BuildGuide()">Generate guide</button><div id="v30Guide" class="v30-soft">No guide generated yet.</div></div>
    <div class="card"><div class="card-header">Claim status quick lookup</div><div class="v30-search"><input id="v30ClaimLookup" placeholder="Enter claim ID or baggage tag"><button class="accent" onclick="v30LookupClaim()">Check</button></div><div id="v30ClaimResult" class="v30-soft">Waiting for claim number.</div></div>
    <div class="card"><div class="card-header">Passenger-friendly shortcuts</div><div class="v30-grid">${action('🧮','Fare and baggage fees','Open official calculator','showView("calc")')}${action('📅','Schedules','Open schedules tab','showView("schedules")')}${action('🧳','Damage report','Create claim packet','showView("v30-claim")')}${action('📣','Notices','Open public notice board','showView("noticeboard")')}</div></div><div class="v30-spacer"></div>`}
  window.v30BuildGuide=function(){const need=$('v30Need').value,route=$('v30Route').value,lookup=$('v30Lookup').value.trim(),mobile=$('v30Mobile').value.trim();const steps=[];if(/damage/i.test(need)){steps.push('Take photo of claim stub or baggage tag.','Take full baggage photo and close-up damage photo.','Proceed to Baggage Damage Detector or staff counter.','Keep claim number for follow-up.')}else if(/lost/i.test(need)){steps.push('Record route, vessel, travel date, and baggage tag.','Submit lost baggage ticket.','Staff checks loading/unloading records.','Passenger receives claim number.')}else if(/fare|route/i.test(need)){steps.push('Open official route/fare tool.','Choose route and passenger type.','For baggage fee, use Baggage Calc tab only.')}else{steps.push('Go to nearest OceanJet counter.','Prepare PSN or ticket details.','Staff logs request and updates status.')}const id=lookup||uid('OJ-HELP');$('v30Guide').innerHTML=`<div class="v30-receipt"><b>Passenger Guide: ${esc(id)}</b><br>Need: ${esc(need)}<br>Route: ${routeLabel(route)}<br>Mobile: ${esc(mobile||'not provided')}${qr(id)}<div class="v30-flow">${steps.map((s,i)=>`<div class="v30-step" data-n="${i+1}"><b>${esc(s)}</b></div>`).join('')}</div></div>`;audit('guide',need+' '+id)};
  window.v30LookupClaim=function(){const q=($('v30ClaimLookup').value||'').toLowerCase().trim();if(!q){$('v30ClaimResult').textContent='Please enter a claim ID or tag.';return}const all=tickets().concat(oldClaims()).concat(damages());const hit=all.find(c=>String(c.claimId||c.caseId||c.ticketId||c.id||c.tagNo||c.tag||'').toLowerCase().includes(q)||JSON.stringify(c).toLowerCase().includes(q));$('v30ClaimResult').innerHTML=hit?`<b>Record found:</b><br>${esc(hit.claimId||hit.caseId||hit.ticketId||hit.id||'Local Record')}<br>Status: ${statusChip(hit.status||'Under Review')}<br><small>${esc(hit.destination||hit.route||hit.damageType||hit.issue||'Open local record')}</small>`:'No local record found on this device. Ask staff to check the master device/export.';audit('lookup',q)};
  function renderClaim(){const m=metrics();const t=tickets();ensureView('v30-claim').innerHTML=`
    <div class="card v30-shell"><div class="v30-title"><div><h2>🧳 Claim Automation Studio</h2><div class="v30-sub">Creates structured damage/lost baggage packets, QR-style receipts, priority scoring, and offline sync entries.</div></div><span class="v30-chip amber">STAFF READY</span></div>${kpis(m)}</div>
    <div class="card"><div class="card-header">Create claim packet</div><div class="grid2"><div class="input-group"><label>Claim type</label><select id="v30ClaimType"><option>Damaged baggage</option><option>Lost baggage</option><option>Missing item</option><option>Wet baggage</option><option>Broken handle/wheel</option><option>Passenger assistance</option></select></div><div class="input-group"><label>Route</label><select id="v30ClaimRoute">${ROUTES.map(r=>`<option value="${r}">${routeLabel(r)}</option>`).join('')}</select></div></div><div class="grid2"><div class="input-group"><label>Tag / PSN / Ticket</label><input id="v30ClaimTag" placeholder="Baggage tag or PSN"></div><div class="input-group"><label>Passenger last name optional</label><input id="v30ClaimName" placeholder="Last name"></div></div><div class="grid2"><div class="input-group"><label>Severity</label><select id="v30ClaimSeverity"><option>Minor</option><option>Moderate</option><option>Critical</option></select></div><div class="input-group"><label>Photo evidence</label><select id="v30ClaimEvidence"><option>Complete: stub + full bag + damage close-up</option><option>Partial: needs more photos</option><option>No photo yet</option></select></div></div><div class="input-group"><label>Notes</label><textarea id="v30ClaimNotes" rows="3" placeholder="Short incident description"></textarea></div><button class="primary block" onclick="v30CreateClaim()">Create Claim Packet</button><div id="v30NewClaim" class="v30-soft">No new packet yet.</div></div>
    <div class="card"><div class="card-header">Smart local claim queue</div><div class="v30-table"><table><thead><tr><th>Claim</th><th>Route</th><th>Issue</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>${t.map(c=>`<tr><td>${esc(c.claimId)}</td><td>${routeLabel(c.route)}</td><td>${esc(c.issue)}</td><td><span class="v30-chip ${priority(c.priority)}">${c.priority}</span></td><td>${statusChip(c.status)}</td><td><button class="sm" onclick="v30NextStatus('${c.claimId}')">Next</button></td></tr>`).join('')||'<tr><td colspan="6">No V30 tickets yet.</td></tr>'}</tbody></table></div></div>
    <div class="card"><div class="card-header">Evidence checklist</div><div class="v30-flow"><div class="v30-step" data-n="1"><b>Claim stub/tag photo</b><br><small>Required for identity verification.</small></div><div class="v30-step" data-n="2"><b>Full baggage view</b><br><small>Shows size, color, baggage type, and condition.</small></div><div class="v30-step" data-n="3"><b>Damage close-up</b><br><small>Shows crack, wheel, handle, wet damage, etc.</small></div><div class="v30-step" data-n="4"><b>Passenger confirmation</b><br><small>Confirm contact, claim ID, route, and status.</small></div></div></div><div class="v30-spacer"></div>`}
  window.v30CreateClaim=function(){const c={claimId:uid('OJ-V30'),createdAt:now(),issue:$('v30ClaimType').value,route:$('v30ClaimRoute').value,tag:$('v30ClaimTag').value.trim(),name:$('v30ClaimName').value.trim(),severity:$('v30ClaimSeverity').value,evidence:$('v30ClaimEvidence').value,notes:$('v30ClaimNotes').value.trim(),status:'Submitted',priority:0};c.priority=(/critical/i.test(c.severity)?88:/moderate/i.test(c.severity)?62:38)+(c.evidence.includes('No')?12:c.evidence.includes('Partial')?8:0)+(/lost|wet|broken/i.test(c.issue)?10:0);const list=tickets();list.unshift(c);save(KEYS.tickets,list);const ob=outbox();ob.unshift({id:uid('SYNC'),type:'claim',status:'pending',createdAt:now(),payload:c});save(KEYS.outbox,ob);$('v30NewClaim').innerHTML=`<div class="v30-receipt"><b>${c.claimId}</b><br>${esc(c.issue)} • ${routeLabel(c.route)}<br>Priority: ${c.priority}${qr(c.claimId)}<button class="accent block" onclick="v30PrintClaim('${c.claimId}')">Open receipt</button></div>`;audit('claim_create',c.claimId);tip('Claim packet created.');renderClaim()};
  window.v30PrintClaim=function(id){const c=tickets().find(x=>x.claimId===id);if(!c)return;const w=window.open('','_blank');if(!w){tip('Pop-up blocked. Receipt shown in page.');return}w.document.write(`<html><head><title>${esc(id)}</title><style>body{font-family:Arial;padding:18px} .box{border:1px solid #111;padding:14px;border-radius:12px} small{color:#555}</style></head><body><div class="box"><h2>OceanJet Claim Receipt</h2><b>${esc(c.claimId)}</b><p>${esc(c.issue)}<br>${routeLabel(c.route)}<br>Status: ${esc(c.status)}<br>Created: ${esc(c.createdAt)}</p><small>Keep this claim number for follow-up.</small></div></body></html>`);w.document.close();};
  window.v30NextStatus=function(id){const order=['Submitted','Under Review','Need Evidence','Approved','Processing','Closed'];const list=tickets();const c=list.find(x=>x.claimId===id);if(!c)return;let i=order.indexOf(c.status);c.status=order[(i+1)%order.length];c.updatedAt=now();save(KEYS.tickets,list);audit('claim_status',id+' -> '+c.status);renderClaim();tip('Status updated.');};
  function renderSync(){const m=metrics(), cfg=load(KEYS.config,{mode:'local-only',endpoint:'',provider:'None'});ensureView('v30-sync').innerHTML=`
    <div class="card v30-shell"><div class="v30-title"><div><h2>☁️ Offline Sync Bridge</h2><div class="v30-sub">Prepares the static GitHub Pages app for future Firebase/Supabase/API sync without requiring it today. Current mode stays local-first and offline-safe.</div></div><span class="v30-chip ${navigator.onLine?'green':'red'}">${navigator.onLine?'ONLINE':'OFFLINE'}</span></div>${kpis(m)}</div>
    <div class="card"><div class="card-header">Sync status</div><div class="v30-row"><div><strong>Mode</strong><small>${esc(cfg.mode)} • Provider: ${esc(cfg.provider)}</small></div><span class="v30-chip blue">CONFIG</span></div><div class="v30-row"><div><strong>Outbox</strong><small>${m.ob.length} pending local item(s)</small></div><span class="v30-chip ${m.ob.length?'amber':'green'}">${m.ob.length?'PENDING':'CLEAR'}</span></div><div class="v30-meter"><span style="width:${Math.min(100,m.ob.length*18)}%"></span></div></div>
    <div class="card"><div class="card-header">Cloud readiness settings</div><div class="grid2"><div class="input-group"><label>Provider</label><select id="v30Provider"><option ${cfg.provider==='None'?'selected':''}>None</option><option ${cfg.provider==='Firebase'?'selected':''}>Firebase</option><option ${cfg.provider==='Supabase'?'selected':''}>Supabase</option><option ${cfg.provider==='Custom API'?'selected':''}>Custom API</option></select></div><div class="input-group"><label>Mode</label><select id="v30Mode"><option ${cfg.mode==='local-only'?'selected':''}>local-only</option><option ${cfg.mode==='manual-export'?'selected':''}>manual-export</option><option ${cfg.mode==='future-api'?'selected':''}>future-api</option></select></div></div><div class="input-group"><label>Future endpoint URL optional</label><input id="v30Endpoint" value="${esc(cfg.endpoint)}" placeholder="https://..."></div><button class="primary block" onclick="v30SaveCloudConfig()">Save Sync Config</button></div>
    <div class="card"><div class="card-header">Backup and sync actions</div><div class="v30-grid">${action('📦','Full Backup','Export all local app data','v30ExportFullBackup()')}${action('📤','Outbox Package','Export pending sync items','v30ExportOutbox()')}${action('✅','Mark Synced','Clear simulated outbox','v30MarkSynced()')}${action('🧪','Run Site Test','Create diagnostics JSON','v30RunSiteTest()')}</div></div><div class="v30-spacer"></div>`}
  window.v30SaveCloudConfig=function(){const cfg={provider:$('v30Provider').value,mode:$('v30Mode').value,endpoint:$('v30Endpoint').value.trim(),updatedAt:now()};save(KEYS.config,cfg);audit('config','Cloud config saved');tip('Sync config saved.');renderSync()};
  window.v30ExportFullBackup=function(){const data={version:VERSION,exportedAt:now(),v30Tickets:tickets(),outbox:outbox(),audit:load(KEYS.audit,[]),prefs:prefs(),cloudConfig:load(KEYS.config,{}),damage:damages(),localStorageKeys:Object.keys(localStorage).filter(k=>k.startsWith('oj_'))};download(JSON.stringify(data,null,2),'application/json','oceanjet_v30_full_local_backup.json');audit('export','full backup');tip('Full backup exported.');};
  window.v30ExportOutbox=function(){download(JSON.stringify({version:VERSION,exportedAt:now(),outbox:outbox()},null,2),'application/json','oceanjet_v30_outbox_package.json');audit('export','outbox');tip('Outbox exported.');};
  window.v30MarkSynced=function(){save(KEYS.outbox,[]);const list=tickets().map(x=>Object.assign({},x,{syncStatus:'Synced'}));save(KEYS.tickets,list);audit('sync','Outbox marked synced');tip('Outbox cleared.');renderSync()};
  window.v30RunSiteTest=function(){const result={at:now(),version:VERSION,online:navigator.onLine,views:VIEWS.map(v=>({view:v,exists:!!$('view-'+v)})),storage:storage(),tickets:tickets().length,damage:damages().length,errors:load('oj_v30_errors',[])};download(JSON.stringify(result,null,2),'application/json','oceanjet_v30_site_test.json');audit('test','site test exported');tip('Site test exported.');};
  function renderAdmin(){const locked=!adminOK();const p=prefs();ensureView('v30-admin').innerHTML=`
    <div class="card v30-shell"><div class="v30-title"><div><h2>🛡️ V30 Admin + Privacy Console</h2><div class="v30-sub">Admin-only diagnostics, privacy checks, mobile mode settings, and content knowledge base controls.</div></div><span class="v30-chip ${locked?'red':'green'}">${locked?'LOCKED':'UNLOCKED'}</span></div></div>
    ${locked?adminLogin():adminTools(p)}<div class="v30-spacer"></div>`}
  function adminLogin(){return `<div class="card"><div class="card-header">Admin login required</div><div class="grid2"><div class="input-group"><label>Username</label><input id="v30AdminUser" placeholder="admin"></div><div class="input-group"><label>Password</label><input id="v30AdminPass" type="password" placeholder="admin"></div></div><button class="primary block" onclick="v30AdminUnlock()">Unlock Admin Console</button><p class="muted">Demo credentials: admin/admin, demo/demo, supervisor/supervisor</p></div>`}
  function adminTools(p){const m=metrics();const kb=load(KEYS.kb,{policy:'Handle passenger data only when needed. Export backups after each shift.',notice:'Welcome to OceanJet service portal.'});return `<div class="card"><div class="card-header">Admin diagnostics</div>${kpis(m)}<div class="v30-row"><div><strong>Privacy posture</strong><small>Passenger names should be optional; exports should be admin-controlled.</small></div><span class="v30-chip amber">LOCAL DATA</span></div></div><div class="card"><div class="card-header">Mobile behavior</div><div class="v30-grid">${action('👆','Large Touch Mode',p.large?'Currently ON':'Currently OFF','v30ToggleLargeTouch()')}${action('⚡','Fast Mode',p.fast?'Currently ON':'Currently OFF','v30ToggleFastMode()')}${action('🧹','Compact Audit','Keep latest 60 logs','v30CompactAudit()')}${action('🚪','Lock Admin','Return to protected mode','v30AdminLock()')}</div></div><div class="card"><div class="card-header">Content knowledge base</div><div class="input-group"><label>Public notice</label><textarea id="v30KbNotice" rows="3">${esc(kb.notice)}</textarea></div><div class="input-group"><label>Privacy / SOP reminder</label><textarea id="v30KbPolicy" rows="4">${esc(kb.policy)}</textarea></div><button class="primary block" onclick="v30SaveKB()">Save Knowledge Base</button></div><div class="card"><div class="card-header">Admin backup</div><div class="v30-grid">${action('📦','Export Backup','Download complete local backup','v30ExportFullBackup()','good')}${action('🧪','Run Test','Download diagnostics','v30RunSiteTest()','warn')}${action('🔎','Privacy Audit','Check optional sensitive fields','v30PrivacyAudit()','hot')}</div></div>`}
  window.v30AdminUnlock=function(){const u=$('v30AdminUser')?.value||'',p=$('v30AdminPass')?.value||'';const ok=(u==='admin'&&p==='admin')||(u==='demo'&&p==='demo')||(u==='supervisor'&&p==='supervisor');if(ok){sessionStorage.setItem('oj_v22_admin_unlocked','1');audit('admin','unlock');tip('Admin unlocked.');renderAdmin()}else tip('Wrong login.')};
  window.v30AdminLock=function(){sessionStorage.removeItem('oj_v22_admin_unlocked');localStorage.removeItem('oj_v22_admin_unlocked');audit('admin','lock');tip('Admin locked.');renderAdmin()};
  window.v30ToggleLargeTouch=function(){const p=prefs();p.large=!p.large;setPrefs(p);audit('prefs','large '+p.large);renderAdmin()};
  window.v30ToggleFastMode=function(){const p=prefs();p.fast=!p.fast;setPrefs(p);audit('prefs','fast '+p.fast);renderAdmin()};
  window.v30CompactAudit=function(){save(KEYS.audit,load(KEYS.audit,[]).slice(0,60));tip('Audit compacted.');renderAdmin()};
  window.v30SaveKB=function(){save(KEYS.kb,{notice:$('v30KbNotice').value,policy:$('v30KbPolicy').value,updatedAt:now()});audit('kb','saved');tip('Knowledge base saved.')};
  window.v30PrivacyAudit=function(){const risky=tickets().filter(x=>x.name&&x.name.length>1);const report={at:now(),tickets:tickets().length,recordsWithPassengerName:risky.length,recommendation:'Keep passenger name optional and export backups only through admin tools.'};download(JSON.stringify(report,null,2),'application/json','oceanjet_v30_privacy_audit.json');audit('privacy','audit exported');tip('Privacy audit exported.')};
  const renderers={'v30-os':renderOS,'v30-care':renderCare,'v30-claim':renderClaim,'v30-sync':renderSync,'v30-admin':renderAdmin};
  function renderLocal(name){activate(name);(renderers[name]||renderOS)()}
  function patchDrawer(){const menu=$('drawerMenu');if(!menu)return;const add=(v,l,i)=>{if(!menu.querySelector(`[data-view="${v}"]`))menu.insertAdjacentHTML('beforeend',`<div class="drawer-item" data-view="${v}" onclick="showView('${v}')"><i>${i}</i> ${l}</div>`)};add('v30-os','V30 SuperApp OS','🧬');add('v30-care','Passenger Care','👤');add('v30-claim','Claim Automation','🧳');add('v30-sync','Sync Bridge','☁️');add('v30-admin','V30 Admin','🛡️')}
  function patchNav(){if(window.__v30NavPatched)return;window.__v30NavPatched=true;const oldShow=window.showView;window.showView=function(name){if(VIEWS.includes(name)){renderLocal(name);return}const r=oldShow?oldShow.apply(this,arguments):undefined;setTimeout(()=>{patchDrawer();patchDashboard();patchMap();},180);return r};try{showView=window.showView}catch(e){}const oldBuild=window.buildDrawerMenu;window.buildDrawerMenu=function(){const r=oldBuild?oldBuild.apply(this,arguments):undefined;patchDrawer();return r};try{buildDrawerMenu=window.buildDrawerMenu}catch(e){}}
  function patchDashboard(){const v=$('view-dashboard');if(!v||$('v30DashPanel'))return;const m=metrics();v.insertAdjacentHTML('afterbegin',`<div id="v30DashPanel" class="card v30-shell"><div class="v30-title"><div><h2>🧬 V30 Service SuperApp Layer</h2><div class="v30-sub">Readiness ${m.ready}% • ${m.open.length} open V30 tickets • ${m.ob.length} sync item(s)</div></div><button class="sm primary" onclick="showView('v30-os')">Open V30</button></div></div>`)}
  function patchMap(){const v=$('view-map');if(!v||$('v30MapPanel'))return;v.insertAdjacentHTML('afterbegin',`<div id="v30MapPanel" class="card v30-shell"><div class="v30-title"><div><h2>🗺️ V30 Passenger + Ops Map Lens</h2><div class="v30-sub">Use V29 predictive map for route pressure or V30 Passenger Care for guided route help.</div></div><button class="sm accent" onclick="showView('v29-map')">Predictive Map</button></div></div>`)}
  function installHealthPill(){if($('v30HealthPill'))return;const d=document.createElement('div');d.id='v30HealthPill';d.className='v30-floating-health';d.onclick=()=>showView('v30-sync');document.body.appendChild(d);setInterval(()=>{const m=metrics();d.textContent=`V30 ${navigator.onLine?'Online':'Offline'} • ${m.ready}%`;},2500)}
  function guardErrors(){window.addEventListener('error',e=>{const arr=load('oj_v30_errors',[]);arr.unshift({at:now(),message:e.message,source:e.filename,line:e.lineno});save('oj_v30_errors',arr.slice(0,40));audit('error',e.message)});/* V47FIX: disabled V30 auto-open recovery to avoid hijacking current screen. */}
  function boot(){try{document.body.classList.add('v30-ready');setPrefs(prefs());VIEWS.forEach(ensureView);patchNav();if(typeof window.buildDrawerMenu==='function')window.buildDrawerMenu();patchDashboard();patchMap();installHealthPill();guardErrors();audit('boot',VERSION+' loaded');console.log(VERSION+' loaded')}catch(e){console.error('V30 boot error',e);audit('boot_error',e.message);tip('V30 boot recovery: '+e.message)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
