
(function(){
  if(window.__OJ_V25_SMART_OPS__) return;
  window.__OJ_V25_SMART_OPS__ = true;
  const VERSION='V25_SMART_OPS_EXPERIENCE';
  const CLAIM_KEY='oj_v22_claims';
  const TICKET_KEY='oj_v24_visit_tickets';
  const FEEDBACK_KEY='oj_v24_feedback';
  const NOTICE_KEY='oj_v25_public_notices';
  const TRAIN_KEY='oj_v25_training_progress';
  const PREF_KEY='oj_v25_prefs';
  const AUDIT_KEY='oj_v25_last_readiness_scan';
  const $=(id)=>document.getElementById(id);
  const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=(s)=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  const load=(k,f)=>{try{const raw=localStorage.getItem(k);return raw?JSON.parse(raw):f}catch(e){return f}};
  const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){console.warn('V25 save failed',e);return false}};
  const now=()=>new Date().toLocaleString('en-PH',{timeZone:'Asia/Manila',hour12:true});
  const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'});
  const toast=(m)=>{try{if(typeof window.toast==='function')return window.toast(m)}catch(e){} const d=document.createElement('div');d.textContent=m;d.style.cssText='position:fixed;left:50%;top:16px;transform:translateX(-50%);background:#ff4fa3;color:white;padding:10px 14px;border-radius:999px;z-index:99999;font-weight:900;box-shadow:0 8px 24px rgba(0,0,0,.35)';document.body.appendChild(d);setTimeout(()=>d.remove(),2300)};
  const claims=()=>load(CLAIM_KEY,[]);
  const tickets=()=>load(TICKET_KEY,[]);
  const feedback=()=>load(FEEDBACK_KEY,[]);
  const notices=()=>load(NOTICE_KEY,seedNotices());
  const prefs=()=>load(PREF_KEY,{compact:false,autoNotice:true});
  const uid=(p)=>p+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,5).toUpperCase();
  function routeLabel(r){ if(!r) return 'Unspecified route'; try{ if(typeof window.label==='function') return window.label(r); }catch(e){} return String(r).replace(/_/g,' → ').replace(/\b\w/g,c=>c.toUpperCase()); }
  function mask(s){s=String(s||'').trim();return s? s[0]+'***' : 'No name';}
  function seedNotices(){return [
    {id:'N-'+today()+'-001',level:'info',route:'all',title:'Mobile portal active',message:'Passengers may use claim status, fare tools, and service hub from their phone.',expires:'',createdAt:now()},
    {id:'N-'+today()+'-002',level:'warning',route:'cebu_tagbilaran',title:'Arrive early for peak trips',message:'Prepare ticket, valid ID, and baggage tag before counter verification.',expires:'',createdAt:now()}
  ];}
  function isOpen(c){return !['Closed','Resolved','Rejected','Done'].includes(String(c.status||''));}
  function claimAgeHours(c){const raw=c.updatedAt||c.createdAt||c.phtTimestamp||c.dateTaken;const t=Date.parse(raw);return Number.isFinite(t)?Math.max(0,(Date.now()-t)/36e5):0;}
  function risk(c){let s=10; const text=JSON.stringify(c).toLowerCase(); if(/critical|urgent|wet|missing|crack|broken/.test(text))s+=35;if(!c.tag&&!c.tagNo)s+=14;if(!c.contact&&!c.phone)s+=12;if(!c.lastName&&!c.name)s+=10;if(claimAgeHours(c)>24)s+=18;if(String(c.status||'New')==='New')s+=8;return Math.min(100,s);}
  function storage(){let total=0,items=[];try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';const v=localStorage.getItem(k)||'';const b=(k.length+v.length)*2;total+=b;items.push({k,b});}}catch(e){} return {bytes:total,mb:total/1024/1024,pct:Math.min(100,Math.round(total/(4.5*1024*1024)*100)),items:items.sort((a,b)=>b.b-a.b)};}
  function ensureView(name){let v=$('view-'+name); if(!v){v=document.createElement('div');v.id='view-'+name;v.className='view';(document.querySelector('.app')||document.body).appendChild(v);} return v;}
  function activeNotices(){const n=notices();const d=today();return n.filter(x=>!x.expires||x.expires>=d).slice(0,30)}
  function health(){const cs=claims(),open=cs.filter(isOpen),missing=cs.filter(c=>(!c.tag&&!c.tagNo)||(!c.lastName&&!c.name)||(!c.contact&&!c.phone));const tk=tickets().filter(t=>String(t.status)!=='Done');const fb=feedback();const avg=fb.length?(fb.reduce((a,f)=>a+Number(f.rating||0),0)/fb.length):0;const st=storage();const urgent=open.filter(c=>risk(c)>=65).length;return {claims:cs,open,missing,tickets:tk,feedback:fb,avg,storage:st,urgent,score:Math.max(0,100-(urgent*12)-(missing.length*4)-Math.max(0,st.pct-70))};}
  function noticeTicker(){const rows=activeNotices().slice(0,3);return rows.length?rows.map(n=>`<div class="v25-notice ${esc(n.level)}"><b>${esc(n.title)}</b><br><small>${esc(n.route==='all'?'All routes':routeLabel(n.route))} • ${esc(n.message)}</small></div>`).join(''):'<p class="muted">No active notices.</p>';}
  function renderQuickDesk(){const h=health();ensureView('quickdesk').innerHTML=`
    <div class="card v25-shell"><div class="v25-title"><div><h2>⚡ V25 Quick Desk</h2><small>One mobile screen for the most used passenger and staff actions.</small></div><span class="v25-chip ${h.urgent?'red':'green'}">${h.urgent?h.urgent+' urgent':'Ready'}</span></div><div class="v25-grid" style="margin-top:12px"><div class="v25-kpi"><b>${h.open.length}</b><span>Open Claims</span></div><div class="v25-kpi"><b>${h.tickets.length}</b><span>Waiting Tickets</span></div><div class="v25-kpi"><b>${h.avg?h.avg.toFixed(1):'--'}</b><span>Avg Feedback</span></div><div class="v25-kpi"><b>${h.score}%</b><span>Site Readiness</span></div></div><div class="v25-meter"><span style="width:${h.score}%"></span></div></div>
    <div class="card"><div class="card-header">🚀 Fast Actions</div><div class="v25-action-grid">
      ${action('🧮','Baggage Calc','Compute official counter fee','calculator')}
      ${action('🧳','Report Baggage','Damage or lost baggage form','portal')}
      ${action('🔎','Claim Status','Track with claim number','claimstatus')}
      ${action('🧭','Service Hub','Passenger and staff service','servicehub')}
      ${action('🧩','Queue Manager','Prioritize pending cases','queuemanager')}
      ${action('📢','Notice Board','Route and port advisories','noticeboard')}
      ${action('🩺','Readiness Scan','Storage, errors, data quality','readiness')}
      ${action('🎓','Micro Training','Short SOP skill checks','training')}
    </div></div>
    <div class="card"><div class="card-header">📢 Active Notices</div>${noticeTicker()}</div>
    <div class="card"><div class="card-header">🎯 What needs attention</div>${attentionRows(h)}</div><div class="v25-bottom-space"></div>`;}
  function action(ico,title,sub,view){return `<button class="v25-action" onclick="showView('${view}')"><span class="ico">${ico}</span><b>${esc(title)}</b><small>${esc(sub)}</small></button>`}
  function attentionRows(h){const rows=[]; if(h.urgent)rows.push(['red','Urgent claims',h.urgent+' claim(s) have high priority score.','queuemanager']); if(h.missing.length)rows.push(['amber','Missing info',h.missing.length+' claim(s) need tag/contact/name completion.','queuemanager']); if(h.storage.pct>72)rows.push(['amber','Storage high','Export backup and clean duplicate data.','readiness']); if(!activeNotices().length)rows.push(['amber','No active notices','Add port or route advisory for passengers.','noticeboard']); if(!rows.length)rows.push(['green','All clear','No major issue detected right now.','readiness']); return rows.map(r=>`<div class="v25-row"><div><strong>${esc(r[1])}</strong><small>${esc(r[2])}</small></div><button class="sm" onclick="showView('${r[3]}')">Open</button></div>`).join('')}
  function renderNoticeBoard(){const ns=notices();const canEdit=isAdminUnlocked();ensureView('noticeboard').innerHTML=`
    <div class="card v25-shell"><div class="v25-title"><div><h2>📢 Public Notice Board</h2><small>Route advisories, port reminders, and passenger-facing announcements.</small></div><span class="v25-chip pink">${activeNotices().length} active</span></div></div>
    <div class="card"><div class="card-header">Active Notices</div>${ns.length?ns.map(noticeRow).join(''):'<p class="muted">No notices yet.</p>'}</div>
    <div class="card"><div class="card-header">${canEdit?'Add New Notice':'Notice Manager Locked'}</div>${canEdit?noticeForm():'<p class="muted">Open Admin Panel and login to add/edit public notices.</p><button class="primary block" onclick="showView(\'admin\')">Admin Login</button>'}</div><div class="v25-bottom-space"></div>`;}
  function noticeRow(n){return `<div class="v25-notice ${esc(n.level)}"><div class="v25-title"><div><b>${esc(n.title)}</b><small>${esc(n.route==='all'?'All routes':routeLabel(n.route))} • ${esc(n.createdAt)} ${n.expires?'• expires '+esc(n.expires):''}</small></div><span class="v25-chip ${n.level==='critical'?'red':n.level==='warning'?'amber':'green'}">${esc(n.level)}</span></div><p style="margin:8px 0 0;color:var(--text2,#dbe7ff)">${esc(n.message)}</p>${isAdminUnlocked()?`<button class="sm danger" onclick="v25DeleteNotice('${esc(n.id)}')">Remove</button>`:''}</div>`}
  function noticeForm(){return `<div class="grid2"><div class="input-group"><label>Level</label><select id="v25NoticeLevel"><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select></div><div class="input-group"><label>Route</label><select id="v25NoticeRoute"><option value="all">All Routes</option>${routeOptionsHtml()}</select></div></div><div class="input-group"><label>Title</label><input id="v25NoticeTitle" placeholder="Example: Gate update"></div><div class="input-group"><label>Message</label><textarea id="v25NoticeMsg" rows="4" placeholder="Short passenger-friendly instruction"></textarea></div><div class="input-group"><label>Expires optional</label><input id="v25NoticeExp" type="date"></div><button class="primary block" onclick="v25SaveNotice()">Publish Notice</button>`}
  function routeOptionsHtml(){const routes=['cebu_tagbilaran','cebu_maasin','cebu_surigao','cebu_siquijor','cebu_dumaguete','cebu_ormoc','cebu_palompon','cebu_getafe'];return routes.map(r=>`<option value="${r}">${esc(routeLabel(r))}</option>`).join('')}
  window.v25SaveNotice=function(){const rows=notices();const item={id:uid('NOTICE'),level:$('v25NoticeLevel')?.value||'info',route:$('v25NoticeRoute')?.value||'all',title:$('v25NoticeTitle')?.value.trim()||'OceanJet Notice',message:$('v25NoticeMsg')?.value.trim()||'Please follow port staff instructions.',expires:$('v25NoticeExp')?.value||'',createdAt:now()};rows.unshift(item);save(NOTICE_KEY,rows.slice(0,80));toast('Notice published.');renderNoticeBoard();};
  window.v25DeleteNotice=function(id){if(!confirm('Remove this notice?'))return;save(NOTICE_KEY,notices().filter(n=>String(n.id)!==String(id)));renderNoticeBoard();toast('Notice removed.');};
  function isAdminUnlocked(){try{return sessionStorage.getItem('oj_v22_admin_unlocked')==='1'||localStorage.getItem('oj_v22_admin_unlocked')==='1'}catch(e){return false}}
  function renderQueueManager(){const rows=claims().slice().sort((a,b)=>risk(b)-risk(a));const lanes=[['New','New'],['Under Review','Under Review'],['Claim Stub Issued','Claim Stub Issued'],['Resolved','Resolved']];ensureView('queuemanager').innerHTML=`
    <div class="card v25-shell"><div class="v25-title"><div><h2>🧩 Smart Queue Manager</h2><small>Prioritize claim work by risk, missing information, and waiting time.</small></div><span class="v25-chip ${rows.filter(c=>risk(c)>=65&&isOpen(c)).length?'red':'green'}">Auto-ranked</span></div><div class="v25-stick"><input id="v25QueueSearch" placeholder="Search claim, tag, last name, route" oninput="v25FilterQueue()"></div></div>
    <div id="v25QueueLanes" class="v25-grid2">${lanes.map(l=>laneHtml(l[0],rows.filter(c=>(c.status||'New')===l[1] || (l[1]==='New'&&!c.status)))).join('')}</div><div class="v25-bottom-space"></div>`;}
  function laneHtml(title,rows){return `<div class="v25-lane"><h3>${esc(title)} (${rows.length})</h3>${rows.slice(0,8).map(queueCard).join('')||'<p class="muted">Empty lane.</p>'}</div>`}
  function queueCard(c){const r=risk(c),cls=r>=65?'red':r>=40?'amber':'green';const id=c.id||c.caseId||'NO-ID';return `<div class="v25-row"><div><strong>${esc(id)}</strong><small>${esc(c.type||'Claim')} • ${esc(routeLabel(c.route)||c.routeLabel||'')} • ${esc(mask(c.lastName||c.name))}<br>Tag: ${esc(c.tag||c.tagNo||'missing')} • Age: ${Math.round(claimAgeHours(c))}h</small></div><div class="right"><span class="v25-chip ${cls}">${r}%</span><br><button class="sm" onclick="v25CycleClaim('${esc(id)}')">Next</button></div></div>`}
  window.v25FilterQueue=function(){const q=String($('v25QueueSearch')?.value||'').toLowerCase();const rows=claims().filter(c=>JSON.stringify(c).toLowerCase().includes(q)).sort((a,b)=>risk(b)-risk(a));const lanes=[['New','New'],['Under Review','Under Review'],['Claim Stub Issued','Claim Stub Issued'],['Resolved','Resolved']];const out=$('v25QueueLanes'); if(out) out.innerHTML=lanes.map(l=>laneHtml(l[0],rows.filter(c=>(c.status||'New')===l[1] || (l[1]==='New'&&!c.status)))).join('');};
  window.v25CycleClaim=function(id){const rows=claims();const c=rows.find(x=>String(x.id||x.caseId)===String(id));if(!c)return;const seq=['New','Under Review','Claim Stub Issued','Resolved'];const cur=seq.indexOf(c.status||'New');c.status=seq[(cur+1+seq.length)%seq.length];c.updatedAt=now();save(CLAIM_KEY,rows);toast('Claim moved to '+c.status);renderQueueManager();};
  function readinessChecks(){const h=health();const sw=!!(navigator.serviceWorker&&navigator.serviceWorker.controller);const https=location.protocol==='https:'||location.hostname==='localhost'||location.protocol==='file:';const compact=prefs().compact;const duplicateIds=duplicateClaims().length;const checks=[
    ['App visible',!!document.querySelector('.view.active'),'Active view is available'],['Storage below 75%',h.storage.pct<75,`${h.storage.mb.toFixed(2)}MB used`],['No urgent backlog',h.urgent===0,`${h.urgent} urgent open claims`],['Claims have key info',h.missing.length===0,`${h.missing.length} claims missing info`],['No duplicate claim IDs',duplicateIds===0,`${duplicateIds} duplicate ID(s)`],['Service worker ready',sw||location.protocol==='file:',sw?'Active':'Needs GitHub Pages/browser reload'],['Secure context',https,location.protocol],['Compact mobile mode',compact,'Recommended for low-end Android']
  ];return checks;}
  function renderReadiness(){const checks=readinessChecks();const pass=checks.filter(c=>c[1]).length;const score=Math.round(pass/checks.length*100);localStorage.setItem(AUDIT_KEY,now());ensureView('readiness').innerHTML=`
    <div class="card v25-shell"><div class="v25-title"><div><h2>🩺 Site Readiness Scan</h2><small>Checks mobile performance, storage, queue quality, and deployment readiness.</small></div><span class="v25-chip ${score>80?'green':score>55?'amber':'red'}">${score}%</span></div><div class="v25-meter"><span style="width:${score}%"></span></div></div>
    <div class="card"><div class="card-header">Diagnostics</div>${checks.map(c=>`<div class="v25-row"><div><strong>${c[1]?'✅':'⚠️'} ${esc(c[0])}</strong><small>${esc(c[2])}</small></div><span class="v25-chip ${c[1]?'green':'amber'}">${c[1]?'Pass':'Check'}</span></div>`).join('')}</div>
    <div class="card"><div class="card-header">Repair Tools</div><div class="v25-action-grid"><button class="v25-action" onclick="v25ToggleCompact()"><span class="ico">📱</span><b>Toggle Fast Mobile Mode</b><small>Reduce animations and heavy visual effects.</small></button><button class="v25-action" onclick="v25DeduplicateClaims()"><span class="ico">🧹</span><b>Clean Duplicate Claims</b><small>Keep the newest record per claim ID.</small></button><button class="v25-action" onclick="v25ExportLeanBackup()"><span class="ico">💾</span><b>Lean Backup</b><small>Small JSON without embedded photos.</small></button><button class="v25-action" onclick="location.reload()"><span class="ico">🔄</span><b>Reload App</b><small>Use after GitHub Pages upload.</small></button></div></div><div class="v25-bottom-space"></div>`;}
  function duplicateClaims(){const seen={},dupes=[];claims().forEach((c,i)=>{const id=c.id||c.caseId;if(!id)return;if(seen[id]!=null)dupes.push({id,i});seen[id]=i});return dupes;}
  window.v25ToggleCompact=function(){const p=prefs();p.compact=!p.compact;save(PREF_KEY,p);document.body.classList.toggle('v25-compact',!!p.compact);toast(p.compact?'Fast Mobile Mode on':'Fast Mobile Mode off');renderReadiness();};
  window.v25DeduplicateClaims=function(){const rows=claims();const map=new Map();rows.slice().reverse().forEach(c=>{const id=c.id||c.caseId||uid('CLAIM');map.set(id,c)});const clean=Array.from(map.values()).reverse();save(CLAIM_KEY,clean);toast('Duplicate cleanup complete: '+(rows.length-clean.length)+' removed');renderReadiness();};
  window.v25ExportLeanBackup=function(){const data={version:VERSION,exportedAt:now(),claims:claims().map(c=>Object.fromEntries(Object.entries(c).filter(([k])=>!['photos','image','dataUrl'].includes(k)))),tickets:tickets(),feedback:feedback(),notices:notices(),readiness:{lastScan:localStorage.getItem(AUDIT_KEY),storage:storage()}};download(JSON.stringify(data,null,2),'application/json','oceanjet_v25_lean_backup_'+today()+'.json');};
  function download(data,type,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
  const trainingModules=[['counter','Counter Opening','Check device time, internet state, camera permission, and backup location.'],['claim','Damage Claim Intake','Verify PSN or ticket, last name, baggage tag, route, and at least two photos.'],['privacy','Privacy Reminder','Collect only necessary data. Mask passenger details when showing public queues.'],['handoff','Shift Handoff','Export daily pack, list urgent claims, and brief next staff.']];
  function renderTraining(){const p=load(TRAIN_KEY,{});ensureView('training').innerHTML=`<div class="card v25-shell"><div class="v25-title"><div><h2>🎓 Micro Training</h2><small>Short, repeatable SOP refreshers for port staff using mobile phones.</small></div><span class="v25-chip green">${Object.keys(p).length}/${trainingModules.length} done</span></div></div><div class="card">${trainingModules.map(m=>`<div class="v25-row"><div><strong>${p[m[0]]?'✅':'▫️'} ${esc(m[1])}</strong><small>${esc(m[2])}${p[m[0]]?' • Completed '+esc(p[m[0]]):''}</small></div><button class="sm ${p[m[0]]?'':'primary'}" onclick="v25CompleteTraining('${m[0]}')">${p[m[0]]?'Redo':'Done'}</button></div>`).join('')}<button class="accent block" onclick="v25ResetTraining()">Reset Training Progress</button></div><div class="v25-bottom-space"></div>`;}
  window.v25CompleteTraining=function(id){const p=load(TRAIN_KEY,{});p[id]=now();save(TRAIN_KEY,p);toast('Training marked complete.');renderTraining();};
  window.v25ResetTraining=function(){save(TRAIN_KEY,{});renderTraining();toast('Training reset.');};
  function patchPortal(){const v=$('view-portal');if(!v||$('v25PortalBoost'))return;v.insertAdjacentHTML('afterbegin',`<div id="v25PortalBoost" class="card v25-shell"><div class="v25-title"><div><h2>⚡ Smart Portal Shortcuts</h2><small>V25 adds quick desk, notices, queue manager, readiness scan, and staff micro-training.</small></div><span class="v25-chip green">V25</span></div><div class="v25-action-grid">${action('⚡','Quick Desk','Open command home','quickdesk')}${action('📢','Notice Board','Read route updates','noticeboard')}${action('🧩','Queue','Staff priorities','queuemanager')}${action('🩺','Readiness','Check app health','readiness')}</div></div>`);}
  function patchDashboard(){const v=$('view-dashboard');if(!v||$('v25DashBoost'))return;const h=health();v.insertAdjacentHTML('afterbegin',`<div id="v25DashBoost" class="card v25-shell"><div class="v25-title"><div><h2>⚡ V25 Smart Ops Snapshot</h2><small>Efficiency layer for passenger service, staff queue control, public notices, and app readiness.</small></div><span class="v25-chip ${h.score>75?'green':'amber'}">${h.score}% ready</span></div><div class="v25-grid" style="margin-top:10px"><div class="v25-kpi"><b>${h.open.length}</b><span>Open Claims</span></div><div class="v25-kpi"><b>${activeNotices().length}</b><span>Notices</span></div><div class="v25-kpi"><b>${h.tickets.length}</b><span>Tickets</span></div><div class="v25-kpi"><b>${h.storage.mb.toFixed(1)}MB</b><span>Storage</span></div></div><div class="v25-action-grid">${action('⚡','Quick Desk','Open fast actions','quickdesk')}${action('🧩','Queue','Manage claims','queuemanager')}${action('📢','Notices','Passenger updates','noticeboard')}${action('🩺','Scan','Readiness check','readiness')}</div></div>`);}
  function patchDrawer(){const menu=$('drawerMenu');if(!menu)return;const items=[['quickdesk','⚡','Quick Desk'],['noticeboard','📢','Notice Board'],['queuemanager','🧩','Queue Manager'],['readiness','🩺','Readiness Scan'],['training','🎓','Micro Training']];items.reverse().forEach(([view,icon,label])=>{if(!menu.querySelector(`.drawer-item[data-view="${view}"]`)){const d=document.createElement('div');d.className='drawer-item';d.dataset.view=view;d.setAttribute('onclick',`navigate('${view}')`);d.innerHTML=`<i>${icon}</i> ${label}`;menu.insertBefore(d,menu.firstChild);}})}
  function showV25(name){qsa('.view').forEach(v=>v.classList.remove('active'));ensureView(name).classList.add('active');if(name==='quickdesk')renderQuickDesk();if(name==='noticeboard')renderNoticeBoard();if(name==='queuemanager')renderQueueManager();if(name==='readiness')renderReadiness();if(name==='training')renderTraining();qsa('#drawerMenu .drawer-item').forEach(el=>el.classList.toggle('active',el.dataset.view===name));try{window.scrollTo({top:0,behavior:'smooth'})}catch(e){window.scrollTo(0,0)}}
  function patchNavigation(){const views=['quickdesk','noticeboard','queuemanager','readiness','training'];const oldShow=window.showView;if(oldShow&&!oldShow.__v25Wrapped){window.showView=showView=function(name){if(views.includes(name)){showV25(name);return;}const r=oldShow.apply(this,arguments);setTimeout(()=>{patchDrawer();if(name==='portal')patchPortal();if(name==='dashboard')patchDashboard();},90);return r;};window.showView.__v25Wrapped=true;}const oldBuild=window.buildDrawerMenu;if(oldBuild&&!oldBuild.__v25Wrapped){window.buildDrawerMenu=buildDrawerMenu=function(){const r=oldBuild.apply(this,arguments);patchDrawer();return r;};window.buildDrawerMenu.__v25Wrapped=true;}}
  function boot(){try{document.body.classList.add('v25-mobile-polish');if(prefs().compact)document.body.classList.add('v25-compact');['quickdesk','noticeboard','queuemanager','readiness','training'].forEach(ensureView);if(!localStorage.getItem(NOTICE_KEY))save(NOTICE_KEY,seedNotices());patchNavigation();if(typeof window.buildDrawerMenu==='function')window.buildDrawerMenu();patchDrawer();setTimeout(()=>{patchPortal();patchDashboard();},700);console.log(VERSION+' loaded');}catch(e){console.error('V25 boot error',e);toast('V25 boot issue: '+e.message)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
