
(function(){
  'use strict';
  const V8_VERSION='v8-pack3-command-center-source-based';
  const ROUTES=['cebu_tagbilaran','cebu_maasin','cebu_surigao','cebu_siquijor','cebu_dumaguete','cebu_ormoc','cebu_palompon','cebu_getafe'];
  const INFO={
    cebu_tagbilaran:{title:'Cebu to Tagbilaran',dest:'Tagbilaran',vessel:'OJ 388',dep:'5:10 AM',arr:'7:10 AM',travel:'2h',gate:'A1',weather:'Calm sea',type:'Direct',fare:1000,x:37,y:37},
    cebu_maasin:{title:'Cebu to Maasin',dest:'Maasin',vessel:'OJ 03',dep:'7:00 AM',arr:'10:00 AM',travel:'3h',gate:'C1',weather:'Clear skies',type:'Direct',fare:1430,x:63,y:65},
    cebu_surigao:{title:'Cebu to Surigao',dest:'Surigao',vessel:'OJ 03 + OJ 388',dep:'7:00 AM',arr:'12:30 PM',travel:'5h 30m',gate:'C2',weather:'Transfer watch',type:'Connect via Maasin',fare:2470,x:76,y:72},
    cebu_siquijor:{title:'Cebu to Siquijor',dest:'Siquijor',vessel:'OJ 388 + OJ 988',dep:'6:00 AM',arr:'10:20 AM',travel:'4h 20m',gate:'A2',weather:'Moderate sea',type:'Connect via Tagbilaran',fare:2000,x:45,y:70},
    cebu_dumaguete:{title:'Cebu to Dumaguete',dest:'Dumaguete',vessel:'OJ 388',dep:'5:10 AM',arr:'9:30 AM',travel:'4h 20m',gate:'A3',weather:'Transfer watch',type:'Connect via Tagbilaran',fare:2170,x:51,y:80},
    cebu_ormoc:{title:'Cebu to Ormoc',dest:'Ormoc',vessel:'OJ 8',dep:'6:00 AM',arr:'9:00 AM',travel:'3h',gate:'B1',weather:'Calm sea',type:'Direct',fare:1430,x:72,y:39},
    cebu_palompon:{title:'Cebu to Palompon',dest:'Palompon',vessel:'OJ 02',dep:'10:00 AM',arr:'1:00 PM',travel:'3h',gate:'B2',weather:'Clear skies',type:'Direct',fare:1430,x:68,y:28},
    cebu_getafe:{title:'Cebu to Getafe',dest:'Getafe',vessel:'OJ 10',dep:'6:30 AM',arr:'7:30 AM',travel:'1h',gate:'D1',weather:'Fast lane',type:'Direct',fare:585,x:39,y:25}
  };
  const $=id=>document.getElementById(id);
  const peso=n=>(typeof fmtPHP==='function'?fmtPHP(Number(n)||0):'₱'+(Number(n)||0).toFixed(2));
  const label=r=>INFO[r]?.title||String(r).replace(/_/g,' to ').replace(/\b\w/g,m=>m.toUpperCase());
  const nowMin=()=>{const d=new Date();return d.getHours()*60+d.getMinutes();};
  const baseNoise=(route,offset=0)=>{let sum=nowMin()+offset; for(const ch of route) sum+=ch.charCodeAt(0); return sum;};
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  function load(route){const hist=(DB?.stats?.routeCounts?.[route]||0)*6;const weekend=[0,6].includes(new Date().getDay())?14:0;return clamp(25+(baseNoise(route)%48)+hist+weekend,8,99);}
  function risk(route){const l=load(route);const connect=INFO[route].type.includes('Connect')?14:0;const heavy=(DB?.history||[]).slice(0,30).filter(h=>h.route===route&&Number(h.weight)>60).length*5;return clamp(Math.round(l*.7+connect+heavy),5,99);}
  function statusClass(n){return n>78?'danger':n>58?'warn':'ok';}
  function statusText(n){return n>78?'Critical':n>58?'Moderate':'Smooth';}
  function color(n){return n>78?'linear-gradient(90deg,var(--v8red),var(--v8amber))':n>58?'linear-gradient(90deg,var(--v8amber),var(--v8cyan))':'linear-gradient(90deg,var(--v8green),var(--v8cyan))';}
  function ensureView(){if(!$('view-command')){const v=document.createElement('div');v.id='view-command';v.className='view';const anchor=$('view-innovation')||$('view-map')||document.querySelector('.view:last-of-type'); if(anchor&&anchor.parentNode) anchor.parentNode.insertBefore(v,anchor.nextSibling); else document.querySelector('.app')?.appendChild(v);}}
  function patchMenu(){if(typeof buildDrawerMenu==='function'&&!window.__v8MenuPatched){const old=buildDrawerMenu;window.buildDrawerMenu=buildDrawerMenu=function(){old();const menu=$('drawerMenu');if(menu&&!menu.querySelector('[data-view="command"]')){const after=menu.querySelector('[data-view="innovation"]');const html='<div class="drawer-item" data-view="command" onclick="navigate(\'command\')"><i>🛰️</i> Command Center</div>';if(after)after.insertAdjacentHTML('afterend',html);else menu.insertAdjacentHTML('beforeend',html);}};window.__v8MenuPatched=true;}}
  function patchShow(){if(typeof showView==='function'&&!window.__v8ShowPatched){const old=showView;window.showView=showView=function(name){ensureView();if(name==='command'){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-command').classList.add('active');document.querySelectorAll('.drawer-item').forEach(el=>el.classList.toggle('active',el.dataset.view==='command'));renderCommand();return;}return old(name);};window.__v8ShowPatched=true;}}
  function stats(){const s=DB?.stats||{};return{tx:s.transactions||0,rev:s.revenue||0,kg:s.totalKg||0,top:s.topRoute||'cebu_tagbilaran'};}
  function renderPulseMap(){return `<div class="v8-pulse-map"><div class="v8-node cebu">CEBU HUB</div>${Object.entries(INFO).map(([r,i])=>{const x1=50,y1=50,x2=i.x,y2=i.y;const dx=x2-x1,dy=y2-y1;const len=Math.sqrt(dx*dx+dy*dy);const ang=Math.atan2(dy,dx)*180/Math.PI;return `<div class="v8-beam" style="left:${x1}%;top:${y1}%;width:${len}%;transform:rotate(${ang}deg);animation-delay:${(baseNoise(r)%9)/10}s"></div><div class="v8-node" style="left:${x2}%;top:${y2}%">${i.dest}</div>`}).join('')}</div>`;}
  function portMetrics(){const routePressure=ROUTES.map(r=>load(r));const avg=Math.round(routePressure.reduce((a,b)=>a+b,0)/routePressure.length);const baggage=clamp(Math.round((DB?.stats?.totalKg||0)%45 + avg*.55),10,98);const queue=clamp(avg+((new Date().getMinutes()%20)-8),8,99);const counters=clamp(Math.round((baggage+queue)/2),8,99);const transfer=clamp(Math.max(load('cebu_surigao'),load('cebu_siquijor'),load('cebu_dumaguete'))+8,15,99);return{avg,baggage,queue,counters,transfer};}
  function recommendation(m){if(m.queue>78||m.counters>78)return'Open 2 extra baggage counters and prioritize connecting passengers.';if(m.transfer>70)return'Announce transfer gate reminders for Surigao, Siquijor, and Dumaguete.';if(m.avg>58)return'Moderate load. Prepare standby staff near baggage release.';return'Operations smooth. Maintain normal staffing and monitor next departure.';}
  function portPanel(){const m=portMetrics();const items=[['Boarding Queue',m.queue],['Baggage Counter Load',m.counters],['Cebu Pier Congestion',m.avg],['Connecting Trip Pressure',m.transfer],['Baggage Handling Load',m.baggage]];return `<div class="v8-port-grid">${items.map(([name,val])=>`<div class="v8-holo-card"><div class="v8-route-title"><b>${name}</b><span class="v8-chip ${statusClass(val)}">${statusText(val)}</span></div><div class="v8-meter"><i style="width:${val}%;background:${color(val)}"></i></div><small class="muted">AI pulse reading: ${val}%</small></div>`).join('')}</div><div class="v8-alert ${statusClass(Math.max(m.queue,m.counters,m.transfer))}"><b>AI Staff Recommendation:</b><br>${recommendation(m)}</div>`;}
  function vesselCard(route){const i=INFO[route];const l=load(route),r=risk(route);return `<div class="v8-holo-card"><div class="v8-route-title"><div><b>⛴ ${i.vessel}</b><br><small>${i.title}</small></div><span class="v8-chip ${statusClass(r)}">${i.gate}</span></div><table class="v8-mini-table"><tr><td>Departure</td><td>${i.dep}</td></tr><tr><td>Arrival</td><td>${i.arr}</td></tr><tr><td>Travel</td><td>${i.travel}</td></tr><tr><td>Trip Type</td><td>${i.type}</td></tr><tr><td>TC/OA Fare</td><td>${peso(i.fare)}</td></tr><tr><td>Weather</td><td>${i.weather}</td></tr></table><div style="margin-top:8px"><small class="muted">Load Forecast ${l}%</small><div class="v8-meter"><i style="width:${l}%;background:${color(l)}"></i></div><small class="muted">Risk Forecast ${r}%</small><div class="v8-meter"><i style="width:${r}%;background:${color(r)}"></i></div></div><div style="display:flex;gap:6px;margin-top:9px;flex-wrap:wrap"><button class="sm primary" onclick="v8OpenVessel('${route}')">Details</button><button class="sm accent" onclick="v8SendToCalc('${route}')">Use Route</button><button class="sm" onclick="v8CreateBoarding('${route}')">Boarding</button></div></div>`;}
  function aiAlerts(){const alerts=[];const s=stats();const high=ROUTES.map(r=>({r,l:load(r),risk:risk(r)})).sort((a,b)=>b.risk-a.risk)[0];if(high.risk>76)alerts.push({type:'danger',msg:`High risk on ${label(high.r)}. Prioritize gate ${INFO[high.r].gate}.`});else if(high.risk>58)alerts.push({type:'warn',msg:`Moderate pressure on ${label(high.r)}. Monitor baggage and queue movement.`});else alerts.push({type:'ok',msg:'All main Cebu routes are under manageable load.'});const heavy=(DB?.history||[]).slice(0,50).filter(h=>Number(h.weight)>70);if(heavy.length)alerts.push({type:'warn',msg:`${heavy.length} recent heavy-baggage transaction(s) detected. Manual scale verification recommended.`});if(s.rev>0)alerts.push({type:'ok',msg:`Revenue monitor active: ${peso(s.rev)} total baggage revenue stored.`});alerts.push({type:'ok',msg:'Original baggage calculator core remains preserved. V8 adds command-center intelligence only.'});return alerts.map(a=>`<div class="v8-alert ${a.type}">${a.msg}</div>`).join('');}
  function renderTicker(){const rows=[];const t=new Date().toLocaleTimeString('en-PH',{hour12:true});rows.push(`[${t}] <b>V8 COMMAND CENTER ONLINE</b>`);ROUTES.slice().sort((a,b)=>risk(b)-risk(a)).slice(0,5).forEach(r=>rows.push(`[${t}] ${INFO[r].vessel} • ${INFO[r].dest} • load ${load(r)}% • risk ${risk(r)}% • gate ${INFO[r].gate}`));rows.push(`[${t}] Port AI: ${recommendation(portMetrics())}`);rows.push(`[${t}] Pack 3 active: Port Congestion + Vessel Cards + Digital Control Room`);return rows.map(x=>`<div>${x}</div>`).join('');}
  window.renderCommand=function(){ensureView();const s=stats();const active=ROUTES.length;const avgRisk=Math.round(ROUTES.reduce((a,r)=>a+risk(r),0)/ROUTES.length);$('view-command').innerHTML=`<div class="card v8-shell"><div class="card-header"><span>🛰️ Digital Command Center V8</span><span class="v8-chip ok">PACK 3 ONLINE</span></div><div class="v8-kpi-grid"><div class="v8-kpi"><b>${s.tx}</b><span>Transactions</span></div><div class="v8-kpi"><b>${peso(s.rev)}</b><span>Baggage Revenue</span></div><div class="v8-kpi"><b>${Number(s.kg||0).toFixed(1)}kg</b><span>Total Baggage</span></div><div class="v8-kpi"><b>${avgRisk}%</b><span>Route Risk Avg</span></div></div></div><div class="v8-command-grid"><div class="card v8-shell"><div class="card-header"><span>🌐 Cebu Route Pulse Map</span><span class="v8-chip">${active} vessels</span></div>${renderPulseMap()}</div><div class="card"><div class="card-header">🚨 AI Operations Alerts</div>${aiAlerts()}<div class="v8-ticker" id="v8Ticker">${renderTicker()}</div></div></div><div class="card v8-shell"><div class="card-header"><span>⚓ Port Congestion Simulator</span><button class="sm accent" onclick="v8RefreshCommand()">Refresh Pulse</button></div>${portPanel()}</div><div class="card"><div class="card-header"><span>⛴ Futuristic Vessel Cards</span><span class="v8-chip">Live Simulation</span></div><div class="v8-vessel-grid">${ROUTES.map(vesselCard).join('')}</div></div>`;};
  window.v8RefreshCommand=function(){renderCommand(); if(typeof toast==='function')toast('V8 port pulse refreshed.');};
  window.v8SendToCalc=function(route){if(typeof showView==='function')showView('calculator');setTimeout(()=>{if($('calcRoute'))$('calcRoute').value=route;if($('weight'))$('weight').focus();if(typeof toast==='function')toast('Route loaded into preserved calculator.');},80);};
  window.v8OpenVessel=function(route){const i=INFO[route];const l=load(route),r=risk(route),m=portMetrics();const old=$('v8Modal');if(old)old.remove();const modal=document.createElement('div');modal.className='v8-modal';modal.id='v8Modal';modal.innerHTML=`<div class="v8-modal-box"><div class="card-header"><span>⛴ ${i.vessel} • ${i.title}</span><button class="sm" onclick="document.getElementById('v8Modal').remove()">✕</button></div><div class="v8-alert ${statusClass(r)}"><b>AI Route Forecast:</b> ${statusText(r)} risk. Gate ${i.gate}. ${i.type}. ${i.weather}.</div><table class="v8-mini-table"><tr><td>Departure</td><td>${i.dep}</td></tr><tr><td>Arrival</td><td>${i.arr}</td></tr><tr><td>Travel Time</td><td>${i.travel}</td></tr><tr><td>Vessel</td><td>${i.vessel}</td></tr><tr><td>TC/OA Fare</td><td>${peso(i.fare)}</td></tr><tr><td>Current Port Queue</td><td>${m.queue}%</td></tr><tr><td>Baggage Counter Load</td><td>${m.counters}%</td></tr></table><div style="margin-top:10px"><small class="muted">Load ${l}%</small><div class="v8-meter"><i style="width:${l}%;background:${color(l)}"></i></div><small class="muted">Risk ${r}%</small><div class="v8-meter"><i style="width:${r}%;background:${color(r)}"></i></div></div><div style="display:flex;gap:8px;margin-top:10px;flex-wrap:wrap"><button class="primary sm" onclick="v8SendToCalc('${route}');document.getElementById('v8Modal').remove()">Use in Calculator</button><button class="accent sm" onclick="v8CreateBoarding('${route}')">Generate Boarding Pass</button></div></div>`;document.body.appendChild(modal);};
  window.v8CreateBoarding=function(route){const i=INFO[route];const code='V8-'+Date.now().toString().slice(-7);const old=$('v8PassModal');if(old)old.remove();const modal=document.createElement('div');modal.className='v8-modal';modal.id='v8PassModal';modal.innerHTML=`<div class="v8-modal-box"><div class="card-header"><span>🎫 Smart Boarding Pass V8</span><button class="sm" onclick="document.getElementById('v8PassModal').remove()">✕</button></div><div class="v8-pass"><h3>OCEAN FAST FERRIES</h3><div class="v8-pass-layout"><div><div class="v8-pass-row"><span>Route</span><b>${i.title}</b></div><div class="v8-pass-row"><span>Vessel</span><b>${i.vessel}</b></div><div class="v8-pass-row"><span>Gate</span><b>${i.gate}</b></div><div class="v8-pass-row"><span>Departure</span><b>${i.dep}</b></div><div class="v8-pass-row"><span>Arrival</span><b>${i.arr}</b></div><div class="v8-pass-row"><span>Trip</span><b>${i.type}</b></div><div class="v8-pass-row"><span>Code</span><b>${code}</b></div></div><div class="v8-qr"></div></div><div style="margin-top:8px;text-align:center;font-weight:900;color:#0e7490">AI Verified • ${statusText(risk(route))} Load</div></div><button class="primary block" style="margin-top:10px" onclick="window.print()">Print Boarding Pass</button></div>`;document.body.appendChild(modal);try{DB.audit=DB.audit||[];DB.audit.unshift({time:new Date().toLocaleString(),action:'V8 boarding pass generated '+code+' for '+i.title,user:currentRole||'system'});saveDB();}catch(e){}};
  function patchDashboard(){if(typeof buildDashboard==='function'&&!window.__v8DashPatched){const old=buildDashboard;window.buildDashboard=buildDashboard=function(){old();const v=$('view-dashboard');if(v&&!$('v8DashCommand')){const m=portMetrics();v.insertAdjacentHTML('beforeend',`<div id="v8DashCommand" class="card v8-shell"><div class="card-header"><span>🛰️ V8 Command Snapshot</span><span class="v8-chip ${statusClass(m.queue)}">Port ${m.queue}%</span></div><div class="v8-kpi-grid"><div class="v8-kpi"><b>${m.queue}%</b><span>Boarding Queue</span></div><div class="v8-kpi"><b>${m.counters}%</b><span>Counter Load</span></div><div class="v8-kpi"><b>${m.transfer}%</b><span>Transfer Pressure</span></div><div class="v8-kpi"><b>${ROUTES.length}</b><span>Vessel Cards</span></div></div><button class="primary block" style="margin-top:10px" onclick="showView('command')">Open Digital Command Center</button></div>`);}};window.__v8DashPatched=true;}}
  function patchAI(){if(typeof aiOfflineRespond==='function'&&!window.__v8AIPatched){const old=aiOfflineRespond;window.aiOfflineRespond=aiOfflineRespond=function(q){const s=String(q||'').toLowerCase();if(/command center|control room|digital command|ops center|operation center/.test(s))return 'V8 Digital Command Center shows Cebu route pulse map, AI alerts, port congestion simulation, and futuristic vessel cards. Open the Command Center tab.';if(/congestion|queue|port load|counter load|pier|terminal/.test(s)){const m=portMetrics();return `Cebu Port Pulse:\nBoarding queue: ${m.queue}%\nBaggage counter load: ${m.counters}%\nTransfer pressure: ${m.transfer}%\nAI recommendation: ${recommendation(m)}`;}if(/vessel|ship|oj |gate|departure|arrival/.test(s)){const found=ROUTES.find(r=>s.includes(INFO[r].dest.toLowerCase())||s.includes(INFO[r].vessel.toLowerCase()));if(found){const i=INFO[found];return `${i.title}\nVessel: ${i.vessel}\nGate: ${i.gate}\nDeparture: ${i.dep}\nArrival: ${i.arr}\nTravel: ${i.travel}\nStatus: ${statusText(risk(found))} risk (${risk(found)}%)`;}}return old(q);};window.__v8AIPatched=true;}}
  function addDockButton(){const dock=$('v7MiniDock');if(dock&&!dock.querySelector('[data-v8-command]'))dock.insertAdjacentHTML('afterbegin','<button data-v8-command onclick="showView(\'command\')">🛰️ Command Center</button>');}
  function boot(){try{ensureView();patchMenu();patchShow();patchDashboard();patchAI();if(typeof buildDrawerMenu==='function')buildDrawerMenu();addDockButton();if($('view-dashboard')?.classList.contains('active')&&currentRole&&typeof showView==='function')showView('dashboard');window.__OFF_PATCH_VERSION=V8_VERSION;try{DB.v8Version=V8_VERSION;saveDB();}catch(e){}}catch(e){console.error('V8 Pack 3 error',e);}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
