
(function(){
  'use strict';
  const PATCH_VERSION='v6-source-clean-plus';
  const MAIN_ROUTES=['cebu_tagbilaran','cebu_maasin','cebu_surigao','cebu_siquijor','cebu_dumaguete','cebu_ormoc','cebu_palompon','cebu_getafe'];
  const CLASS_KEYS=['TC/OA','BC','SC/PWD (BC)','SC/PWD (TC/OA)','ST','MI'];
  const DIRECT_LEG_FARES={
    cebu_tagbilaran:{'TC/OA':1000,'BC':1560,'SC/PWD (BC)':1274.29,'SC/PWD (TC/OA)':714.29,'ST':800,'MI':500},
    tagbilaran_siquijor:{'TC/OA':1000,'BC':1560,'SC/PWD (BC)':1274.29,'SC/PWD (TC/OA)':714.29,'ST':800,'MI':500},
    tagbilaran_dumaguete:{'TC/OA':1170,'BC':1820,'SC/PWD (BC)':1485.71,'SC/PWD (TC/OA)':835.71,'ST':936,'MI':585},
    cebu_getafe:{'TC/OA':585,'BC':1040,'SC/PWD (BC)':872.86,'SC/PWD (TC/OA)':417.86,'ST':468,'MI':292.50},
    cebu_ormoc:{'TC/OA':1430,'BC':1950,'SC/PWD (BC)':1541.43,'SC/PWD (TC/OA)':1021.43,'ST':1144,'MI':715},
    cebu_palompon:{'TC/OA':1430,'BC':1950,'SC/PWD (BC)':1541.43,'SC/PWD (TC/OA)':1021.43,'ST':1144,'MI':715},
    cebu_maasin:{'TC/OA':1430,'BC':1950,'SC/PWD (BC)':1541.43,'SC/PWD (TC/OA)':1021.43,'ST':1144,'MI':715},
    maasin_surigao:{'TC/OA':1040,'BC':1560,'SC/PWD (BC)':1262.86,'SC/PWD (TC/OA)':742.86,'ST':832,'MI':520}
  };
  const ROUTE_PLANS={
    cebu_tagbilaran:{title:'Cebu to Tagbilaran',type:'Direct',legs:['cebu_tagbilaran'],travel:'2h',gate:'A1',zone:'Bohol Lane'},
    cebu_maasin:{title:'Cebu to Maasin',type:'Direct',legs:['cebu_maasin'],travel:'3h',gate:'C1',zone:'Maasin Lane'},
    cebu_surigao:{title:'Cebu to Surigao',type:'Connecting via Maasin',legs:['cebu_maasin','maasin_surigao'],travel:'5h 30m',gate:'C2',zone:'Surigao Connect'},
    cebu_siquijor:{title:'Cebu to Siquijor',type:'Connecting via Tagbilaran',legs:['cebu_tagbilaran','tagbilaran_siquijor'],travel:'4h 20m',gate:'A2',zone:'Siquijor Connect'},
    cebu_dumaguete:{title:'Cebu to Dumaguete',type:'Connecting via Tagbilaran',legs:['cebu_tagbilaran','tagbilaran_dumaguete'],travel:'4h 20m',gate:'A3',zone:'Dumaguete Connect'},
    cebu_ormoc:{title:'Cebu to Ormoc',type:'Direct',legs:['cebu_ormoc'],travel:'3h',gate:'B1',zone:'Ormoc Lane'},
    cebu_palompon:{title:'Cebu to Palompon',type:'Direct',legs:['cebu_palompon'],travel:'3h',gate:'B2',zone:'Palompon Lane'},
    cebu_getafe:{title:'Cebu to Getafe',type:'Direct',legs:['cebu_getafe'],travel:'1h',gate:'D1',zone:'Getafe Lane'}
  };
  const ALIASES={cebu_tagbilaran:['tagbilaran','tagbi','tagb','bohol'],cebu_maasin:['maasin','massin','southern leyte'],cebu_surigao:['surigao'],cebu_siquijor:['siquijor'],cebu_dumaguete:['dumaguete','duma'],cebu_ormoc:['ormoc'],cebu_palompon:['palompon','kalanggaman'],cebu_getafe:['getafe']};
  const REMOVED_ITEMS=['Playables SDK wrapper','duplicate observer add-ons','auto-login bypass','stale Liloan wording','duplicate route tabs','experimental repeated admin cards'];

  const money=n=>(typeof fmtPHP==='function')?fmtPHP(Number(n)||0):'₱'+(Number(n)||0).toFixed(2);
  const byId=id=>document.getElementById(id);
  const normal=s=>String(s||'').toLowerCase().replace(/[^a-z0-9.\s]/g,' ').replace(/\s+/g,' ').trim();
  const label=r=>ROUTE_PLANS[r]?.title || (DB.schedules?.[r]?.title) || String(r).replace(/_/g,' to ').replace(/\b\w/g,m=>m.toUpperCase());
  const routeOptions=sel=>MAIN_ROUTES.map(r=>`<option value="${r}" ${sel===r?'selected':''}>${label(r)}</option>`).join('');
  const classOptions=sel=>CLASS_KEYS.map(c=>`<option value="${c}" ${sel===c?'selected':''}>${c}</option>`).join('');
  function toastV6(msg){ if(typeof toast==='function') toast(msg); }
  function addAudit(action){DB.audit=DB.audit||[];DB.audit.unshift({time:new Date().toLocaleString(),action,user:window.currentRole||currentRole||'system'});DB.audit=DB.audit.slice(0,250);saveDB();}
  function fareSum(route,cls){const plan=ROUTE_PLANS[route];if(!plan)return{total:0,legs:[]};const legs=plan.legs.map(k=>({key:k,label:label(k),fare:Number((DIRECT_LEG_FARES[k]||{})[cls]??(DIRECT_LEG_FARES[k]||{})['TC/OA']??0)}));return{total:Number(legs.reduce((a,b)=>a+b.fare,0).toFixed(2)),legs};}
  function routeFareObject(route){const o={};CLASS_KEYS.forEach(c=>o[c]=fareSum(route,c).total);return o;}
  function findRoute(text){const q=normal(text);if(q.includes('liloan'))return'liloan';for(const r of MAIN_ROUTES){if(q.includes(r.replace(/_/g,' '))||q.includes(label(r).toLowerCase()))return r;const dest=r.replace('cebu_','');if(q.includes(dest))return r;for(const a of ALIASES[r]||[])if(q.includes(normal(a)))return r;}return null;}
  function detectFareClass(text){const q=normal(text);if(q.includes('business')||/\bbc\b/.test(q))return'BC';if(q.includes('student')||/\bst\b/.test(q))return'ST';if(q.includes('minor')||q.includes('military')||/\bmi\b/.test(q))return'MI';if(q.includes('pwd')||q.includes('senior')||/\bsc\b/.test(q))return(q.includes('business')||/\bbc\b/.test(q))?'SC/PWD (BC)':'SC/PWD (TC/OA)';return'TC/OA';}
  function syncCoreData(){
    if(!window.DB&&typeof DB!=='undefined')window.DB=DB;
    DB.audit=DB.audit||[];DB.seasonal=DB.seasonal||{};DB.routePlans=ROUTE_PLANS;DB.v6Removed=REMOVED_ITEMS;
    delete DB.slabs.cebu_liloan;delete DB.slabs.liloan_cebu;delete DB.paxFares.cebu_liloan;delete DB.paxFares.liloan_cebu;delete DB.schedules.cebu_liloan;delete DB.schedules.liloan_cebu;
    MAIN_ROUTES.forEach(r=>{DB.paxFares[r]=routeFareObject(r);DB.schedules[r]=DB.schedules[r]||{title:label(r),travel:ROUTE_PLANS[r].travel,trips:[]};DB.schedules[r].title=label(r);DB.schedules[r].travel=ROUTE_PLANS[r].travel;});
    Object.keys(DIRECT_LEG_FARES).forEach(k=>{DB.paxFares[k]=DIRECT_LEG_FARES[k];});
    ['cebu_surigao','cebu_siquijor','cebu_dumaguete'].forEach(r=>{(DB.schedules[r]?.trips||[]).forEach(t=>{if(!t.remarks)t.remarks=ROUTE_PLANS[r].type;});});
    saveDB();
  }

  function patchDrawer(){
    window.buildDrawerMenu=buildDrawerMenu=function(){
      const items=[{view:'dashboard',icon:'🏠',label:'Dashboard'},{view:'calculator',icon:'🧮',label:'Baggage + Trip Total'},{view:'ar',icon:'📷',label:'AR Scanner'},{view:'map',icon:'🗺️',label:'Live Map'},{view:'fares',icon:'💵',label:'Cebu Fare Matrix'},{view:'schedules',icon:'🕐',label:'Cebu Schedules'},{view:'history',icon:'📋',label:'History'}];
      if(currentRole==='supervisor')items.push({view:'admin',icon:'🔐',label:'Admin Panel'});
      byId('drawerMenu').innerHTML=items.map(i=>`<div class="drawer-item" data-view="${i.view}" onclick="navigate('${i.view}')"><i>${i.icon}</i> ${i.label}</div>`).join('');
    };
  }

  function enhanceCalcRouteOptions(){const sel=byId('calcRoute');if(!sel)return;const current=MAIN_ROUTES.includes(sel.value)?sel.value:'cebu_tagbilaran';sel.innerHTML=routeOptions(current);sel.value=current;sel.onchange=()=>{renderTripQuote();};}
  function injectTripQuoteControls(){
    if(byId('v6TripQuoteCard'))return;
    const result=byId('resultCard');if(!result)return;
    const card=document.createElement('div');card.className='card neo-card';card.id='v6TripQuoteCard';
    card.innerHTML=`<div class="card-header"><span>🧾 Smart Trip Total</span><span class="neo-chip">Pax + baggage</span></div><div class="grid2"><div class="input-group"><label>Passenger fare class</label><select id="v6FareClass" onchange="renderTripQuote()">${classOptions('TC/OA')}</select></div><div class="input-group"><label>Include fare in grand total</label><select id="v6IncludeFare" onchange="renderTripQuote()"><option value="yes">Yes</option><option value="no">Baggage only</option></select></div></div><div id="v6TripQuote" class="fare-breakdown v6-warn">Compute baggage first to see passenger fare + baggage grand total.</div><div class="grid2"><button class="sm accent block" onclick="copyTripQuote()">Copy Quote</button><button class="sm primary block" onclick="openCommandPalette()">Ask AI / Command</button></div>`;
    result.parentNode.insertBefore(card,result.nextSibling);
  }
  function readBaggageTotal(){const txt=byId('totalDisplay')?.textContent||'0';return Number(txt.replace(/[^0-9.]/g,''))||0;}
  window.renderTripQuote=function(){
    const box=byId('v6TripQuote');if(!box)return;
    const route=byId('calcRoute')?.value||'cebu_tagbilaran';const fareClass=byId('v6FareClass')?.value||'TC/OA';const include=byId('v6IncludeFare')?.value!=='no';const mode=byId('calcMode')?.value||'normal';const pax=mode==='normal'?(parseInt(byId('pax')?.value,10)||1):1;const baggage=readBaggageTotal();const f=fareSum(route,fareClass);const passenger=f.total*pax;const grand=include?passenger+baggage:baggage;
    const legHtml=f.legs.map(l=>`<div class="quote-line"><span>↳ ${l.label}</span><strong>${money(l.fare)} × ${pax}</strong></div>`).join('');
    box.innerHTML=`<b>${label(route)}</b> <span class="${f.legs.length>1?'badge-connect':'badge-direct'}">${ROUTE_PLANS[route].type}</span><br><div class="quote-line"><span>Passenger fare (${fareClass})</span><strong>${money(f.total)} / pax</strong></div>${legHtml}<div class="quote-line"><span>Passenger subtotal</span><strong>${money(passenger)}</strong></div><div class="quote-line"><span>Baggage fee</span><strong>${money(baggage)}</strong></div><hr style="border-color:var(--border);margin:7px 0"><div class="quote-line"><span>Grand total</span><span class="quote-total">${money(grand)}</span></div><small style="color:var(--text3)">Gate ${ROUTE_PLANS[route].gate} • ${ROUTE_PLANS[route].zone} • ${ROUTE_PLANS[route].travel}</small>`;
    window.__lastTripQuote=`${label(route)}\nClass: ${fareClass}\nPax: ${pax}\nPassenger subtotal: ${money(passenger)}\nBaggage fee: ${money(baggage)}\nGrand total: ${money(grand)}\n${f.legs.map(l=>l.label+': '+money(l.fare)).join('\n')}`;
    const receipt=byId('receipt');if(receipt&&receipt.style.display!=='none'&&!receipt.querySelector('.v6-receipt-note'))receipt.insertAdjacentHTML('beforeend',`<div class="v6-receipt-note"><b>Trip total:</b> Passenger subtotal ${money(passenger)} + baggage ${money(baggage)} = <b>${money(grand)}</b></div>`);
  };
  window.copyTripQuote=function(){const t=window.__lastTripQuote||'No quote yet.';if(navigator.clipboard)navigator.clipboard.writeText(t).then(()=>toastV6('Trip quote copied.')).catch(()=>toastV6('Copy not supported.'));else toastV6(t);};
  function patchCalculator(){
    const oldBuild=buildCalculator;window.buildCalculator=buildCalculator=function(){oldBuild();enhanceCalcRouteOptions();injectTripQuoteControls();setTimeout(renderTripQuote,30);};
    const oldCompute=compute;window.compute=compute=function(override=null){const r=oldCompute(override);setTimeout(renderTripQuote,40);return r;};
    const oldAdjust=cashierAdjust;window.cashierAdjust=cashierAdjust=function(){const r=oldAdjust();setTimeout(renderTripQuote,50);return r;};
  }

  function renderFarePlanner(){const r=byId('v6FareRoute')?.value||'cebu_tagbilaran';const c=byId('v6PlannerClass')?.value||'TC/OA';const pax=parseInt(byId('v6PlannerPax')?.value,10)||1;const f=fareSum(r,c);byId('v6FarePlannerOut').innerHTML=`<div class="fare-breakdown"><b>${label(r)}</b><br>${ROUTE_PLANS[r].type} • ${ROUTE_PLANS[r].travel}<br>${f.legs.map(l=>`↳ ${l.label}: ${money(l.fare)}`).join('<br>')}<hr style="border-color:var(--border);margin:7px 0">${c}: ${money(f.total)} × ${pax} pax = <b style="color:var(--accent)">${money(f.total*pax)}</b></div>`;}
  window.renderV6FarePlanner=renderFarePlanner;
  function patchFares(){
    window.buildFares=buildFares=function(){byId('view-fares').innerHTML=`<div class="card neo-card"><div class="card-header"><span>💵 Cebu Fare Matrix</span><span class="neo-chip">Main routes only</span></div><div class="grid2"><div class="input-group"><label>Route</label><select id="v6FareRoute" onchange="renderV6FarePlanner()">${routeOptions('cebu_tagbilaran')}</select></div><div class="input-group"><label>Passenger Class</label><select id="v6PlannerClass" onchange="renderV6FarePlanner()">${classOptions('TC/OA')}</select></div><div class="input-group"><label>Passengers</label><input id="v6PlannerPax" type="number" value="1" min="1" oninput="renderV6FarePlanner()"></div><div class="input-group"><label>Quick action</label><button class="primary block" onclick="renderV6FarePlanner()">Calculate</button></div></div><div id="v6FarePlannerOut"></div></div><div class="card"><div class="card-header">🧮 All Main Cebu Passenger Fares</div><div class="matrix-table"><table><thead><tr><th>Route</th>${CLASS_KEYS.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${MAIN_ROUTES.map(r=>`<tr><td><b>${label(r)}</b><br><small style="color:var(--text3)">${ROUTE_PLANS[r].type}</small></td>${CLASS_KEYS.map(c=>`<td>${money(fareSum(r,c).total)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div><div class="card"><div class="card-header">🔗 Connection Logic</div>${MAIN_ROUTES.filter(r=>ROUTE_PLANS[r].legs.length>1).map(r=>`<div class="fare-breakdown"><b>${label(r)}</b><br>${ROUTE_PLANS[r].legs.map(l=>label(l)).join(' + ')}</div>`).join('')}</div>`;renderFarePlanner();};
  }

  function patchSchedules(){
    window.buildSchedules=buildSchedules=function(){byId('view-schedules').innerHTML=`<div class="card neo-card"><div class="card-header"><span>🕐 Cebu Main Route Schedules</span><span class="neo-chip">No duplicates</span></div><select id="schedRoute" onchange="renderSchedule()">${routeOptions('cebu_tagbilaran')}</select><div id="schedList"></div></div>`;renderSchedule();};
    window.renderSchedule=renderSchedule=function(){const r=byId('schedRoute')?.value||'cebu_tagbilaran';const s=DB.schedules[r]||{trips:[]};const f=fareSum(r,'TC/OA');byId('schedList').innerHTML=`<div class="fare-breakdown"><b>${label(r)}</b><br>${ROUTE_PLANS[r].type} • Travel time: ${ROUTE_PLANS[r].travel}<br>Gate: ${ROUTE_PLANS[r].gate} • Zone: ${ROUTE_PLANS[r].zone}<br>Tourist fare: <b>${money(f.total)}</b><br>${f.legs.map(l=>`↳ ${l.label}: ${money(l.fare)}`).join('<br>')}</div>${s.trips?.length?s.trips.map(t=>`<div class="trip-row"><b>${t.dep}</b> → <b>${t.arr||''}</b> | ${t.vessel}${t.remarks?`<br><small style="color:var(--text3)">📌 ${t.remarks}</small>`:''}</div>`).join(''):'<p style="color:var(--text3);margin-top:8px">No saved trip schedule for this route yet.</p>'}`;};
  }

  function routeOrbitHtml(){return MAIN_ROUTES.map((r,i)=>{const count=DB.stats.routeCounts?.[r]||0;const f=fareSum(r,'TC/OA');const pct=Math.min(100,10+count*12+i*5);return`<div class="v6-node"><b>${label(r)}</b><div>${ROUTE_PLANS[r].type}</div><div class="v6-price">${money(f.total)}</div><div class="mini-meter"><span style="width:${pct}%"></span></div><small style="color:var(--text3)">Gate ${ROUTE_PLANS[r].gate} • ${count} txn</small></div>`;}).join('');}
  function patchDashboard(){const old=buildDashboard;window.buildDashboard=buildDashboard=function(){old();const v=byId('view-dashboard');if(!v||byId('v6DashDeck'))return;const peak=MAIN_ROUTES.map(r=>({r,score:(DB.schedules[r]?.trips?.length||0)*20+(DB.stats.routeCounts?.[r]||0)*10+(ROUTE_PLANS[r].legs.length>1?18:0)})).sort((a,b)=>b.score-a.score)[0];v.insertAdjacentHTML('beforeend',`<div id="v6DashDeck"><div class="card neo-card scanline"><div class="card-header"><span>🧠 Route Intelligence V6</span><span class="neo-chip">Source-based</span></div><div class="v6-grid">${routeOrbitHtml()}</div></div><div class="card"><div class="card-header">🧹 Cleanup Report</div>${REMOVED_ITEMS.map(x=>`<div class="fare-breakdown v6-clean">✅ Removed: ${x}</div>`).join('')}<div class="fare-breakdown v6-warn">Calculator preserved: slabCost(), compute(), cashierAdjust(), and original receipt generation.</div></div><div class="card"><div class="card-header">⚓ Predictive Operations</div><div class="v6-grid3"><div class="ops-cell"><b>${peak?label(peak.r).split(' to ')[1]:'--'}</b>Peak Route</div><div class="ops-cell"><b>${peak?ROUTE_PLANS[peak.r].gate:'--'}</b>Next Gate</div><div class="ops-cell"><b>${DB.history?.length||0}</b>Saved Logs</div></div></div></div>`);};}

  function patchAdmin(){
    window.buildAdmin=buildAdmin=function(){if(currentRole!=='supervisor'){byId('loginOverlay').style.display='flex';toastV6('Supervisor login required');return;}byId('view-admin').innerHTML=`<div class="card neo-card"><div class="card-header">🔐 Admin Control Center V6</div><div class="grid2" style="margin-bottom:12px"><button class="accent sm block" onclick="v6Admin('slabs')">Slabs</button><button class="accent sm block" onclick="v6Admin('fares')">Leg Fares</button><button class="accent sm block" onclick="v6Admin('exports')">Exports</button><button class="accent sm block" onclick="v6Admin('audit')">Audit</button></div><div id="adminContent"></div></div>`;v6Admin('slabs');};
    window.v6Admin=function(section){const box=byId('adminContent');if(!box)return;if(section==='slabs'){box.innerHTML=`<div class="card-header">📦 Main Cebu Slab Editor</div><div class="input-group"><label>Route</label><select id="v6SlabRoute" onchange="loadV6Slabs()">${routeOptions('cebu_tagbilaran')}</select></div><div class="v6-grid3">${['Normal 1-10kg','Normal 11-40kg','Normal 41kg+','Fragile 1-10kg','Fragile 11-40kg','Fragile 41kg+'].map((l,i)=>`<div class="input-group"><label>${l}</label><input type="number" step="0.01" id="v6s${i}"></div>`).join('')}</div><button class="primary block" onclick="saveV6Slabs()">Save Slabs Without Changing Calculator Logic</button>`;loadV6Slabs();}
      else if(section==='fares'){box.innerHTML=`<div class="card-header">💵 Direct Leg Fare Editor</div><div class="input-group"><label>Direct leg</label><select id="v6LegKey" onchange="loadV6LegFares()">${Object.keys(DIRECT_LEG_FARES).map(k=>`<option value="${k}">${label(k)}</option>`).join('')}</select></div><div class="v6-grid3">${CLASS_KEYS.map((c,i)=>`<div class="input-group"><label>${c}</label><input type="number" step="0.01" id="v6f${i}"></div>`).join('')}</div><button class="primary block" onclick="saveV6LegFares()">Save Leg + Recalculate Connecting Routes</button><div class="fare-breakdown">Connecting routes are recalculated automatically from their legs.</div>`;loadV6LegFares();}
      else if(section==='exports'){box.innerHTML=`<div class="card-header">📤 Export + Maintenance</div><div class="grid2"><button class="primary block" onclick="exportV6CSV()">Export CSV Manifest</button><button class="accent block" onclick="exportDatabase()">Export JSON Backup</button><button class="accent block" onclick="restoreV6Core()">Restore Main Cebu Fares</button><button class="danger block" onclick="resetApp()">Reset App</button></div><div class="fare-breakdown v6-clean">This V6 build removed unnecessary duplicate code but preserved the baggage calculator.</div>`;}
      else{box.innerHTML=`<div class="card-header">📜 Audit Trail</div><div style="max-height:360px;overflow:auto">${(DB.audit||[]).map(a=>`<div class="history-row"><b>${a.time}</b><br>${a.action}<br><small style="color:var(--text3)">${a.user||'system'}</small></div>`).join('')||'<p style="color:var(--text3)">No audit logs yet.</p>'}</div>`;}};
    window.loadV6Slabs=function(){const r=byId('v6SlabRoute')?.value||'cebu_tagbilaran';const s=DB.slabs[r];if(!s)return;[...s.normal,...s.fragile].forEach((v,i)=>byId('v6s'+i).value=v);};
    window.saveV6Slabs=function(){const r=byId('v6SlabRoute').value;DB.slabs[r]={normal:[0,1,2].map(i=>Number(byId('v6s'+i).value)||0),fragile:[3,4,5].map(i=>Number(byId('v6s'+i).value)||0)};addAudit('Updated V6 slab rates for '+label(r));saveDB();toastV6('Slab rates saved.');};
    window.loadV6LegFares=function(){const k=byId('v6LegKey')?.value||'cebu_tagbilaran';CLASS_KEYS.forEach((c,i)=>byId('v6f'+i).value=DIRECT_LEG_FARES[k][c]||0);};
    window.saveV6LegFares=function(){const k=byId('v6LegKey').value;CLASS_KEYS.forEach((c,i)=>{DIRECT_LEG_FARES[k][c]=Number(byId('v6f'+i).value)||0;});syncCoreData();addAudit('Updated direct leg fares for '+label(k));toastV6('Leg fares saved and connection totals recalculated.');};
  }
  window.exportV6CSV=function(){const rows=[['ID','Time','Route','Mode','Class','Pax','Weight','BaggageTotal']].concat((DB.history||[]).map((h,i)=>[i+1,h.time||'',label(h.route),h.mode||'',h.cls||'',h.pax||'',h.weight||'',h.total||'']));const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='ocean_ferries_v6_manifest.csv';a.click();URL.revokeObjectURL(a.href);toastV6('CSV exported.');};
  window.restoreV6Core=function(){syncCoreData();toastV6('V6 main Cebu data restored.');if(byId('view-fares')?.classList.contains('active'))buildFares();};

  function aiFare(q){const r=findRoute(q);if(r==='liloan')return'Cebu to Liloan is removed/not included. Main Cebu routes are Tagbilaran, Maasin, Surigao, Siquijor, Dumaguete, Ormoc, Palompon, and Getafe.';if(!r)return'Mention the route, example: fare Cebu to Dumaguete or student fare Cebu to Siquijor.';const cls=detectFareClass(q);const f=fareSum(r,cls);return`${label(r)} fare (${cls}): ${money(f.total)}\n${ROUTE_PLANS[r].type} • ${ROUTE_PLANS[r].travel}\n${f.legs.map(l=>'• '+l.label+': '+money(l.fare)).join('\n')}`;}
  function aiSchedule(q){const r=findRoute(q);if(!r||r==='liloan')return'Please mention one main Cebu route: Tagbilaran, Maasin, Surigao, Siquijor, Dumaguete, Ormoc, Palompon, or Getafe.';const s=DB.schedules[r];return`${label(r)} schedule:\n${ROUTE_PLANS[r].type} • ${ROUTE_PLANS[r].travel} • ${ROUTE_PLANS[r].gate}\n${s?.trips?.length?s.trips.slice(0,8).map(t=>'• '+t.dep+' → '+t.arr+' | '+t.vessel+(t.remarks?' | '+t.remarks:'')).join('\n'):'No saved trip schedule yet.'}`;}
  function aiBaggage(q){const kg=(q.match(/(\d+(?:\.\d+)?)\s*(kg|kilo|kilos)/i)||[])[1];if(!kg)return'Include weight, example: 2 pax 45kg Cebu to Ormoc or fragile 20kg Cebu to Getafe.';const r=findRoute(q);if(r==='liloan')return'Cebu to Liloan is not included.';const route=r||'cebu_tagbilaran';const pax=Number((q.match(/(\d+)\s*(pax|passenger|passengers)/i)||[])[1]||1);const mode=/fragile|cargo/i.test(q)?'fragile':'normal';const cls=/business|bc/i.test(q)?'business':'tourist';try{const free=mode==='normal'?DB.freeAllowance[cls]:0;const freeTotal=free*pax;const excess=Math.max(0,Number(kg)-freeTotal);const E=mode==='normal'?excess/pax:Number(kg);const slab=slabCost(E,DB.slabs[route][mode]);const baggage=mode==='normal'?slab.total*pax:slab.total;const fareClass=detectFareClass(q);const passenger=fareSum(route,fareClass).total*pax;return`Trip estimate for ${label(route)}:\nPassenger fare (${fareClass}): ${money(passenger)}\nBaggage fee: ${money(baggage)}\nGrand total: ${money(passenger+baggage)}\nFree baggage: ${freeTotal}kg\nChargeable: ${E.toFixed(2)}kg`; }catch(e){return'Cannot compute because a slab rate is missing.';}}
  function patchAI(){if(typeof aiOfflineRespond==='function'){window.aiOfflineRespond=aiOfflineRespond=function(q){const s=normal(q);if(!s)return'Please type your question.';if(/^(hi|hello|hey)/.test(s))return'Hello! I am the Ocean Fast Ferries V6 AI. Ask about fares, schedules, baggage fees, passenger + baggage grand totals, gates, and connection legs.';if(s.includes('liloan'))return'Cebu to Liloan was removed/not included. Main routes: Tagbilaran, Maasin, Surigao, Siquijor, Dumaguete, Ormoc, Palompon, and Getafe.';if(/schedule|trip|depart|arrival|vessel|time/.test(s))return aiSchedule(q);if(/fare|ticket|price|how much/.test(s)&&!/kg|baggage|bag|cargo/.test(s))return aiFare(q);if(/kg|baggage|bag|luggage|cargo|fragile|compute|calculate|grand total|quote/.test(s))return aiBaggage(q);if(/connect|connecting|via|transfer/.test(s))return'Cebu to Dumaguete = Cebu→Tagbilaran + Tagbilaran→Dumaguete. Cebu to Siquijor = Cebu→Tagbilaran + Tagbilaran→Siquijor. Cebu to Surigao = Cebu→Maasin + Maasin→Surigao.';if(/route|destination|where.*go/.test(s))return'Main Cebu routes only: Cebu to Tagbilaran, Maasin, Surigao, Siquijor, Dumaguete, Ormoc, Palompon, and Getafe.';if(/free|allowance/.test(s))return'Tourist/Open Air has 10kg free per pax. Business has 20kg free per pax. Fragile cargo has no free allowance.';if(/removed|cleanup|delete|clean/.test(s))return'V6 removed duplicate add-on code, stale Liloan wording, auto-login bypass, duplicate route tabs, and repeated admin widgets. The original baggage calculator logic is preserved.';if(/help|what can you/.test(s))return'Try: fare Cebu to Dumaguete, 2 pax 45kg Cebu to Ormoc, fragile 20kg Cebu to Getafe, Cebu to Siquijor schedule, connection rules, or cleanup report.';return'I can answer Ocean Fast Ferries questions about fares, schedules, baggage, routes, gates, discounts, connections, and trip totals.';};}}

  window.openCommandPalette=function(){const old=byId('v6CommandPalette');if(old){old.remove();return;}const el=document.createElement('div');el.className='command-palette';el.id='v6CommandPalette';el.innerHTML=`<div class="command-box"><div class="card-header"><span>⚡ Command Center</span><button class="sm" onclick="document.getElementById('v6CommandPalette').remove()">✕</button></div><input id="v6CmdInput" placeholder="Ask: fare Cebu to Siquijor, 2 pax 45kg Ormoc..." onkeydown="if(event.key==='Enter')runV6Command()"><div><div class="command-row" onclick="showView('calculator');document.getElementById('v6CommandPalette').remove()"><b>Open Trip Calculator</b><span>🧮</span></div><div class="command-row" onclick="showView('fares');document.getElementById('v6CommandPalette').remove()"><b>Open Fare Matrix</b><span>💵</span></div><div class="command-row" onclick="showView('schedules');document.getElementById('v6CommandPalette').remove()"><b>Open Main Schedules</b><span>🕐</span></div></div></div>`;document.body.appendChild(el);setTimeout(()=>byId('v6CmdInput')?.focus(),50);};
  window.runV6Command=function(){const q=byId('v6CmdInput')?.value||'';byId('v6CommandPalette')?.remove();if(!q.trim())return;if(!byId('chatPanel')?.classList.contains('open'))toggleChat();addChatMsg('user',q);addChatMsg('bot',aiOfflineRespond(q));};
  function floatingTools(){if(byId('v6FloatTools'))return;const div=document.createElement('div');div.id='v6FloatTools';div.className='v6-floating-tools';div.innerHTML=`<button onclick="openCommandPalette()">⚡ Command</button><button onclick="showView('calculator')">🧮 Calculator</button><button onclick="showView('fares')">💵 Fares</button>`;document.body.appendChild(div);}
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommandPalette();}});

  function boot(){try{syncCoreData();patchDrawer();patchCalculator();patchFares();patchSchedules();patchDashboard();patchAdmin();patchAI();floatingTools();if(typeof buildDrawerMenu==='function')buildDrawerMenu();if(byId('view-dashboard')?.classList.contains('active')&&currentRole)showView('dashboard');window.__OFF_PATCH_VERSION=PATCH_VERSION;}catch(e){console.error('V6 patch error',e);}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
