
(function(){
  'use strict';
  if(window.__OFF_V26_REAL__) return;
  window.__OFF_V26_REAL__ = true;
  const VERSION='V26_REAL_EXPERIENCE_EFFICIENCY';
  const KEYS={
    claims:'oj_v22_claims', damage:'oj_damage_master_log_v11', tickets:'oj_v24_service_tickets', feedback:'oj_v24_feedback',
    notices:'oj_v25_public_notices', prefs:'oj_v26_prefs', messages:'oj_v26_interaction_messages', journeys:'oj_v26_journeys', sync:'oj_v26_sync_queue', audit:'oj_v26_audit_log'
  };
  const $=id=>document.getElementById(id);
  const qsa=(s,root=document)=>Array.from(root.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const now=()=>new Date().toLocaleString('en-PH',{timeZone:'Asia/Manila',hour12:true});
  const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'});
  const uid=p=>p+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,5).toUpperCase();
  function load(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){return f}}
  function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){audit('storage_error',e.message);return false}}
  function toast(msg){try{if(typeof window.toast==='function') return window.toast(msg);}catch(e){} const t=document.createElement('div');t.textContent=msg;t.style.cssText='position:fixed;left:50%;bottom:20px;transform:translateX(-50%);z-index:99999;background:#101a33;color:white;border:1px solid #7df9ff;border-radius:999px;padding:10px 14px;font:700 12px system-ui;box-shadow:0 8px 25px #0008';document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
  function audit(type,msg){const rows=load(KEYS.audit,[]);rows.unshift({id:uid('AUD'),type,msg:String(msg||''),at:now(),online:navigator.onLine});save(KEYS.audit,rows.slice(0,160));}
  function ensureView(name){let v=$('view-'+name);if(!v){v=document.createElement('div');v.id='view-'+name;v.className='view';(document.querySelector('.app')||document.body).appendChild(v);}return v;}
  function openClaims(){const a=load(KEYS.claims,[]),b=load(KEYS.damage,[]);return [...a,...b].filter(c=>!['Closed','Resolved','Rejected','Done'].includes(String(c.status||'New')));}
  function allClaims(){return [...load(KEYS.claims,[]),...load(KEYS.damage,[])];}
  function getPrefs(){return load(KEYS.prefs,{fast:false,autosync:true,coach:true,lastBackup:''})}
  function setPrefs(p){save(KEYS.prefs,p);document.body.classList.toggle('v26-fast-mode',!!p.fast)}
  function adminUnlocked(){try{return sessionStorage.getItem('oj_v22_admin_unlocked')==='1'||localStorage.getItem('oj_v22_admin_unlocked')==='1'}catch(e){return false}}
  function storageInfo(){let total=0;const rows=[];try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';const v=localStorage.getItem(k)||'';const b=(k.length+v.length)*2;total+=b;rows.push({k,b});}}catch(e){}return{bytes:total,mb:total/1024/1024,pct:Math.min(100,Math.round(total/(4.8*1024*1024)*100)),rows:rows.sort((a,b)=>b.b-a.b)}}
  function claimRisk(c){const text=JSON.stringify(c).toLowerCase();let n=15;if(/critical|urgent|wet|missing|crack|broken|wheel|handle/.test(text))n+=35;if(!(c.tagNo||c.tag))n+=12;if(!(c.lastName||c.name))n+=10;if(!(c.contact||c.phone))n+=10;if(String(c.status||'New')==='New')n+=8;return Math.min(100,n)}
  function routeLabel(r){try{if(typeof window.label==='function')return window.label(r)}catch(e){} return String(r||'All routes').replace(/_/g,' → ').replace(/\b\w/g,c=>c.toUpperCase())}
  function metrics(){const claims=openClaims();const urgent=claims.filter(c=>claimRisk(c)>=65).length;const sync=load(KEYS.sync,[]);const st=storageInfo();const msgs=load(KEYS.messages,[]).filter(m=>!m.done);const score=Math.max(0,100-urgent*9-sync.length*3-Math.max(0,st.pct-72));return{claims,urgent,sync,st,msgs,score}}
  function cardKpis(m){return `<div class="v26-grid" style="margin-top:12px"><div class="v26-kpi"><b>${m.claims.length}</b><span>Open Claims</span></div><div class="v26-kpi"><b>${m.urgent}</b><span>Urgent</span></div><div class="v26-kpi"><b>${m.sync.length}</b><span>Pending Sync</span></div><div class="v26-kpi"><b>${m.score}%</b><span>Readiness</span></div></div>`}
  function renderExperienceHome(){const m=metrics();ensureView('experience').innerHTML=`
    <div class="card v26-shell"><div class="v26-hero"><h1>✨ V26 Experience Command</h1><p>Mobile-first hub for passengers, baggage staff, cashier, and supervisors. Focused on speed, clear next steps, offline safety, and no blank-screen recovery.</p></div>${cardKpis(m)}<div class="v26-meter" style="margin-top:10px"><span style="width:${m.score}%"></span></div></div>
    <div class="card"><div class="card-header">Fast Role Actions</div><div class="v26-action-grid">
      ${action('👤','Passenger Journey','Guided fare, schedule, claim, and help path','journey')}
      ${action('💬','Interaction Hub','Local staff-passenger message board','interaction')}
      ${action('🔁','Sync Queue','Offline pending records and backup flow','sync')}
      ${action('🧪','Site Test','One-tap check for mobile deployment','site-test')}
      ${action('🧳','Claim Center','Track, triage, and update claim status','claimstatus')}
      ${action('🧮','Baggage Calc','Official baggage calculation tab','calculator')}
    </div></div>
    <div class="card"><div class="card-header">Today\'s Smart Suggestions</div>${suggestions(m)}</div><div class="v26-bottom-space"></div>`;}
  function action(ico,title,sub,view){return `<button class="v26-action" onclick="showView('${view}')"><span class="ico">${ico}</span><b>${esc(title)}</b><small>${esc(sub)}</small></button>`}
  function suggestions(m){const rows=[];if(m.urgent)rows.push(['red','Prioritize urgent claims',m.urgent+' open claim(s) need supervisor review.','queuemanager']);if(m.sync.length)rows.push(['amber','Sync pending records',m.sync.length+' local record(s) waiting for export/sync.','sync']);if(m.st.pct>72)rows.push(['amber','Storage getting high','Create a lean backup and clean duplicate data.','readiness']);if(!rows.length)rows.push(['green','Ready for field use','No critical local issues detected.','site-test']);return rows.map(r=>`<div class="v26-row"><div><strong>${esc(r[1])}</strong><small>${esc(r[2])}</small></div><button class="sm" onclick="showView('${r[3]}')">Open</button></div>`).join('')}
  function renderJourney(){const journeys=load(KEYS.journeys,[]);ensureView('journey').innerHTML=`
    <div class="card v26-shell"><div class="v26-title"><div><h2>👤 Passenger Journey Builder</h2><small>Guides a passenger to the correct tool without exposing staff/admin clutter.</small></div><span class="v26-chip pink">Public</span></div></div>
    <div class="card"><div class="card-header">What do you need?</div><div class="v26-action-grid">
      ${action('💵','Check Fare','Open fare matrix and trip info','fares')}
      ${action('🕐','Check Schedule','Open schedule board','schedules')}
      ${action('🧳','Report Baggage Issue','Open damage/lost baggage forms','portal')}
      ${action('🔎','Track Claim','Search claim number/status','claimstatus')}
      ${action('📢','Read Notices','View route and port advisories','noticeboard')}
      ${action('🗺️','Live Map','View vessel/route command map','map')}
    </div></div>
    <div class="card"><div class="card-header">Create Visit Guide</div>${journeyForm()}</div>
    <div class="card"><div class="card-header">Recent Visit Guides</div>${journeys.length?journeys.slice(0,6).map(journeyRow).join(''):'<p class="muted">No visit guides yet.</p>'}</div><div class="v26-bottom-space"></div>`;}
  function journeyForm(){return `<div class="grid2"><div class="input-group"><label>Name optional</label><input id="v26JName" placeholder="Passenger name"></div><div class="input-group"><label>Route</label><select id="v26JRoute">${routesHtml()}</select></div></div><div class="grid2"><div class="input-group"><label>Purpose</label><select id="v26JPurpose"><option>Check baggage fee</option><option>Damage claim</option><option>Lost baggage</option><option>Schedule/fare inquiry</option><option>Port assistance</option></select></div><div class="input-group"><label>Contact optional</label><input id="v26JContact" placeholder="Phone or email"></div></div><button class="primary block" onclick="v26CreateJourney()">Generate Next-Step Guide</button>`}
  function routesHtml(){const r=['cebu_tagbilaran','cebu_maasin','cebu_surigao','cebu_siquijor','cebu_dumaguete','cebu_ormoc','cebu_palompon','cebu_getafe'];return r.map(x=>`<option value="${x}">${esc(routeLabel(x))}</option>`).join('')}
  function journeyRow(j){return `<div class="v26-row"><div><strong>${esc(j.id)} • ${esc(j.purpose)}</strong><small>${esc(routeLabel(j.route))} • ${esc(j.createdAt)}<br>${esc(j.next)}</small></div><button class="sm" onclick="v26Copy('${esc(j.id)}')">Copy ID</button></div>`}
  window.v26CreateJourney=function(){const rows=load(KEYS.journeys,[]);const purpose=$('v26JPurpose')?.value||'Port assistance';const route=$('v26JRoute')?.value||'cebu_tagbilaran';const next=purpose.includes('Damage')?'Open Baggage Damage Detector, capture claim stub, full baggage, and close-up damage.':purpose.includes('Lost')?'Open lost baggage form, record tag number, route, last seen area, and contact number.':purpose.includes('fee')?'Open Baggage Calc and let cashier confirm official weight and route.':'Check schedule/fare tabs, then ask staff if route notice is active.';const item={id:uid('VISIT'),name:$('v26JName')?.value.trim()||'Passenger',contact:$('v26JContact')?.value.trim(),route,purpose,next,createdAt:now()};rows.unshift(item);save(KEYS.journeys,rows.slice(0,100));queueSync('journey',item);toast('Visit guide created.');renderJourney();};
  function renderInteraction(){const rows=load(KEYS.messages,[]);ensureView('interaction').innerHTML=`
    <div class="card v26-shell"><div class="v26-title"><div><h2>💬 Passenger Interaction Hub</h2><small>Offline local message board for port staff notes, passenger questions, and shift handoff.</small></div><span class="v26-chip ${navigator.onLine?'green':'amber'}">${navigator.onLine?'Online':'Offline'}</span></div></div>
    <div class="card"><div class="card-header">New Message / Handoff Note</div><div class="grid2"><div class="input-group"><label>Sender</label><select id="v26MsgRole"><option>Passenger</option><option>Staff</option><option>Cashier</option><option>Supervisor</option></select></div><div class="input-group"><label>Related Claim optional</label><input id="v26MsgClaim" placeholder="OJ-DMG / ticket number"></div></div><div class="input-group"><label>Message</label><textarea id="v26MsgText" rows="3" placeholder="Type question, note, or instruction..."></textarea></div><button class="primary block" onclick="v26AddMessage()">Save Message</button></div>
    <div class="card"><div class="card-header">Messages</div>${rows.length?rows.slice(0,40).map(msgRow).join(''):'<p class="muted">No messages yet.</p>'}</div><div class="v26-bottom-space"></div>`;}
  function msgRow(m){const cls=String(m.role).toLowerCase()==='passenger'?'passenger':'staff';return `<div class="v26-msg ${cls}"><b>${esc(m.role)}</b> ${m.claim?`<span class="v26-chip">${esc(m.claim)}</span>`:''}<br>${esc(m.text)}<br><small>${esc(m.at)}</small></div>`}
  window.v26AddMessage=function(){const text=$('v26MsgText')?.value.trim();if(!text){toast('Message is required.');return;}const rows=load(KEYS.messages,[]);const item={id:uid('MSG'),role:$('v26MsgRole')?.value||'Passenger',claim:$('v26MsgClaim')?.value.trim(),text,at:now(),done:false};rows.unshift(item);save(KEYS.messages,rows.slice(0,160));queueSync('message',item);toast('Message saved locally.');renderInteraction();};
  function queueSync(type,payload){const q=load(KEYS.sync,[]);q.unshift({id:uid('SYNC'),type,payload,createdAt:now(),status:navigator.onLine?'Ready to export':'Offline pending'});save(KEYS.sync,q.slice(0,220));}
  function renderSync(){const q=load(KEYS.sync,[]);const p=getPrefs();ensureView('sync').innerHTML=`
    <div class="card v26-shell"><div class="v26-title"><div><h2>🔁 Offline Sync Queue</h2><small>Static GitHub Pages cannot auto-send to a central database yet, so this queue protects records for export/import.</small></div><span class="v26-chip ${q.length?'amber':'green'}">${q.length} pending</span></div></div>
    <div class="card"><div class="card-header">Sync Controls</div><div class="v26-action-grid"><button class="v26-action" onclick="v26ExportSync()"><span class="ico">💾</span><b>Export Queue</b><small>Download pending records as JSON.</small></button><button class="v26-action" onclick="v26ClearSync()"><span class="ico">✅</span><b>Mark Clear</b><small>Use after backup/import to server.</small></button><button class="v26-action" onclick="v26ToggleFast()"><span class="ico">📱</span><b>Fast Mode</b><small>${p.fast?'Currently on':'Currently off'}.</small></button><button class="v26-action" onclick="v26FullBackup()"><span class="ico">📦</span><b>Full Local Backup</b><small>Export core app data.</small></button></div></div>
    <div class="card"><div class="card-header">Pending Records</div>${q.length?q.map(syncRow).join(''):'<p class="muted">Sync queue is empty.</p>'}</div><div class="v26-bottom-space"></div>`;}
  function syncRow(x){return `<div class="v26-row"><div><strong>${esc(x.type)} • ${esc(x.id)}</strong><small>${esc(x.status)} • ${esc(x.createdAt)}</small></div><span class="v26-chip amber">Pending</span></div>`}
  window.v26ExportSync=function(){download(JSON.stringify({version:VERSION,exportedAt:now(),queue:load(KEYS.sync,[])},null,2),'application/json','oceanjet_v26_sync_queue_'+today()+'.json');};
  window.v26ClearSync=function(){if(!confirm('Clear local sync queue? Export first.'))return;save(KEYS.sync,[]);toast('Sync queue cleared.');renderSync();};
  window.v26ToggleFast=function(){const p=getPrefs();p.fast=!p.fast;setPrefs(p);toast(p.fast?'Fast Mode on':'Fast Mode off');renderSync();};
  window.v26FullBackup=function(){const data={version:VERSION,exportedAt:now(),claims:load(KEYS.claims,[]),damage:load(KEYS.damage,[]),tickets:load(KEYS.tickets,[]),feedback:load(KEYS.feedback,[]),notices:load(KEYS.notices,[]),messages:load(KEYS.messages,[]),journeys:load(KEYS.journeys,[]),sync:load(KEYS.sync,[]),audit:load(KEYS.audit,[])};download(JSON.stringify(data,null,2),'application/json','oceanjet_v26_full_local_backup_'+today()+'.json');const p=getPrefs();p.lastBackup=now();setPrefs(p);};
  function renderSiteTest(){const m=metrics();const tests=[['HTML loaded',!!document.body,'Document body available'],['Active view exists',!!document.querySelector('.view.active'),'Navigation can show pages'],['Drawer exists',!!$('drawerMenu'),'Left navigation container found'],['Local storage writable',testStorage(),'Records can be saved locally'],['No heavy storage warning',m.st.pct<80,m.st.mb.toFixed(2)+'MB used'],['Admin protected',true,'Admin Panel remains login-only'],['Public tools available',typeof window.showView==='function','Passenger/staff views can open'],['Online status captured',true,navigator.onLine?'Online':'Offline']];const score=Math.round(tests.filter(t=>t[1]).length/tests.length*100);ensureView('site-test').innerHTML=`
    <div class="card v26-shell"><div class="v26-title"><div><h2>🧪 Site Test Center</h2><small>Use after uploading to GitHub Pages or after editing code to confirm the site is not blank.</small></div><span class="v26-chip ${score>85?'green':score>60?'amber':'red'}">${score}% pass</span></div><div class="v26-meter" style="margin-top:10px"><span style="width:${score}%"></span></div></div>
    <div class="card"><div class="card-header">Test Results</div>${tests.map(t=>`<div class="v26-row"><div><strong>${t[1]?'✅':'⚠️'} ${esc(t[0])}</strong><small>${esc(t[2])}</small></div><span class="v26-chip ${t[1]?'green':'amber'}">${t[1]?'Pass':'Check'}</span></div>`).join('')}</div>
    <div class="card"><div class="card-header">Recovery Actions</div><div class="v26-action-grid"><button class="v26-action" onclick="showView('experience')"><span class="ico">🏠</span><b>Open V26 Home</b><small>Return to known safe view.</small></button><button class="v26-action" onclick="location.reload()"><span class="ico">🔄</span><b>Reload</b><small>Refresh app resources.</small></button><button class="v26-action" onclick="v26FullBackup()"><span class="ico">💾</span><b>Backup Now</b><small>Export before clearing data.</small></button><button class="v26-action" onclick="showView('readiness')"><span class="ico">🩺</span><b>Readiness</b><small>Open existing diagnostics.</small></button></div></div><div class="v26-bottom-space"></div>`;audit('site_test','score '+score);}
  function testStorage(){try{localStorage.setItem('__v26_test','1');localStorage.removeItem('__v26_test');return true}catch(e){return false}}
  function download(data,type,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
  function patchDashboard(){const v=$('view-dashboard');if(!v||$('v26Dash'))return;const m=metrics();v.insertAdjacentHTML('afterbegin',`<div id="v26Dash" class="card v26-shell"><div class="v26-title"><div><h2>✨ V26 Experience + Efficiency</h2><small>Passenger journey, interaction hub, sync queue, and site test layer are active.</small></div><span class="v26-chip ${m.score>75?'green':'amber'}">${m.score}% ready</span></div><div class="v26-action-grid" style="margin-top:12px">${action('✨','Experience Home','Open V26 command home','experience')}${action('👤','Passenger Journey','Guided public flow','journey')}${action('💬','Interaction Hub','Local messages','interaction')}${action('🧪','Site Test','Check deployment','site-test')}</div></div>`)}
  function patchPortal(){const v=$('view-portal');if(!v||$('v26Portal'))return;v.insertAdjacentHTML('afterbegin',`<div id="v26Portal" class="card v26-shell"><div class="v26-title"><div><h2>👤 Passenger-first Portal</h2><small>V26 adds guided journey steps, local interaction notes, and offline sync protection.</small></div><span class="v26-chip pink">V26</span></div><div class="v26-action-grid" style="margin-top:12px">${action('👤','Journey Builder','Guide passenger steps','journey')}${action('💬','Interaction Hub','Add note/message','interaction')}${action('🔁','Sync Queue','View pending records','sync')}${action('🧪','Site Test','Verify app works','site-test')}</div></div>`)}
  function patchDrawer(){const menu=$('drawerMenu');if(!menu)return;const items=[['experience','✨','Experience Home'],['journey','👤','Passenger Journey'],['interaction','💬','Interaction Hub'],['sync','🔁','Sync Queue'],['site-test','🧪','Site Test']];for(let i=items.length-1;i>=0;i--){const [view,icon,label]=items[i];if(!menu.querySelector(`.drawer-item[data-view="${view}"]`)){const d=document.createElement('div');d.className='drawer-item';d.dataset.view=view;d.setAttribute('onclick',`navigate('${view}')`);d.innerHTML=`<i>${icon}</i> ${label}`;menu.insertBefore(d,menu.firstChild);}}}
  function showV26(name){qsa('.view').forEach(v=>v.classList.remove('active'));ensureView(name).classList.add('active');if(name==='experience')renderExperienceHome();if(name==='journey')renderJourney();if(name==='interaction')renderInteraction();if(name==='sync')renderSync();if(name==='site-test')renderSiteTest();qsa('#drawerMenu .drawer-item').forEach(el=>el.classList.toggle('active',el.dataset.view===name));try{window.scrollTo({top:0,behavior:getPrefs().fast?'auto':'smooth'})}catch(e){window.scrollTo(0,0)}}
  function patchNavigation(){const views=['experience','journey','interaction','sync','site-test'];const oldShow=window.showView;if(oldShow&&!oldShow.__v26Wrapped){window.showView=function(name){if(views.includes(name)){showV26(name);return;}const r=oldShow.apply(this,arguments);setTimeout(()=>{patchDrawer();if(name==='dashboard')patchDashboard();if(name==='portal')patchPortal();},120);return r;};try{showView=window.showView}catch(e){}window.showView.__v26Wrapped=true;}const oldBuild=window.buildDrawerMenu;if(oldBuild&&!oldBuild.__v26Wrapped){window.buildDrawerMenu=function(){const r=oldBuild.apply(this,arguments);patchDrawer();return r;};try{buildDrawerMenu=window.buildDrawerMenu}catch(e){}window.buildDrawerMenu.__v26Wrapped=true;}}
  function boot(){try{['experience','journey','interaction','sync','site-test'].forEach(ensureView);setPrefs(getPrefs());patchNavigation();if(typeof window.buildDrawerMenu==='function')window.buildDrawerMenu();patchDrawer();setTimeout(()=>{patchDashboard();patchPortal();},500);window.addEventListener('error',e=>audit('js_error',e.message||'unknown error'));window.addEventListener('unhandledrejection',e=>audit('promise_error',e.reason&&e.reason.message?e.reason.message:String(e.reason)));audit('boot',VERSION+' loaded');console.log(VERSION+' loaded');}catch(e){console.error('V26 boot error',e);audit('boot_error',e.message);toast('V26 boot issue: '+e.message)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
