
(function(){
  'use strict';
  if(window.__OJ_V29_PREDICTIVE_SERVICE_OS__) return;
  window.__OJ_V29_PREDICTIVE_SERVICE_OS__ = true;
  const VERSION='V29 Predictive Service OS';
  const KEYS={claims:'oj_passenger_claims_v22',damage:'oj_damage_master_log_v11',sync:'oj_offline_sync_queue_v26',audit:'oj_v29_audit',prefs:'oj_v29_prefs',notices:'oj_public_notices_v25',forecast:'oj_v29_forecasts',journey:'oj_v29_journeys',shift:'oj_v29_shift_plan'};
  const VIEWS=['v29-os','v29-journey','v29-claims','v29-ops','v29-map','v29-admin'];
  const ROUTES=['cebu_tagbilaran','cebu_maasin','cebu_surigao','cebu_siquijor','cebu_dumaguete','cebu_ormoc','cebu_palompon','cebu_getafe'];
  const PORTS=['CEBU','TAGBILARAN','MAASIN','SURIGAO','SIQUIJOR','DUMAGUETE','ORMOC','PALOMPON','GETAFE'];
  const $=id=>document.getElementById(id), qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const now=()=>new Date().toLocaleString('en-PH',{timeZone:'Asia/Manila',hour12:true});
  const uid=p=>p+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase();
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function load(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){return f}}
  function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){audit('storage_error',e.message);return false}}
  function audit(type,msg){const a=load(KEYS.audit,[]);a.unshift({id:uid('V29AUD'),type,msg:String(msg||''),at:now(),online:navigator.onLine});save(KEYS.audit,a.slice(0,220));}
  function toast(msg){try{if(typeof window.toast==='function')return window.toast(msg)}catch(e){} const t=document.createElement('div');t.textContent=msg;t.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);background:#061126;color:white;border:1px solid #61f7ff;border-radius:999px;padding:10px 15px;font:900 12px system-ui;z-index:999999;box-shadow:0 8px 30px #000a';document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
  function ensureView(name){let v=$('view-'+name);if(!v){v=document.createElement('div');v.id='view-'+name;v.className='view';(qs('.app')||document.body).appendChild(v)}return v}
  function isAdmin(){try{return sessionStorage.getItem('oj_v22_admin_unlocked')==='1'||localStorage.getItem('oj_v22_admin_unlocked')==='1'}catch(e){return false}}
  function oldClaims(){return load(KEYS.claims,[])}
  function damages(){return load(KEYS.damage,[])}
  function allClaims(){return [...oldClaims(),...damages()].map(normalizeClaim)}
  function openClaims(){return allClaims().filter(c=>!['closed','resolved','rejected','done'].includes(String(c.status||'new').toLowerCase()))}
  function normalizeClaim(c){return Object.assign({},c,{id:c.claimId||c.caseId||c.id||c.ticketId||'NO-ID',tag:c.tagNo||c.tag||c.baggageTag||'',route:c.route||c.destination||c.dest||'Unknown',status:c.status||c.claimStatus||'New',name:c.passengerName||c.name||c.lastName||'',issue:c.damageType||c.type||c.description||c.notes||'Claim',created:c.createdAt||c.phtTimestamp||c.dateTaken||''})}
  function claimRisk(c){const text=JSON.stringify(c).toLowerCase();let n=16;if(/critical|urgent|wet|missing|crack|broken|wheel|handle|priority|medicine|id|passport/.test(text))n+=34;if(!c.tag)n+=12;if(!c.name)n+=8;if(!c.contact&&!c.phone&&!c.email)n+=8;if(String(c.status).toLowerCase()==='new')n+=10;if(/surigao|dumaguete|siquijor/.test(String(c.route).toLowerCase()))n+=6;return Math.min(100,n)}
  function routeLabel(r){try{if(typeof window.label==='function')return window.label(r)}catch(e){} const map={cebu_tagbilaran:'Cebu → Tagbilaran',cebu_maasin:'Cebu → Maasin',cebu_surigao:'Cebu → Surigao',cebu_siquijor:'Cebu → Siquijor',cebu_dumaguete:'Cebu → Dumaguete',cebu_ormoc:'Cebu → Ormoc',cebu_palompon:'Cebu → Palompon',cebu_getafe:'Cebu → Getafe'};return map[r]||String(r||'Unknown').replace(/_/g,' → ').replace(/\b\w/g,c=>c.toUpperCase())}
  function storage(){let bytes=0;try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';bytes+=(k.length+(localStorage.getItem(k)||'').length)*2}}catch(e){}return{bytes,mb:bytes/1048576,pct:Math.min(100,Math.round(bytes/(4.8*1048576)*100))}}
  function routePressure(route){const c=allClaims().filter(x=>String(x.route).toLowerCase().includes(String(route).split('_').pop())||String(x.route).toLowerCase()===String(route).toLowerCase()).length; const nowHr=new Date().getHours(); const peak=(nowHr>=6&&nowHr<=9)||(nowHr>=15&&nowHr<=19)?18:4; const base=18+peak+(ROUTES.indexOf(route)%4)*7; return Math.min(98,base+c*5+Math.floor(Math.random()*7));}
  function delayRisk(route){const p=routePressure(route); const long=/surigao|dumaguete|siquijor/.test(route)?10:0; return Math.min(96,Math.round(p*.58+long+Math.random()*8));}
  function healthScore(){const st=storage(), oc=openClaims(), urgent=oc.filter(c=>claimRisk(c)>=68), sync=load(KEYS.sync,[]);return Math.max(0,Math.min(100,100-urgent.length*7-sync.length*2-Math.max(0,st.pct-72))) }
  function metrics(){const oc=openClaims(), urgent=oc.filter(c=>claimRisk(c)>=68), sync=load(KEYS.sync,[]), st=storage();return{oc,urgent,sync,st,ready:healthScore(),claims:allClaims(),audit:load(KEYS.audit,[]),notices:load(KEYS.notices,[])}}
  function color(v){return v>=78?'green':v>=55?'amber':'red'}
  function action(ico,title,sub,view){return `<button class="v29-action" onclick="showView('${view}')"><span class="ico">${ico}</span><b>${esc(title)}</b><small>${esc(sub)}</small></button>`}
  function kpis(m){return `<div class="v29-grid3"><div class="v29-kpi"><b>${m.ready}%</b><span>Experience Score</span></div><div class="v29-kpi"><b>${m.oc.length}</b><span>Open Cases</span></div><div class="v29-kpi"><b>${m.urgent.length}</b><span>Priority Risks</span></div></div>`}
  function renderOS(){const m=metrics(); ensureView('v29-os').innerHTML=`
    <div class="card v29-shell"><div class="v29-title"><div><h1>🧠 V29 Predictive Service OS</h1><div class="v29-sub">A major upgrade focused on passenger guidance, staff decision speed, predictive route/claim risk, and mobile reliability.</div></div><span class="v29-chip ${color(m.ready)}">${m.ready}% HEALTH</span></div>${kpis(m)}<div class="v29-meter" style="margin-top:12px"><span style="width:${m.ready}%"></span></div></div>
    <div class="card"><div class="card-header">Predictive action hub</div><div class="v29-grid">${action('🧭','Journey Advisor','Passenger next-steps and route prediction','v29-journey')}${action('🧳','Claims Intelligence','Prioritize and resolve baggage cases faster','v29-claims')}${action('🧑‍💼','Staff Ops Cockpit','Shift load, queue pressure, and staff tasks','v29-ops')}${action('🗺️','Predictive Map','Route pressure radar and port status','v29-map')}${action('🛠️','Admin Control','Locked tools, backup, diagnostics','v29-admin')}${action('🔎','Quick Search','Use existing command search','v27-search')}</div></div>
    <div class="card"><div class="card-header">What needs attention now</div>${recommendations(m)}</div><div class="v29-spacer"></div>`}
  function recommendations(m){const rows=[]; if(m.urgent.length) rows.push(['red','Prioritize baggage claim review',m.urgent.length+' open case(s) may breach service quality.','v29-claims']); if(m.sync.length) rows.push(['amber','Offline data pending',m.sync.length+' local item(s) should be exported/synced.','v29-admin']); if(m.st.pct>72) rows.push(['amber','Storage pressure rising','Export backup and compress local logs.','v29-admin']); const worst=ROUTES.map(r=>({r,p:routePressure(r),d:delayRisk(r)})).sort((a,b)=>b.p-a.p)[0]; if(worst) rows.push([worst.p>74?'red':'amber','Route pressure alert',routeLabel(worst.r)+' pressure '+worst.p+'%, delay risk '+worst.d+'%.','v29-map']); if(!rows.length) rows.push(['green','System looks ready','No critical local issue detected.','v29-journey']); return rows.map(r=>`<div class="v29-row"><div><strong><span class="v29-chip ${r[0]}">${r[0]}</span> ${esc(r[1])}</strong><small>${esc(r[2])}</small></div><button class="sm" onclick="showView('${r[3]}')">Open</button></div>`).join('')}
  function routeOptions(sel){return ROUTES.map(r=>`<option value="${r}" ${sel===r?'selected':''}>${esc(routeLabel(r))}</option>`).join('')}
  function renderJourney(){ensureView('v29-journey').innerHTML=`
    <div class="card v29-shell"><div class="v29-title"><div><h2>🧭 Passenger Journey Advisor</h2><div class="v29-sub">A guided public flow that tells passengers what to do next for fares, schedules, baggage, claims, or delays.</div></div><span class="v29-chip pink">PUBLIC</span></div></div>
    <div class="card"><div class="grid2"><div class="input-group"><label>Passenger Need</label><select id="v29Need" onchange="v29BuildJourney()"><option value="fare">Check fare / route</option><option value="schedule">Check trip schedule</option><option value="damage">Report damaged baggage</option><option value="lost">Report lost baggage</option><option value="status">Track claim status</option><option value="delay">Trip delay help</option></select></div><div class="input-group"><label>Route</label><select id="v29Route" onchange="v29BuildJourney()">${routeOptions('cebu_tagbilaran')}</select></div></div><button class="primary block" onclick="v29BuildJourney()">Build passenger steps</button></div>
    <div class="card"><div class="card-header">Recommended steps</div><div id="v29JourneyOut"></div></div>
    <div class="card"><div class="card-header">Passenger quick tools</div><div class="v29-grid">${action('💵','Fares','Open passenger fares','fares')}${action('🕐','Schedules','Open schedule board','schedules')}${action('🧳','Damage Report','Open damage detector','damage')}${action('🎒','Lost Baggage','Open lost baggage form','lostbaggage')}${action('🔎','Claim Status','Track claim number','claimstatus')}${action('📢','Notices','Read public advisories','noticeboard')}</div></div><div class="v29-spacer"></div>`; setTimeout(()=>window.v29BuildJourney&&window.v29BuildJourney(),40)}
  window.v29BuildJourney=function(){const need=$('v29Need')?.value||'fare', route=$('v29Route')?.value||ROUTES[0]; const p=routePressure(route), d=delayRisk(route); const map={fare:[['Open Fares','Check passenger fare for '+routeLabel(route)+'.'],['Use Baggage Calc only for baggage','Official baggage fee must be computed in the Baggage Calc tab, not the chatbot.'],['Save screenshot/receipt','Passenger can show the result at counter if needed.']],schedule:[['Open Schedules','Confirm latest posted departure for '+routeLabel(route)+'.'],['Check advisory board','Look for route notices and port reminders.'],['Ask staff if risk is high','Current predicted route pressure is '+p+'%.']],damage:[['Open Damage Detector','Capture claim stub, full baggage, and close-up damage photo.'],['Confirm passenger identity','Use PSN + Last Name before saving case.'],['Issue claim number','Passenger tracks status in Claim Status.'],['Escalate if severe','Current claim risk logic prioritizes crack, wet damage, missing parts, and broken handles.']],lost:[['Open Lost Baggage Form','Record tag, route, last seen port, and contact.'],['Mark priority if essential','Passport, medicine, ID, or wallet should be priority.'],['Give claim reference','Passenger tracks using claim number.']],status:[['Open Claim Status','Search claim number or last name.'],['Explain timeline','Submitted → Under Review → Processing → Resolved.'],['Escalate missing updates','If no update, staff should open Claims Intelligence.']],delay:[['Check route risk','Route pressure '+p+'%, predicted delay risk '+d+'%.'],['Open Live Map','See pressure layer and port board.'],['Read Notices','Check if staff posted advisory for '+routeLabel(route)+'.']]}; const out=$('v29JourneyOut'); if(out) out.innerHTML='<div class="v29-flow">'+map[need].map((s,i)=>`<div class="v29-step" data-n="${i+1}"><b>${esc(s[0])}</b><br><small>${esc(s[1])}</small></div>`).join('')+'</div>'; save(KEYS.journey,{need,route,pressure:p,delay:d,lastBuilt:now()});};
  function renderClaims(){const rows=openClaims().map(c=>Object.assign(c,{risk:claimRisk(c)})).sort((a,b)=>b.risk-a.risk); ensureView('v29-claims').innerHTML=`
    <div class="card v29-shell"><div class="v29-title"><div><h2>🧳 Claims Intelligence</h2><div class="v29-sub">Predictive triage for damage/lost baggage. Helps staff pick which claim to handle first.</div></div><span class="v29-chip ${rows.filter(r=>r.risk>=68).length?'red':'green'}">${rows.filter(r=>r.risk>=68).length} PRIORITY</span></div></div>
    <div class="card"><div class="card-header">Smart actions</div><div class="v29-grid">${action('📷','Capture Evidence','Open Damage Detector','damage')}${action('🔎','Track Status','Open Claim Status','claimstatus')}${action('📋','Staff Counter','Open Staff Counter','staffcounter')}${action('📤','Export Center','Open Exports','exportcenter')}</div></div>
    <div class="card"><div class="card-header">Priority Queue</div><div class="v29-table"><table><thead><tr><th>Risk</th><th>Claim</th><th>Route</th><th>Status</th><th>Next Action</th></tr></thead><tbody>${rows.slice(0,40).map(c=>`<tr><td><span class="v29-chip ${c.risk>=68?'red':c.risk>=45?'amber':'green'}">${c.risk}</span></td><td>${esc(c.id)}<br><small>${esc(c.tag||'No tag')}</small></td><td>${esc(routeLabel(c.route))}</td><td>${esc(c.status)}</td><td>${nextAction(c)}</td></tr>`).join('')||'<tr><td colspan="5">No open local claims found.</td></tr>'}</tbody></table></div></div>
    <div class="card"><div class="card-header">Generate Staff Claim Brief</div><button class="primary block" onclick="v29ExportClaimBrief()">Export priority brief JSON</button></div><div class="v29-spacer"></div>`}
  function nextAction(c){if(c.risk>=70)return 'Immediate supervisor review'; if(!c.tag)return 'Complete baggage tag'; if(!c.name)return 'Verify passenger identity'; if(/new/i.test(c.status))return 'Move to Under Review'; return 'Continue processing'}
  window.v29ExportClaimBrief=function(){const data={version:VERSION,exportedAt:now(),priority:openClaims().map(c=>Object.assign(normalizeClaim(c),{risk:claimRisk(normalizeClaim(c)),nextAction:nextAction(normalizeClaim(c))})).sort((a,b)=>b.risk-a.risk)}; download(JSON.stringify(data,null,2),'application/json','oceanjet_v29_claim_priority_brief.json'); audit('export','Claim priority brief exported'); toast('Claim brief exported.');};
  function renderOps(){const m=metrics(); const forecast=ROUTES.map(r=>({route:r,pressure:routePressure(r),delay:delayRisk(r),staff:Math.max(1,Math.round(routePressure(r)/35))})).sort((a,b)=>b.pressure-a.pressure); ensureView('v29-ops').innerHTML=`
    <div class="card v29-shell"><div class="v29-title"><div><h2>🧑‍💼 Staff Ops Cockpit</h2><div class="v29-sub">Forecasts service pressure and suggests shift workload for baggage counter, cashier, and passenger assistance.</div></div><span class="v29-chip blue">FORECAST</span></div>${kpis(m)}</div>
    <div class="card"><div class="card-header">One-minute shift plan</div><div id="v29ShiftPlan">${shiftPlanHTML(forecast,m)}</div><button class="primary block" onclick="v29SaveShiftPlan()">Save Shift Plan</button></div>
    <div class="card"><div class="card-header">Route workload forecast</div><div class="v29-table"><table><thead><tr><th>Route</th><th>Pressure</th><th>Delay Risk</th><th>Suggested Staff</th></tr></thead><tbody>${forecast.map(f=>`<tr><td>${esc(routeLabel(f.route))}</td><td><span class="v29-chip ${color(100-f.pressure)}">${f.pressure}%</span></td><td>${f.delay}%</td><td>${f.staff}</td></tr>`).join('')}</tbody></table></div></div><div class="v29-spacer"></div>`}
  function shiftPlanHTML(forecast,m){const top=forecast.slice(0,3); const tasks=[`Assign ${Math.max(1,m.urgent.length)} staff to priority baggage claims.`,`Post public notice for ${routeLabel(top[0].route)} if pressure remains above ${top[0].pressure}%.`,`Prepare backup export before shift handover.`,`Keep one counter focused on passenger claim status lookups.`]; return '<div class="v29-flow">'+tasks.map((t,i)=>`<div class="v29-step" data-n="${i+1}"><b>${esc(t)}</b></div>`).join('')+'</div>'}
  window.v29SaveShiftPlan=function(){const m=metrics();const forecast=ROUTES.map(r=>({route:r,pressure:routePressure(r),delay:delayRisk(r)}));save(KEYS.shift,{savedAt:now(),health:m.ready,openClaims:m.oc.length,priority:m.urgent.length,forecast});audit('shift','V29 shift plan saved');toast('Shift plan saved locally.');};
  function renderMap(){const items=ROUTES.map((r,i)=>({r,p:routePressure(r),d:delayRisk(r),x:[12,30,62,80,45,18,72,54][i],y:[40,72,46,66,30,18,23,82][i]})); ensureView('v29-map').innerHTML=`
    <div class="card v29-shell"><div class="v29-title"><div><h2>🗺️ Predictive Map + Route Radar</h2><div class="v29-sub">Offline-friendly simulation layer: route pressure, delay risk, and port readiness. Can later connect to real GPS/AIS/weather APIs.</div></div><span class="v29-chip amber">SIMULATED</span></div></div>
    <div class="card"><div class="v29-radar">${items.map((it,i)=>`<span class="v29-port ${it.p>72?'hot':'ok'}" style="left:${it.x}%;top:${it.y}%">${PORTS[i]||'PORT'} ${it.p}%</span>`).join('')}</div></div>
    <div class="card"><div class="card-header">Route pressure board</div><div class="v29-table"><table><thead><tr><th>Route</th><th>Pressure</th><th>Delay Risk</th><th>Suggestion</th></tr></thead><tbody>${items.sort((a,b)=>b.p-a.p).map(it=>`<tr><td>${esc(routeLabel(it.r))}</td><td><span class="v29-chip ${it.p>72?'red':it.p>50?'amber':'green'}">${it.p}%</span></td><td>${it.d}%</td><td>${it.p>72?'Prepare notice + staff':it.p>50?'Monitor queue':'Normal'}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="card"><div class="card-header">Open existing Live Map</div><button class="accent block" onclick="showView('map')">Open original Live Map tab</button></div><div class="v29-spacer"></div>`}
  function renderAdmin(){const m=metrics(); const locked=!isAdmin(); ensureView('v29-admin').innerHTML=`
    <div class="card v29-shell"><div class="v29-title"><div><h2>🛠️ V29 Admin Control</h2><div class="v29-sub">Protected tools for diagnostics, backup, local integrity, and predictive data export.</div></div><span class="v29-chip ${locked?'red':'green'}">${locked?'LOCKED':'UNLOCKED'}</span></div></div>
    ${locked?adminLoginHTML():adminToolsHTML(m)}<div class="v29-spacer"></div>`}
  function adminLoginHTML(){return `<div class="card"><div class="card-header">Admin login required</div><div class="grid2"><div class="input-group"><label>Username</label><input id="v29AdminUser" placeholder="admin"></div><div class="input-group"><label>Password</label><input id="v29AdminPass" type="password" placeholder="admin"></div></div><button class="primary block" onclick="v29UnlockAdmin()">Unlock V29 Admin Tools</button><p class="muted">Demo credentials: admin/admin, demo/demo, supervisor/supervisor</p></div>`}
  function adminToolsHTML(m){return `<div class="card"><div class="card-header">System diagnostics</div>${kpis(m)}<div class="v29-row"><div><strong>Storage</strong><small>${m.st.mb.toFixed(2)} MB • ${m.st.pct}% estimated browser storage</small></div></div><div class="v29-row"><div><strong>Audit events</strong><small>${m.audit.length} local V29 events</small></div></div></div><div class="card"><div class="card-header">Admin exports and repair</div><div class="v29-grid">${buttonHTML('📦','Full V29 Snapshot','Export app snapshot','v29ExportSnapshot()')}${buttonHTML('🧹','Compact Audit','Keep latest logs only','v29CompactAudit()')}${buttonHTML('🧪','Run Health Test','Check core views and storage','v29HealthTest()')}${buttonHTML('🔒','Lock Admin','Return to protected mode','v29LockAdmin()')}</div></div>`}
  function buttonHTML(ico,title,sub,fn){return `<button class="v29-action" onclick="${fn}"><span class="ico">${ico}</span><b>${esc(title)}</b><small>${esc(sub)}</small></button>`}
  window.v29UnlockAdmin=function(){const u=$('v29AdminUser')?.value||'', p=$('v29AdminPass')?.value||''; const ok=(u==='admin'&&p==='admin')||(u==='demo'&&p==='demo')||(u==='supervisor'&&p==='supervisor'); if(ok){sessionStorage.setItem('oj_v22_admin_unlocked','1');audit('admin','V29 admin unlocked');toast('Admin unlocked.');renderAdmin()}else toast('Wrong admin login.');};
  window.v29LockAdmin=function(){sessionStorage.removeItem('oj_v22_admin_unlocked');localStorage.removeItem('oj_v22_admin_unlocked');audit('admin','V29 admin locked');toast('Admin locked.');renderAdmin();};
  window.v29CompactAudit=function(){save(KEYS.audit,load(KEYS.audit,[]).slice(0,50));toast('V29 audit compacted.');renderAdmin();};
  window.v29HealthTest=function(){const result={at:now(),views:VIEWS.map(v=>({view:v,exists:!!$('view-'+v)})),storage:storage(),claims:allClaims().length,online:navigator.onLine};audit('health_test',JSON.stringify(result));toast('Health test done.');download(JSON.stringify(result,null,2),'application/json','oceanjet_v29_health_test.json')};
  window.v29ExportSnapshot=function(){const data={version:VERSION,exportedAt:now(),metrics:metrics(),claims:oldClaims(),damage:damages(),sync:load(KEYS.sync,[]),notices:load(KEYS.notices,[]),audit:load(KEYS.audit,[]),journey:load(KEYS.journey,{}),shift:load(KEYS.shift,{})};download(JSON.stringify(data,null,2),'application/json','oceanjet_v29_full_snapshot.json');audit('export','Full snapshot exported');toast('Full snapshot exported.');};
  function download(data,type,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  const renderers={'v29-os':renderOS,'v29-journey':renderJourney,'v29-claims':renderClaims,'v29-ops':renderOps,'v29-map':renderMap,'v29-admin':renderAdmin};
  function patchNav(){const old=window.buildDrawerMenu; window.buildDrawerMenu=function(){try{if(typeof old==='function') old(); const menu=$('drawerMenu'); if(!menu)return; const add=(view,label,ico)=>{if(!menu.querySelector(`[data-view="${view}"]`)) menu.insertAdjacentHTML('beforeend',`<div class="drawer-item" data-view="${view}" onclick="showView('${view}')"><i>${ico}</i> ${label}</div>`)}; add('v29-os','V29 Predictive OS','🧠'); add('v29-journey','Journey Advisor','🧭'); add('v29-claims','Claims Intel','🧳'); add('v29-ops','Staff Ops','🧑‍💼'); add('v29-map','Predictive Map','🗺️'); add('v29-admin','V29 Admin','🛠️');}catch(e){console.error(e)}};
    const oldShow=window.showView; window.showView=function(name){try{if(renderers[name]){qsa('.view').forEach(v=>v.classList.remove('active'));ensureView(name).classList.add('active');qsa('.drawer-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));renderers[name]();return;} }catch(e){console.error('V29 show error',e);audit('show_error',e.message)} if(typeof oldShow==='function')return oldShow(name);};
    const oldNav=window.navigate; window.navigate=function(name){if(renderers[name]) return window.showView(name); if(typeof oldNav==='function') return oldNav(name); if(typeof window.showView==='function') return window.showView(name);};
  }
  function patchDashboard(){try{const v=$('view-dashboard'); if(!v||$('v29Dash')) return; const m=metrics(); v.insertAdjacentHTML('afterbegin',`<div id="v29Dash" class="card v29-shell"><div class="v29-title"><div><h2>🧠 V29 Predictive Service Layer</h2><div class="v29-sub">Experience ${m.ready}% • ${m.oc.length} open claims • ${m.urgent.length} priority risks</div></div><button class="sm primary" onclick="showView('v29-os')">Open V29</button></div></div>`)}catch(e){}}
  function patchMap(){try{const v=$('view-map'); if(!v||$('v29MapPatch')) return; v.insertAdjacentHTML('afterbegin',`<div id="v29MapPatch" class="card v29-shell"><div class="v29-title"><div><h2>🗺️ V29 Predictive Route Radar</h2><div class="v29-sub">Open the predictive map for route pressure, delay risk, and port readiness.</div></div><button class="sm accent" onclick="showView('v29-map')">Predict</button></div></div>`)}catch(e){}}
  function boot(){try{document.body.classList.add('v29-polish'); VIEWS.forEach(ensureView); patchNav(); if(typeof window.buildDrawerMenu==='function') window.buildDrawerMenu(); setTimeout(()=>{patchDashboard();patchMap()},750); audit('boot',VERSION+' loaded'); console.log(VERSION+' loaded')}catch(e){console.error('V29 boot error',e);audit('boot_error',e.message);toast('V29 recovery: '+e.message)}}
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})();
